<?php $i=0;foreach ($this->notapreview->contenido as $contenido): ?> 
     {% if contenido['tipo'] == "audio" %}
    <section class="img-news img-principal">                                           
    
    <div id="swfplayer_open" class="nd_galeriaopen_">
</div>
<div class="help-media">
      <?php echo @$contenido['audio']['descripcion']; ?> <?php if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php endif;?>
      <?php if(!empty(@$contenido['credito'])): ?>
      | <strong>Fotógrafo:</strong>  : {{contenido['credito']}}
      <?php endif;?>
      </div>
<script type="text/javascript">setJW7("swfplayer_open", "{{contenido['audio']['url']}}", "{{contenido['audio']['url_cover']}}", undefined, undefined, "{{model.preroll}}");</script>
    </section>
     <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
     
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>