<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" id='tema' class="{{model.tema}} topics" data-x="lazy, columns-fit, sticky, media, column-fix, social-native">
<div  id="wrap">
    <!--Header-->
    {{ partial('partials/header/indextag_1'  ) }}
    <div id="content" role="main">
        {{ partial('partials/ads/top') }}
        <div class="grid pad">

 

            {{ partial('tag/cabecera/cb_' ~ model.slug , ['portada':'encuestas'] ) }}
            <style>
    .iframeWrapper {
        position: relative;
        padding-bottom: 58.75%;
        padding-top: 25px;
        height: 0;
    }
    .iframeWrapper iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
    @media (max-width: 767px) {
        .iframeWrapper {
            margin-top: 10px;
        }
    }
  </style>

  <div class="iframeWrapper grid pad">
         <iframe style="width:100%; margin-bottom:20px; height:640pxgit" src="http://rpp.pe/elecciones-peru-2016/infografia_evolucion_intencion_de_voto.html" frameborder="0" scrolling="no" ></iframe>
  </div>

<div style="height:20px"></div>
            {{ partial('partials/ads/middle2') }}


        </div>
        </div>
        

    




    
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}

    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
