<div class="alerta alertadeporte full group">
    <a href="{{model.alert.url}}">
        <span class="icon icon-20"></span>
        <div class="alerta-wrap group">
            <div class="alerta-deporte-wrap group">
                <h2>{{model.alert.titulo}}</h2>
                <div class="alerta-cont">
                    <h2>En Vivo</h2>
                    <p>{{model.alert.cuerpo}}</p>
                    <p id="hashtag"></p>
                </div>
                <div id="RST1" class="alerta-marcador group">
                    <script>
                        //rppWR.read({events: 'eliminatorias', type: 'mam', matchId: '{{model.alert.data_factory_id}}'}).renderMaM({id: '#RST1', url: 'www.google.com.pe'});
                    </script>                    
                </div>
            </div>
            <figure>
                <img src="{{model.alert.imagen}}" alt="{{model.alert.titulo}}">
            </figure>
        </div>
    </a>
</div>