
<div class="alerta alertadeporte group">
    <a href="{{model.alert.url|default('#')|lower}}">
        <span class="icon icon-20"></span>
        <div class="alerta-wrap group">
            <div class="alerta-cont">
                <h2>{{model.alert.titulo}}</h2>
                <p>{{model.alert.cuerpo}}</p>
            </div>
            <div id="RST1" class="alerta-marcador group">
                <script>
                    //rppWR.read({events: '{{model.alert.campeonato}}', type: 'mam', matchId: '{{model.alert.data_factory_id}}'}).renderMaM({id: '#RST1', url: 'rpp.pe'});
                </script>                    
            </div>
        </div>
    </a>
</div>