
    {{ partial('partials/nota/header/index' ~ model.package) }}       


<div class="gallery-single">
   
        <?php $i=0; foreach ($this->notapreview->contenido as $contenido): ?>  
         {% if contenido['tipo'] == "photo" %}
            <section class="img-news">                                           
            <figure class="media full">
            <img src="{{contenido['foto']['data']['data']}}" alt="{{contenido['foto']['alt']}}">
            
            <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?> 
          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}            
            </figcaption>
            </figure>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {% break  %}
         {% elseif contenido['tipo'] == "embed" %}
       <p>
        {{contenido['embed']}}
        </p>
       <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
         {% elseif contenido['tipo'] == "video" %}
            <section class="img-news">
            <div id="swfplayer_open" class="nd_galeriaopen_">   </div>
            <div class="help-media">
            <?php echo @$contenido['video']['descripcion']; ?>
                          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}
            </div>
            <script type="text/javascript">setJW7("swfplayer_open", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}','{{contenido['video']['hash']}}');</script>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% elseif contenido['tipo'] == "youtube" %}
         <section class="img-news">
         <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
         <div class="help-media">
            <?php echo @$contenido['youtube']['descripcion']; ?>
            <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}
            </div></section>
         <?php if(empty($contenido['youtube']['url_cover'])) : ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg");</script>
         <?php else: ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "{{contenido['youtube']['url_cover']}}");</script>
         <?php endif;?> 
         <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% endif  %}
         <?php $i++?>
<?php endforeach;?>
   


</div>

<div class="wrap group">
    <div class="content group">  
        <div class="entry-content group">
            {{ partial('partials/nota/detalle/social') }}
            {{ partial('partials/nota/detalle/socialmobile') }}
            <div class="cont ajust_win">
                {{ partial('partials/nota/detalle/open/' ~ model.package ) }}
                {{ partial('partials/nota/detalle/block/firma/'~model.package) }} 
                {{ partial('partials/nota/detalle/content/'~model.package) }}                            
                <!-- .social-share -->                            
                {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
            </div>
            <!-- .cont -->
        </div>
        <!-- .entry-content -->

 <?php if(!(@$this->notapreview->comentariosfb === false) ) :?>       
 <div class="news-comments" id="ancla-comments">
    <h2 class="panel-title">¿Qué opinas?</h2>
    <div id="fbCommentPage" class="fb-comments" data-href="{{host}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
</div>
        <!-- .comments -->
<?php endif;?>


    </div>   
    <!-- .content -->
    <aside class="sidebar">
        {{ partial('partials/ads/right') }}
        {{ partial('partials/nota/sidebar/mas_en_tag' ,[], trackurl ) }}
        {{ partial('partials/ads/perured_nota') }} 
        <!-- pub-300 -->                   
        {{ partial('partials/ads/right1') }}
    </aside>
    <!-- .sidebar -->
</div>