{% cache "nota.article.body." ~ model.nid 0 %}
<div class="col-primary main">
  <div class="section">
    {{ partial('partials/nota/detalle/social') }}
    
    <div itemprop="articleBody" id="article-body" class="col-detail">
        {{ partial('partials/nota/detalle/open/' ~ model.package ) }}        
        {{ partial('partials/nota/detalle/content/'~model.package) }}  <!-- aqui va el contenido medio de la nota -->
    </div>
    {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
    
  </div>
 {{ partial('partials/nota/ads/interna_doble' ) }} 
  <?php if(!(@\Rpp\Services\Get\Content::part($this->model->nid,'comentariosfb')===false)) :?>
  <div class="comments box-mod">
    <div class="box-header">
      <div class="title">¿Qué opinas?<a name="section-comment"></a></div>
    </div>
    <div data-href="{{host}}{{nUrl(model.nid)}}" data-numposts="5" data-width="100%" class="fb-comments"></div>
    <div id="fb-root"></div>
    <script type="text/javascript">
         (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=1065644730116597";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
  </div>
  <?php endif;?>
{{ partial('partials/nota/ads/interna_doble_close' ) }}   
{{ partial('partials/nota/sugeridas/index' , [] , trackurl ) }}
</div>
<!-- .comments -->
{% endcache %} 

{{ partial('partials/nota/sidebar/index') }} 