{% cache "nota.article.body." ~ model.nid 0 %}
{{ partial('partials/nota/header/index' ~ model.package, ['plantjp':'1']) }}      
 <div class="infographic widen">
    <?php $i=0;foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $contenido): ?> 

 
  {% if contenido['tipo'] == "photo" %}

     <!-- foto-->
      <div class="media-info">
        <figure itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
          <meta itemprop="width" content="635">
          <meta itemprop="height" content="357">
          <div ><img itemprop="url" content="{{cdn_image( contenido['foto']['hash'] ,'normal')}}" src="{{contenido['foto']['url']}}" alt="{{contenido['subtitulo']}}" title="{{contenido['subtitulo']}}"></div>
          <figcaption itemprop="description"><?php echo @$contenido['foto']['alt']; ?>
          {% if not(contenido['via'] is empty) %}
          | <strong>Fuente:</strong> {{ contenido['via'] }}
          {% endif %}
          {% if not(contenido['credito'] is empty) %}
          | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
          {% endif %}   
          </figcaption>
        </figure>
      </div>

     <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "embed" %}
       <div>{{contenido['embed']}}</div>    
       <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "video" %}
       <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] =$contenido['video']['url']; 
      $gene_img['video_img'] =$contenido['video']['url_cover']; 
      if(!isset($contenido['video']['playlist'])){ $contenido['video']['playlist']='[]'; }
      $gene_img['playlist'] =json_encode($contenido['video']['playlist']); 
      $gene_img['hash'] =$contenido['video']['hash'];
      $gene_img['rtag'] =$this->model->preroll;
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- video-->
      <div itemprop="video" itemscope itemtype="http://schema.org/VideoObject" itemref="author-name" class="media">
        <meta itemprop="encodingFormat" content="mp4">
        <meta itemprop="uploadDate" content="<?=date(DATE_ATOM,\Rpp\Services\Get\Content::node($this->model->nid)->fecha_publicacion);?>">
        <meta itemprop="contentUrl" content="<?=$gene_img['video_source'];?>">
        <meta itemprop="duration" content="<?php echo @$contenido['video']['duracion']; ?>">
        <figure>
            <div class="cover cover-media">
                <a href="#video" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img itemprop="thumbnailURL" src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['video']['descripcion']; ?>"><span class="icon-play"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['video']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
        </figcaption>
        </figure>
      </div>
       <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "youtube" %}
        <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] ="https://www.youtube.com/watch?v=".$contenido['youtube']['id'];
      if(empty($contenido['youtube']['url_cover'])){
        $gene_img['video_img'] =  "http://img.youtube.com/vi/".$contenido['youtube']['id']."/0.jpg"; 
      } else{
        $gene_img['video_img'] =  $contenido['youtube']['url_cover']; 
      }
      
      if(!isset($contenido['youtube']['playlist'])){ $contenido['youtube']['playlist']='[]'; }
      $gene_img['playlist'] =json_encode($contenido['youtube']['playlist']); 
      $gene_img['hash'] ='undefined';
      $gene_img['rtag'] =$this->model->preroll;
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- youtube-->
      <div itemprop="video" itemscope itemtype="http://schema.org/VideoObject" class="media">
        <figure>
            <div class="cover cover-media">
                <a href="#video" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['youtube']['descripcion']; ?>"><span class="icon-video"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['youtube']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
          </figcaption>
        </figure>
      </div> 
     <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
    
  

 <?php endforeach;?>

</div>

<div class="col-primary main">
  <div class="section">
    {{ partial('partials/nota/detalle/social') }}
    
    <div itemprop="articleBody" id="article-body" class="col-detail">
        {{ partial('partials/ads/interna_full' , ['position':1]) }}  
        {{ partial('partials/nota/detalle/content/'~model.package) }}  <!-- aqui va el contenido medio de la nota -->
    </div>
    {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
    
  </div>
  {{ partial('partials/nota/ads/interna_doble' ) }}  
  <?php if(!(@\Rpp\Services\Get\Content::part($this->model->nid,'comentariosfb')===false)) :?>
  <div class="comments box-mod">
    <div class="box-header">
      <div class="title">¿Qué opinas?<a name="section-comment"></a></div>
    </div>
    <div data-href="{{host}}{{nUrl(model.nid)}}" data-numposts="5" data-width="100%" class="fb-comments"></div>
    <div id="fb-root"></div>
    <script type="text/javascript">
         (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=1065644730116597";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
  </div>
  <?php endif;?>
{{ partial('partials/nota/ads/interna_doble_close' ) }}
{{ partial('partials/nota/sugeridas/index' , [] , trackurl ) }}
</div>

{{ partial('partials/nota/sidebar/index') }} 

{% endcache %} 