
    {{ partial('partials/nota/header/index' ~ model.package, ['plantjp':'1']) }}       


<div class="gallery-single">
   
        <?php $i=0; foreach ($this->notapreview->contenido as $contenido): ?>  
         {% if contenido['tipo'] == "photo" %}
            <section class="img-news">                                           
            <figure class="media full">
            <img src="{{contenido['foto']['data']['data']}}" alt="{{contenido['foto']['alt']}}">
            
            <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?> 
          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}            
            </figcaption>
            </figure>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {% break  %}
         {% elseif contenido['tipo'] == "embed" %}
       <p>
        {{contenido['embed']}}
        </p>
       <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
         {% elseif contenido['tipo'] == "video" %}
            <section class="img-news">
            <div id="swfplayer_open" class="nd_galeriaopen_">   </div>
            <div class="help-media">
            <?php echo @$contenido['video']['descripcion']; ?>
                          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}
            </div>
            <script type="text/javascript">setJW7("swfplayer_open", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}','{{contenido['video']['hash']}}');</script>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% elseif contenido['tipo'] == "youtube" %}
         <section class="img-news">
         <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
         <div class="help-media">
            <?php echo @$contenido['youtube']['descripcion']; ?>
            <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}
            </div></section>
         <?php if(empty($contenido['youtube']['url_cover'])) : ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg");</script>
         <?php else: ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "{{contenido['youtube']['url_cover']}}");</script>
         <?php endif;?> 
         <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% endif  %}
         <?php $i++?>
<?php endforeach;?>
</div>

<div class="col-primary main">
  <div class="section">
    {{ partial('partials/nota/detalle/socialpreview') }}
    
    <div itemprop="articleBody" id="article-body" class="col-detail">
        {{ partial('partials/nota/detalle/open/' ~ model.package ) }}   
        {{ partial('partials/ads/interna_full' , ['position':1]) }}       
        {{ partial('partials/nota/detalle/content/'~model.package) }}  <!-- aqui va el contenido medio de la nota -->
    </div>
    {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
    
  </div>
  {{ partial('partials/nota/ads/interna_doble' ) }}  
  <?php if(!(@$this->notapreview->comentariosfb === false)) :?>
  <div class="comments box-mod">
    <div class="box-header">
      <div class="title">¿Qué opinas?<a name="section-comment"></a></div>
    </div>
    <div data-href="{{host}}" data-numposts="5" data-width="100%" class="fb-comments"></div>
    <div id="fb-root"></div>
    <script type="text/javascript">
         (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=1065644730116597";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
  </div>
  <?php endif;?>
{{ partial('partials/nota/ads/interna_doble_close' ) }}
</div>
<!-- .comments -->
{{ partial('partials/nota/sidebar/index') }} 