<div id="x-fixed-menutop" class="hdr-body <?= @$varimenusm; ?>">
    <div class="inner">
        <div class="grid">
            <div id="organization" itemprop="publisher" itemscope="" itemtype="https://schema.org/Organization"
                 class="logo">
                <meta itemprop="name" content="RPP Noticias">
                <meta itemprop="url" content="{{host}}">
                <div itemprop="logo" itemscope="" itemtype="https://schema.org/ImageObject">
                    <meta itemprop="width" content="153">
                    <meta itemprop="height" content="63">
                    <a href="{{host}}" {{model.htmlrel}}><img itemprop="url" content="{{ehost}}/static/img/logo-rpp.png"
                                            src="{{ehost}}/static/img/logo-rpp.svg?v={{eversion}}" alt="RPP Noticias"
                                            title="RPP Noticias" class="logo-rpp-main"  ></a>
                </div>
            </div>
            <div class="content-side">
                <div class="col col-live"><a href="{{host}}/radioenvivo" class="envivo" {{model.htmlrel}}><img
                            src="{{ehost}}/static/img/envv.svg" alt="En Vivo" class="ico"><span
                            class="titu">En Vivo: <strong id="online"></strong></span></a></div>
<div class="col col-resume"><a href="/el-gran-resumen-de-la-hora" class="resume-link" {{model.htmlrel}}><span
                                class="icon-play"></span><span class="titu">Resumen de la hora</span></a></div>
                <div class="col col-social">
                        <div class="social inverse">
                            {{ partial('partials/header/redessociales' ,[] ) }}
                        </div>
                </div>
                <div class="col col-options">
                    <div class="nav-right">
                        <ul>
                            <li class="opt-menu"><a href="#opciones" id="btn-menu" {{model.htmlrel}}><span class="icon-list"></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-nav">
            <div class="grid content-nav">
                <nav class="nav-main">
                    <div class="account">
                        <div class="row buttons">
                            <ul>
                                <li><a id="btn-edition" href="#" {{model.htmlrel}}>Edición general<span class="icon-chevron-down"></span></a>
                                </li>
                            </ul>
                        </div>
                        <div class="row list">
                            <ul>
                                <li><a href="/" {{model.htmlrel}}>Edición General</a></li>
                                <li><a href="/peru/arequipa" {{model.htmlrel}}>Arequipa</a></li>
                                <li><a href="/peru/la-libertad" {{model.htmlrel}}>La Libertad</a></li>
                                <li><a href="/peru/lambayeque" {{model.htmlrel}}>Lambayeque</a></li>
                                <li><a href="/peru/junin" {{model.htmlrel}}>Junín</a></li>
                                <li><a href="/peru/ancash" {{model.htmlrel}}>Ancash</a></li>
                                <li><a href="/peru/ica" {{model.htmlrel}}>Ica</a></li>
                                <li><a href="/peru/puno" {{model.htmlrel}}>Puno</a></li>
                                <li><a href="/peru/piura" {{model.htmlrel}}>Piura</a></li>
                                <li><a href="/peru/cusco" {{model.htmlrel}}>Cusco</a></li>
                            </ul>
                        </div>
                    </div>
                    <form action="/buscar" method="POST" onsubmit='fn(this, event, {"method":"search"})'
                          class="search-form">
                        <input id="search-input-menu" type="search" name="texto" placeholder="Ingrese su búsqueda"
                               class="search-input">
                        <button><span class="icon-magnifier"></span></button>
                    </form>
                    <div class="issues">
                        <div class="title">Temas</div>
                        <div class="topics-list">
                            <ul>
                                <?php if (@\Rpp\Services\Get\Temas::get_temas()): ?>
                                    <?php foreach (\Rpp\Services\Get\Temas::get_temas()->tags as $tema) : ?>
                                        <li>
                                            <a href="{{host}}/tema-{{tema['slug']}}?ns_source=self&ns_mchannel=portada.home&ns_campaign=menu.temas" {{model.htmlrel}}>{{tema['nombre']}}</a>
                                        </li>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>

                    <div class="title">Secciones</div>
                    {{ partial('partials/header/menu' ,[] ) }}
                    <div class="services">
                        <div class="title">Servicios</div>
                        <div class="inner">
                            <ul>
                                <li><a href="/tema-rotafono" {{model.htmlrel}}><span class="icon-rotafono"></span><span class="title">Rotafono</span></a>
                                </li>
                                <li><a href="/tema-trafico" {{model.htmlrel}}><span class="icon-bus"></span><span
                                            class="title">Tráfico</span></a></li>
                                <li><a href="/virales/cine" {{model.htmlrel}}><span class="icon-movie"></span><span
                                            class="title">Cine</span></a></li>
                                <li><a href="/tema-clima" {{model.htmlrel}}><span class="icon-cloud-sun"></span><span
                                            class="title">Clima</span></a></li>
                            </ul>
                        </div>
                    </div>
                    <form action="/" method="GET" class="newsletter-form">
                        <div class="title">suscríbete a nuestro newsletter</div>
                        <div class="inner">
                            <input type="search" name="email" placeholder="Email" class="search-input">
                            <button><span class="icon-envelope"></span></button>
                        </div>
                    </form>
                    <div class="en-redes">
                        <div class="title">RPP en las Redes Sociales</div>
                        <div class="social">
                            {{ partial('partials/header/redessociales' ,[] ) }}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>