<ul class="menubar">
    <li><a href="/politica" {{model.htmlrel}}>Política</a></li>
    <li><a href="/actualidad" {{model.htmlrel}}>Actualidad</a></li>
    <li><a href="/deportes" {{model.htmlrel}}>Deportes</a></li>
    <li><a href="/entretenimiento" {{model.htmlrel}}>Entretenimiento</a></li>
    <li><a href="/peru" {{model.htmlrel}}>Perú</a></li>
    <li><a href="/mundo" {{model.htmlrel}}>Mundo</a></li>
    <li><a href="/economia" {{model.htmlrel}}>Economía</a></li>
    <li><a href="/vida" {{model.htmlrel}}>Vida</a></li>
    <li><a href="/tecno" {{model.htmlrel}}>Tecno</a></li>
    <li><a href="/viral" {{model.htmlrel}}>Viral</a></li>
    <li><a href="/autores" {{model.htmlrel}}>Autores</a></li>
    <li><a href="/programacion/radio" {{model.htmlrel}}>Radio </a></li>
    <li><a href="/programacion/tv" {{model.htmlrel}}>TV </a></li>
</ul>