<nav class="nav-top">
              <ul>
                <li><a href="/" <?php if($this->model->comscore == 'home.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Edición General</a></li>
                <li><a href="/peru/arequipa" <?php if($this->model->comscore == 'peru.arequipa.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Arequipa</a></li>
                <li><a href="/peru/la-libertad" <?php if($this->model->comscore == 'peru.la-libertad.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>La Libertad</a></li>
                <li><a href="/peru/lambayeque" <?php if($this->model->comscore == 'peru.lambayeque.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Lambayeque</a></li>
                <li><a href="/peru/junin" <?php if($this->model->comscore == 'peru.junin.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Junín</a></li>
                <li><a href="/peru/ancash" <?php if($this->model->comscore == 'peru.ancash.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Ancash</a></li>
                <li><a href="/peru/ica" <?php if($this->model->comscore == 'peru.ica.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Ica</a></li>
                <li><a href="/peru/puno"<?php if($this->model->comscore == 'peru.puno.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Puno</a></li>
                <li><a href="/peru/piura" <?php if($this->model->comscore == 'peru.piura.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Piura</a></li>
                <li><a href="/peru/cusco" <?php if($this->model->comscore == 'peru.cusco.portada'):?>class="active"<?php endif;?> {{model.htmlrel}}>Cusco</a></li>
              </ul>
</nav>