<ul>
	<li class="fb"><a href="https://www.facebook.com/rppnoticias" target="_blank" {{model.htmlrel}}><span class="icon-facebook"></span></a></li>
	<li class="tw"><a href="https://twitter.com/rppnoticias" target="_blank" {{model.htmlrel}}><span class="icon-twitter"></span></a></li>
	<li class="yt"><a href="https://www.youtube.com/user/RPPNOTICIAS" target="_blank" {{model.htmlrel}}><span class="icon-youtube"></span></a></li>
	<li class="rss"><a href="{{host}}/rss" {{model.htmlrel}}><span class="icon-rss"></span></a></li>
</ul>