<section class="connect">
  <h4>Conéctate a la 10</h4>
  <ul>
    <li><a target="_blank" href="https://www.facebook.com/La10.pe" class="wrapper-icon-connect"><i class="icon icon-facebook"></i></a></li>
    <li><a target="_blank" href="https://twitter.com/La10Pe" class="wrapper-icon-connect"><i class="icon icon-twitter"></i></a></li>
    <li><a target="_blank" href="https://plus.google.com/+La10Pe/posts" class="wrapper-icon-connect"><i class="icon icon-google-plus"></i></a></li>
  </ul>
</section>
