<div class="gallery-single slider">
	<div id="slider">
	    <?php foreach ($this->notapreview->contenido as $key => $contenido): ?> 
        	<?php if ($contenido['tipo'] == 'photo') { ?> 
        <figure class="hmedia">
            {{ partial('partials/nota/contenido/bloque/'~model.package~'imagen',contenido) }}
            <figcaption><?php echo @$contenido['foto']['alt']; ?> | <strong>Fuente:</strong> {{contenido['via']}}  <?php echo @$contenido['credito']; ?></figcaption>
        </figure>
        	<?php break; } ?>
    	<?php endforeach;?>
        <ul class="gallery-nav">
            
            <li><a class="btn-prev" href="#"><span>Anterior</span></a></li>
           
           
            <li><a class="btn-next" href="#"><span>Siguiente</span></a></li>
            
        </ul>
	</div>

	<div id="carouselnormal" class="flexslider carousel">
		<ul class="slides group">
            <?php foreach ($this->notapreview->contenido as $key => $contenido): ?> 
        	<?php if ($contenido['tipo'] == 'photo') { ?>
            <li>
                <a href="#"><img src="{{cdn_image( contenido['foto']['hash'] ,'small')}}" alt="{{contenido['foto']['alt']}}"></a>
            </li>
            <?php unset($this->notapreview->contenido[$key]) ?>
           <?php  } ?>
    	<?php endforeach;?>
            
        </ul>
		
	</div>

</div>