<?php $i=0; foreach ($this->notapreview->contenido as $contenido): ?>  
         {% if contenido['tipo'] == "photo" %}
            <section class="img-news img-principal">                                           
            <figure class="media full">
            <img src="{{contenido['foto']['data']['data']}}" alt="{{contenido['foto']['alt']}}">
           <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?> <?php if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php endif;?>
      <span> <?php echo @$contenido['credito']; ?> </span>
      </figcaption>
            </figure>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {% break  %}
         {% elseif contenido['tipo'] == "video" %}
            <section class="img-news">
            <div id="swfplayer_open" class="nd_galeriaopen_">   </div>
            <div class="help-media">
            <?php echo @$contenido['video']['descripcion']; ?> <?php if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php endif;?>
            <span> <?php echo @$contenido['credito']; ?> </span>
            </div>
            <script type="text/javascript">setJW7("swfplayer_open", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}','{{contenido['video']['hash']}}');</script>
            </section>
            <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% elseif contenido['tipo'] == "youtube" %}
         <p><section class="img-news">
            <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
            <div class="help-media">
            <?php echo @$contenido['youtube']['descripcion']; ?> <?php if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php endif;?>
            <span> <?php echo @$contenido['credito']; ?> </span>
            </div>
            </section>
         </p>
         <?php if(empty($contenido['youtube']['url_cover'])) : ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg");</script>
         <?php else: ?>
         <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "{{contenido['youtube']['url_cover']}}");</script>
         <?php endif;?> 
         <?php unset($this->notapreview->contenido[$i]) ?>
         {%break%}
         {% endif  %}
         <?php $i++?>
<?php endforeach;?>