<section class="img-news"><div id="swfplayer_{{key}}" class="nd_galeriaopen_">
</div>
<div class="help-media">
      <?php echo @$contenido['audio']['descripcion']; ?> <?php if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php endif;?>
      <?php if(!empty(@$contenido['credito'])): ?>
      | <strong>Fotógrafo:</strong>  : {{contenido['credito']}}
      <?php endif;?>
</div>
</section>
<script type="text/javascript">setJW7("swfplayer_{{key}}", "{{contenido['audio']['url']}}", "{{contenido['audio']['url_cover']}}", undefined, undefined, "<?php echo @$this->model->preroll; ?>");</script>
