 <?php if( !empty(@\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->_id) ): ?>
 <link type="text/css" rel="stylesheet" href="{{host}}/html/mam/css/mam.css?v={{eversion}}">
    <!-- MaM -->
    <section class="rpp-mam-xyz">
        <header class="rpp-mam-xyz--header">
            <h5 class="rpp-mam-xyz--title"><?php echo \Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->titulo ?> </h5>
        </header>

        <?php if(@\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->tipo->id == 1):?> 
        <section class="rpp-mam-xyz--team">
            <div class="rpp-mam-xyz--state">
                <div class="rpp-mam-xyz--state-envivo">
                    En vivo
                </div>
            </div>
            <div class="rpp-mam-xyz--table">
                <div class="rpp-mam-xyz--table-row">
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--team-math">
                        <img class="rpp-mam-xyz--team-shield1" width="50px" height="50px" src="http://eventos.old.rpp-noticias.io/services/datafactory/escudos/<?php echo \Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->local->id ?>.png" alt="Escudo" />
                    </div>
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--cell-point"><?php echo @\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->local->goles ?>-<?php echo @\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->visitante->goles ?></div>
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--team-math">
                        <img class="rpp-mam-xyz--team-shield2" width="50px" height="50px" src="http://eventos.old.rpp-noticias.io/services/datafactory/escudos/<?php echo \Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->visitante->id ?>.png" alt="Escudo" />
                    </div>
                </div>
            </div>
            <div class="rpp-mam-xyz--over">
                <div class="rpp-mam-xyz--over-team-match-1"><?php echo \Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->local->nombre_equipo ?></div>
                <div class="rpp-mam-xyz--over-team-match-2"><?php echo \Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->visitante->nombre_equipo ?></div>
            </div>
        </section>
        <section class="rpp-mam-xyz--goals">
            <div class="rpp-mam-xyz--goals-inner">
                <ul class="rpp-mam-xyz--goals-1">
                <?php if(is_array(@\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->local->gol_jugadores)):?>
                <?php foreach (\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->local->gol_jugadores as  $gol): ?>
                    <li><strong><?php echo $gol->tiempo ?> <?php echo $gol->minuto ?>'</strong><?php echo $gol->jugador ?></li>
                <?php endforeach ?>
                <?php endif;?>
                </ul>
                <ul class="rpp-mam-xyz--goals-2">
                <?php if(is_array(@\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->visitante->gol_jugadores)):?>
                <?php foreach (\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->match->visitante->gol_jugadores as  $gol): ?>
                    <li><strong><?php echo $gol->tiempo ?> <?php echo $gol->minuto ?>'</strong><?php echo $gol->jugador ?></li>
                <?php endforeach ?>
                <?php endif;?>
                </ul>
            </div>
        </section>
       <?php else:?>

        <section class="rpp-mam-xyz--team  none">
            <div class="rpp-mam-xyz--state">
                <div class="rpp-mam-xyz--state-envivo">
                    En vivo
                </div>
            </div>
            <div class="rpp-mam-xyz--table">
                <div class="rpp-mam-xyz--table-row">
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--team-math">
                        <img class="rpp-mam-xyz--team-shield1" width="50px" height="50px" src="" alt="Escudo" />
                    </div>
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--cell-point"></div>
                    <div class="rpp-mam-xyz--table-cell rpp-mam-xyz--team-math">
                        <img class="rpp-mam-xyz--team-shield2" width="50px" height="50px" src="" alt="Escudo" />
                    </div>
                </div>
            </div>
            <div class="rpp-mam-xyz--over">
                <div class="rpp-mam-xyz--over-team-match-1"></div>
                <div class="rpp-mam-xyz--over-team-match-2"></div>
            </div>
        </section>
        <section class="rpp-mam-xyz--goals none">
            <div class="rpp-mam-xyz--goals-inner">
                <ul class="rpp-mam-xyz--goals-1">

                </ul>
                <ul class="rpp-mam-xyz--goals-2">

                </ul>
            </div>
        </section>

       <?php endif;?>

        <section class="rpp-mam-xyz--flow">
            <ul class="rpp-mam-xyz--flow-help">
                <li class="rpp-mam-xyz--loading">
                    <img src="{{host}}/html/mam/img/spin-loader.svg" width="25" height="25" alt="Spin" /> actualizando
                </li>
            </ul>
               <ul class="rpp-mam-xyz--flow-inside-recursive">
               </ul>
               
<ul class="rpp-mam-xyz--flow-inside">   
   <?php if(!empty(\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->incidencias)):?>   
    <?php foreach (\Rpp\Services\Get\Mam::incidencias($contenido['mam']['id'])->incidencias as  $incidencia ): ?>
                <li class="rpp-mam-xyz--inside">
                    <div class="rpp-mam-xyz--text">
                        <p>
                         {{incidencia.texto}}
                        </p>
                    </div>
        <?php if(!empty($incidencia->foto)):?>
                    <figure class="rpp-mam-xyz--media">
                        <img src="{{incidencia.foto}}" alt="{{incidencia.texto}}" />
                    </figure>
        <?php endif;?>
        <?php if(!empty($incidencia->embed)):?>
                    <div class="rpp-mam-xyz--media">
                      {{incidencia.embed}}
                    </div>
        <?php endif;?>

                    <div class="rpp-mam-xyz--social">
                        <span class="rpp-mam-xyz--social-text">Compartir</span>
                        <a href="#" target="_blank" title="Twitter"><i onclick="rppMaM.$.openSocial('facebook', this)" class="rpp-mam-xyz-icon rpp-mam-xyz-icon-facebook" ></i></a>
                        <a href="#" target="_blank" title="Facebook"><i onclick="rppMaM.$.openSocial('twitter', this)" class="rpp-mam-xyz-icon rpp-mam-xyz-icon-twitter" ></i></a>
                    </div>
                    <div class="rpp-mam-xyz--time">
                       <?php if($incidencia->tiempo==2):?>
                       <?php $tiempo=$incidencia->hora+45; ?>
                       <?php else: ?>
                       <?php $tiempo=$incidencia->hora; ?>
                       <?php endif;?>
                        <time class="rpp-mam-xyz--time-padding">{{tiempo}}</time>
                        <div class="rpp-mam-xyz--icon">
                            <i class="rpp-mam-xyz-icon rpp-mam-xyz-icon-<?php echo @$incidencia->icono;?>"></i>
                        </div>
                    </div>
                </li>
    <?php endforeach ?>
<?php endif;?>
</ul>
        </section>
    </section>
    <script src="{{host}}/html/mam/js/mam.min.js"></script>
    <script>
        //MaM
        rppMaM.recursive({
            status: true,
            urlApi: '<?php echo \Rpp\Services\Get\UrlMedia::get_conf()->endpoint->raiz ?>mam/{{contenido['mam']['id']}}.json',
            social: { facebook: { app_id: 185239485185, via: 'rppnoticias' }, twitter : { via: 'rppdeportes' }},
            classCss : '.rpp-mam-xyz',
            fbClose : 'http://rpp.pe/html/mam/timemachine_share.html',
            timeSeconds : 10,
            pathCSS : false ,
            imageShare : '{{ cdn_image(gNode(model.nid).imagen_portada['hash'],'medium') }}',
            urlShield : '<?php echo \Rpp\Services\Get\UrlMedia::get_conf()->endpoint->raiz ?>mam/escudos/'
        });
    </script>
    <!-- /MaM -->
<?php endif;?>
