<?php if(\Rpp\Services\Get\Content::node($this->model->nid)->tipo != 'brandcontent'):?>
 <div class="pub-wrap group">
    <div class="pub col-2 pub-300">
        <script type="text/javascript"><!--
google_ad_client = "ca-pub-4798561530103428";
/* RPP-Caja-300x250-1-Notas */
google_ad_slot = "4191125917";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
    </div>
    <!-- pub-300 -->

    <div class="pub col-2 pub-300">
        <script type="text/javascript"><!--
google_ad_client = "ca-pub-4798561530103428";
/* RPP-Caja-300x250-2-Notas */
google_ad_slot = "5667833797";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
    </div>
    <!-- pub-300    -->

</div>
<?php endif;?>




