<?php $position = 1 ;foreach (\Rpp\Services\Get\Flow::seccion($slug,50) as $item) : ?>
<?php
  $gene_img['type']='html';
  $gene_img['content'] ='<img src="'.\Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Content::node($item->_id)->imagen_portada['hash'], 'medium') .'" alt=" '.\Rpp\Services\Get\Content::node($item->_id)->imagen_portada['alt'].' ">';
$jsongene_img=json_encode($gene_img, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE);
  ?>
<article class="card">
  <figure class="holder"><a href="{{nUrl(item._id)}}" data-x='<?=$jsongene_img;?>' class="cover x-fit-lazy">
      </a>
      {{ partial('partials/portada/flujo/box/social', [ 'nid' : item._id ]) }}

  </figure>
  <div class="cont">
    <div class="top-info">
      <div class="cat"><a href="{{host}}<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($item->_id)->categoria['slug']) ;  ?>"><?php echo \Rpp\Services\Get\Content::node($item->_id)->categoria['nombre']?></a></div>
      <?php $fecha_actual = time();?>
      <?php $fecha_publicacion  = \Rpp\Services\Get\Content::node($item->_id)->fecha_publicacion  ?>
      <?php if($fecha_publicacion > $fecha_actual) $fecha_publicacion = $fecha_actual; ?>
      <time class="time"><?php echo utf8_encode(ucfirst(strftime('%e.%b.%y',  $fecha_publicacion )) );?></time>
    </div>
    <h2><a href="{{nUrl(item._id)}}{{TrackUrl(position)}}" >{{getNode(item._id).titulo_corto}}</a></h2>
    <div class="author"><img src="{{getPart(item._id,'autor')['foto']}}" alt="{{getPart(item._id,'autor')['nombre']}}">
      <div class="data">Escrito por:<a href="{{host}}<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($item->_id)->categoria['slug']) ;  ?>">{{getPart(item._id,'autor')['nombre']}}</a></div>
    </div>
    <p>{{getNode(item._id).bajada}}</p>
  </div>
</article>


    <?php $position++;?>
<?php endforeach;?>
