<div data-x='{"breakpoints":"480x1x10,768x2x10"}' class="row x-columns-fit">
  <?php $e=1;$interval=5;$adsprint=1;$ads=1;?>
  <?php foreach (\Rpp\Services\Get\Flow::home(50) as $item) : ?>
    {{partial('partials/portada/flujo/box/'~getNode(item._id).tipo,['nid':item._id, 'position': e, 'size' : 'medium'])}}
    <?php if($adsprint%$interval==0): ?>
    <?php $ads_type = 'sync_';?>
    <?php if($ads > 3) $ads_type = ''; ?>
   	{{partial('partials/ads/' ~ ads_type ~ 'interna', [ 'position': ads ])}}
   	<?php $interval=10;$adsprint=1;$ads++;?>
	<?php endif;?>
    <?php $adsprint++;$e++;?>
  <?php endforeach;?>
</div>