<?php $e=1 ; $ads = 1;?>
<?php foreach (\Rpp\Services\Get\Flow::seccion($slug,50,0) as $item) : ?>
    {{partial('partials/portada/flujo/box/normal',['nid':item._id , 'position' : e, 'lazymt': 'x-lazy' ])}}
    <?php if( $e%10 == 0 ): ?>
        <?php $ads_type = 'sync_';?>
        <?php if($ads > 3) $ads_type = ''; ?>
    	{{partial( 'partials/ads/' ~ ads_type ~ 'interna_doble', [ 'position': ads ] )}}
        <?php	$ads = $ads+2; ?>
    <?php endif;?>
<?php $e++;?>
<?php endforeach;?>