<?php $e=1; $ads = 1;?>
<?php if(count(@$this->model->tag_info->tags_in)>1):?>
<?php foreach (\Rpp\Services\Get\LFlow::tagsrelated($this->model->slug, $this->model->tag_info->tags_in ,50) as $item) : ?>
    <?php if(empty(\Rpp\Services\Get\Content::part($item->_id,'_id' ))) continue; ?>
    {{partial('partials/portada/flujo/box/resultado',['nid':item._id  , 'position': e, 'lazymt': 'x-lazy'])}}
    <?php if( $e%5 == 0 ): ?>
        <?php $ads_type = 'sync_';?>
        <?php if($ads > 3) $ads_type = ''; ?>
        {{partial( 'partials/ads/' ~ ads_type ~ 'interna_doble', [ 'position': ads , 'lazymt': 'x-lazy'] )}}
    <?php   $ads = $ads+2; ?>
    <?php endif;?>
<?php $e++;?>    
<?php endforeach;?> 

<?php else:?>

<?php foreach (\Rpp\Services\Get\LFlow::tag($this->model->slug,50) as $item) : ?>
    {{partial('partials/portada/flujo/box/resultado',['nid':item._id  , 'position': e, 'lazymt': 'x-lazy'])}}
    <?php if( $e%5 == 0 ): ?>
        <?php $ads_type = 'sync_';?>
        <?php if($ads > 3) $ads_type = ''; ?>
        {{partial( 'partials/ads/' ~ ads_type ~ 'interna_doble' , [ 'position': ads , 'lazymt': 'x-lazy' ] )}}
    <?php   $ads = $ads+2; ?>
    <?php endif;?>
<?php $e++;?>    
<?php endforeach;?>

<?php endif;?>