<?php if(count(@$this->model->tag_info->tags_in)>1):?>
<?php $tag_list = \Rpp\Services\Get\Flow::tagsrelated($this->model->slug, $this->model->tag_info->tags_in ,100); ?>
<?php else:?>
<?php $tag_list = \Rpp\Services\Get\Flow::tag($this->model->slug,100) ;?> 
<?php endif;?>

<?php $imp=0;$e=1;$ads =1 ; $left = 1 ; $ads_left = array() ;?>
<div data-x='{"breakpoints":"480x1x10,768x2x10"}' class="row x-columns-fit">
  <?php foreach ($tag_list as $offset =>  $item) : ?>
    <?php if($e%5==0): ?>
      <?php $ads_type = 'sync_';?>
      <?php if($ads > 4) $ads_type = ''; ?>
      {{partial('partials/ads/' ~ ads_type ~ 'interna', [ 'position': ads ])}}
      <?php $ads++; ?>
    <?php endif;?>
    <?php if(empty(\Rpp\Services\Get\Content::part($item->_id,'_id' ))) continue; ?>
    {{partial('partials/portada/flujo/box/normal',['nid':item._id  , 'position': e])}}
    <?php $e++;?>
  <?php endforeach;?>
</div>
