<!--Head-->
<head>

</head>
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}" style="margin: 0px !important; overflow-y: hidden;">
    {% if(model.player.estado === 0) %}
    <div class="media-player" >
        <img src="{{ehost}}/images/nodisponible.jpg" alt="Transmisión no disponible" title="Transmisión no disponible" style="width: 100%; min-width: 100%; height: 100% !important" >
    </div>
    {% else %}
    <div class="media-player" >
        <div id="{{model.slug}}"></div>
        <script type="text/javascript">
    var file = "{{model.file}}";
    var playlist = '[{% for k,media in model.player.media %}{"file" : "{{media}}"}{% if k < (model.player.media|length - 1) %},{% endif %}{% endfor %}]';
    var rtag = "{{model.preroll}}";
    
    {% if(model.cover !== "") %}
    var cover = "{{ehost}}/{{model.cover}}";
    {% else %}
    var cover = "";
    {% endif %}
    setJW7("{{model.slug}}", file, cover, playlist, '{{model.tipop}}', rtag);
        </script>
    </div>
    {% endif %}
    {{ partial('partials/footer/comscore') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
