<div class="col-primary main">
      <div class="box-mod pt10">
        <h3>En Vivo</h3>
        <div class="story-top">
          <div class="label">Estás viendo:</div>
        </div>
        <header class="story-header">
          <h1>AMPLIACIÓN DE NOTICIAS</h1>
          <p class="sumary">con Raúl Vargas, Patricia Del Río y Ricardo Gómez</p>
          <!-- audio-->
          <div itemprop="audio" itemscope itemtype="http://schema.org/AudioObject" class="media">
            <meta itemprop="encodingFormat" content="mp3">
           
            <?php $gene_img['playlist']='['; ?>
            <?php if(is_array($this->model->player->media)):?>
            <?php foreach ($this->model->player->media as $k => $media) {
               $gene_img['playlist'].='{"file" : "'.$media.'"}';
               if(count($this->model->player->media) > ($k+1)){  $gene_img['playlist'].=','; }
            } ?>
            <?php endif;?>
            <?php $gene_img['playlist'].=']'; ?>
            <?php 
                $gene_img['type']=$tipoenvi;
                $gene_img['video_source'] =$this->model->file; 
                $gene_img['video_img'] =$ehost."/images/envivo.jpg"; 
               
                $gene_img['hash'] ='undefined';
                $gene_img['rtag'] =$this->model->preroll;
                $gene_img['section'] = @$this->model->epl_sec;
                $gene_img['vtemas'] = @$this->model->epl_kvs;                
                $jsongene_img=json_encode($gene_img);
            ?>


            <figure>
                <div class="cover cover-media">
                    <a href="#<?=$tipoenvi?>" data-x='<?=$jsongene_img;?>' class="x-media big"><img src="{{ehost}}/images/envivo.jpg" alt="envivo">
                        <?php if($tipoenvi=='audio'){ ?>
                        <span class="icon-audio"></span>
                        <?php }else{ ?>
                        <span class="icon-video"></span>
                        <?php } ?>
                    </a>
                </div>
              <figcaption itemprop="description">Transmisión de {{model.tipon}} en vivo</figcaption>
            </figure>
          </div>
        </header>
      </div>
      <div class="comments box-mod">
        <div class="box-header">
          <div class="title">¿Qué opinas?<a name="section-comment"></a></div>
        </div>
        <div data-href="{{host}}/{{model.slug}}" data-numposts="5" data-width="100%" class="fb-comments"></div>
        <div id="fb-root"></div>
        <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=1065644730116597";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
      </div>
    </div>