<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
{{ partial('partials/head/indexportada') }}
<body data-bg="{{model.epl_kvs}}" data-x="slide, lazy, media, sticky" class="radio-live" >
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
    <div id="wrap">
        <!--Header-->
        {{ partial('partials/header/index') }}
        <div id="content" role="main">
        <div class="grid pad">
          <div class="story">

                {{ partial('envivo/index',['tipoenvi': 'audio']) }}
                <!-- feat-content -->

                <aside class="col-secondary sidebar x-sticky"> 
                  <div data-x='{"fixto":".col-primary"}' class="x-column-fix">         
                    {{ partial('partials/sidebar/cabinaenvivo') }}
                    {{ partial('partials/ads/right') }}
                    {{ partial('partials/ads/right1') }}
                    <?php $sdb = 'mas-leidas';?>
                    <?php $nombre = 'Las noticias más leídas';?>
                    <?php $cantidad = 10;?>
                    <?php $tipo ='solo_titular';?>
                    <?php $script =  '';  ?>
                     {{partial('partials/portada/sidebar/' ~ tipo ~ '/index_' ~ sdb ,['tag':  sdb , 'nombre': nombre , 'cantidad': cantidad ,'slug' : 'home' , 'script' : script ]) }}
                    </div>
                </aside>

            </div>
            <!-- .featured -->

            {{ partial('partials/ads/middle2') }}
            <!-- pub-980 -->
            </div>
        </div>
        <!--Footer-->

        {{ partial('partials/footer/index') }}
        {{ partial('partials/footer/scripts') }}
        {{ partial('partials/footer/tracking') }}
    </div>
</body>
