<?php foreach (\Rpp\Services\Get\Flow::tag($tag) as $e => $item):?> 
  <?php if(@\Rpp\Services\Get\Content::node($item->_id)->tipo == 'video'):?>
<div class="box-mod box-row brand-{{tag}} no-ellipsis">
  <?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
  <?php if((int)$imgcb==1){ ?>
  <div style="background:transparent url('<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn_raiz(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']) ?>') left top no-repeat;" class="box-header back-image">
    <h3 class="title"><a href="{{host}}/tema-{{ tag }}">{{nombre}}</a></h3>
  </div>
  <?php }else{ ?>
  <div class="box-header">
    <h3 class="title"><a href="{{host}}/tema-{{ tag }}">{{nombre}}</a></h3>
  </div>
  <?php } ?>



<?php foreach ( \Rpp\Services\Get\Content::part($item->_id,'contenido') as $contenido):?>
     <?php if($contenido['tipo'] == "video"): ?>
      <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] = \Rpp\Services\Get\UrlMedia::replace_cdn_raiz($contenido['video']['url']);
      $gene_img['video_img'] = \Rpp\Services\Get\UrlMedia::replace_cdn_raiz($contenido['video']['url_cover']);
      if(!isset($contenido['video']['playlist'])) $contenido['video']['playlist']='[]'; 
      else $contenido['video']['playlist'] = \Rpp\Services\Get\UrlMedia::replace_cdn($contenido['video']['playlist'],'media');
      $gene_img['playlist'] =@json_encode($contenido['video']['playlist']); 
      $gene_img['hash'] =$contenido['video']['hash'];
      $gene_img['rtag'] ='';
      $gene_img['section'] = @$this->model->epl_sec;  
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
          <article class="card">
              <figure class="holder">
                  <div class="cover cover-media">
                      <a href="#video" data-x='<?=$jsongene_img;?>' class="x-media">
                          <img src="<?=$gene_img['video_img'];?>" >
                            {{ partial('partials/portada/grilla/block/icon/' ~ getNode(item._id).tipo ) }}
                      </a>
                  </div>
                </figure>
              <div class="cont">
                <h3><a href="{{nUrl(item._id)}}{{TrackUrl(1)}}">{{getNode(item._id).titulo}}</a></h3>
              </div>
          </article>
   <?php break;?>
   <?php elseif ($contenido['tipo'] == "youtube") :?>
       <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] ="https://www.youtube.com/watch?v=".$contenido['youtube']['id'];
      if(empty($contenido['youtube']['url_cover'])){
        $gene_img['video_img'] =  "http://img.youtube.com/vi/".$contenido['youtube']['id']."/0.jpg"; 
      } else{
        $gene_img['video_img'] = \Rpp\Services\Get\UrlMedia::replace_cdn_raiz($contenido['youtube']['url_cover']) ; 
      }
      
      $gene_img['playlist'] ='undefined'; 
      $gene_img['hash'] ='undefined';
      $gene_img['rtag'] ='';
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
            <article class="card">
                <figure class="holder">
                    <div class="cover cover-media">
                        <a href="#escuchar" data-x='<?=$jsongene_img;?>' class="x-media">
                            <img src="<?=$gene_img['video_img'];?>" >{{ partial('partials/portada/grilla/block/icon/' ~ getNode(item._id).tipo ) }}
                        </a>
                    </div>
                </figure>
                <div class="cont">
                <div class="top-info">
                  {{ partial('partials/portada/flujo/box/cat', [ 'nid' : item._id ]) }}
                </div>
                  <h3><a href="{{nUrl(item._id)}}{{TrackUrl(1)}}">{{getNode(item._id).titulo}}</a></h3>
                </div>
          </article>
     <?php  break;endif;?>
     <?php endforeach ;?>


</div>
   <?php break;endif;?>
<?php endforeach;?> 

