
<?php \Rpp\Services\Get\UrlTrack::$ns_source = 'rpp'; ?>
<footer>

    <div class="footer-brands">
        <div class="wrapper group">
            <p>Visita también:</p>
            <ul class="group">
                <li><a class="radio-capital" href="http://www.capital.com.pe/{{TrackUrl()}}" target="_blank"
                       title="Radio Capital">Radio Capital</a></li>
                <li><a class="radio-studio92" href="http://www.studio92.com/{{TrackUrl()}}" target="_blank"
                       title="Radio Studio 92">Radio Studio 92</a></li>
                <li><a class="radio-oxigeno" href="http://www.oxigeno.com.pe/{{TrackUrl()}}" target="_blank"
                       title="Radio Oxigeno">Radio Oxigeno</a></li>
                <li><a class="radio-felicidad" href="http://www.felicidad.com.pe/{{TrackUrl()}}" target="_blank"
                       title="Radio Felicidad">Radio Felicidad</a></li>
                <li><a class="radio-corazon" href="http://www.radiocorazon.com.pe/{{TrackUrl()}}" target="_blank"
                       title="Radio Corazón 94.3">Radio Corazón 94.3</a></li>
                <li><a class="radio-lazona" href="http://www.lazona.com.pe/{{TrackUrl()}}" target="_blank"
                       title="Radio La Zona">Radio La Zona</a></li>
                <li><a class="quebuenaoferta"
                       href="http://www.la10.pe/{{TrackUrl()}}"
                       target="_blank" title="La10.pe">La10.pe</a></li>
            </ul>
        </div>
    </div>
    <!-- .footer-brands -->

    <div class="footer-corp">
        <div class="wrapper group">
            <a class="grupo-rpp" href="/{{TrackUrl()}}" target="_blank" title="Grupo RPP">Grupo
                RPP</a>

            <div class="footer-links">
                <ul class="group">
                    <li><a href="http://contactenos.gruporpp.com.pe/" target="_blank">Contáctenos</a></li>
                    <li><a href="/legal">Aviso legal</a></li>
                    <li><a href="mailto:publicidadweb@gruporpp.com.pe"  >Anuncie aquí</a></li>
                    <li><a href="http://snrtv.org.pe/codigo.php"  target="_blank">Código de ética</a></li>
                    <li><a href="http://snrtv.org.pe/solucion.php"  target="_blank">Solución de quejas SNRTV</a></li>
                    <li><a href="javascript:;">Mapa del sitio</a></li>
                </ul>
                <ul class="group">
                    <li>Auditado por: <a  target="_blank" href="http://www.comscore.com/esl/">Comscore</a></li>
                    <li>Asociado a: <a  target="_blank" href="http://www.iabperu.com/">IAB Perú</a></li>
                    <li>Licenciado por: <a  target="_blank" href="http://www.apdayc.org.pe/">APDAYC</a></li>
                </ul>
            </div>
            <a href="http://lucumalabs.com/" rel="nofollow" target="_blank" class="lucuma-labs" href="javascript:;" title="Award winning UX &amp; Design Web Agency">
                Diseñado por: <span>Lúcuma Labs</span>
            </a> 
        </div>
    </div>
    <!-- .footer-corp -->

</footer>

