<script src="{{ehost}}/scripts/jquery.flexslider.js?v={{eversion}}"></script>
<script src="{{ehost}}/scripts/social.js?v={{eversion}}"></script>
<script src="{{ehost}}/scripts/main.js?v={{eversion}}"></script>
<script src="{{ehost}}/scripts/lazy.min.js?v={{eversion}}"></script>
<script src="{{ehost}}/scripts/hammer.min.js" id="master"></script>
<script src="{{ehost}}/scripts/rpp.js" id="master"></script>
{{ partial('partials/footer/comscore') }}

