<div class="feat-content">
    <div class="feat-block group">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>
     {{ partial('partials/portada/grilla/block/hentry', [ 'item' : item ]) }}
     <?php $unset = 'unset_'.$namespace ;?>
     <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
     <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>
     <?php break;endforeach;?>
    </div>


    <div class="feat-block group">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?> 
        <?php if($position>=3) break; ?>     
        <?php if(empty(@$item['nid'])) continue;?>    
         <div class="col-3">            
          {{ partial('partials/portada/grilla/block/hentry_group', [ 'item' : item , 'class' : 'third' , 'img_size' : 'small']) }}
         </div>
         <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
         <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>          
        <?php endforeach;?> 


        <div class="col-3">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?>            
          <?php if($position>=5) break; ?>     
          <?php if(empty(@$item['nid'])) continue;?>
          {{ partial('partials/portada/grilla/block/hentry_title', [ 'item' : item , 'class' : 'third']) }}
          <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>        
        <?php endforeach;?> 

        </div>

    </div><!-- .feat-block -->

</div>
<aside class="feat-sidebar">
 {{ partial('partials/portada/grilla/block/ads/' ~ ads  ) }}

 {{ partial('partials/portada/grilla/block/tag_portada') }}
</aside>