<section id="featured" class=" group">
    <div class="feat-fin">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>   
     {{ partial('partials/portada/grilla/block/hentry_full', [ 'item' : item ]) }}
     <?php $unset = 'unset_'.$namespace ;?>
     <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>
    <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
    <?php break;endforeach;?>
    </div>
</section>
<!-- .featured -->


    

    