<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}
<script type="text/javascript">
  user_id = '{{model.user_ga}}';
</script>
<body data-x="slide, columns-fit, lazy, sticky, media, ago, widget" class="home" data-bg="{{model.epl_kvs}}" >
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore_refresh') }}
<div  id="wrap">
    <!--Header-->  
    {{ partial('partials/header/index') }}
    <div id="content" role="main">
          {{ partial('partials/ads/top') }}
        <div class="grid pad">
          
          {{ partial('partials/portada/bloque/tag/campana_cabecera' , ['slug':'home'] ) }}

          {{ partial('index/body_open' ~ model.no_view_cache_open ) }}
          <div class="row">           
            {{ partial('index/body_central' ~ model.no_view_cache_central ) }}
            {{ partial('partials/portada/bloque/sidebar_homecol_secondary') }}
          </div>
          {{ partial('index/body_close' ~ model.no_view_cache_close ) }}
        </div>
      </div>


    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    {{ partial('partials/footer/scripts') }}
    <script type="text/javascript" src="{{ehost}}/elecciones-peru-2016/debate.js?v={{eversion}}"></script>
    <script src="{{ehost}}/elecciones-peru-2016/js/highcharts.js?v={{eversion}}"></script>
    <script src="{{ehost}}/elecciones-peru-2016/js/srcijp.js?v={{eversion}}"></script>
    {{ partial('partials/resultados_electorales/presidenciales/script') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>