<section class="contenedor contpresidenjps">
		<header class="cabecera">
			<h1>RESULTADOS PRESIDENCIALES 2016</h1>
		</header>
		<section class="contenido">
			<section id="detalle">

				<aside class="referencia">
					<div style="width: 49%; float: left; margin-right: 2%;">
						<select id="fuentes-lista"></select>
					</div>
					<div style="width: 49%; float: left;">
						<select id="departamentos-lista">
						</select>
					</div>
				</aside>
				
				<section class="menu">
					<div id="menu-lista" class="menu-lista"></div>
					<aside class="escrutado"></aside>
					<aside id="mesas-escrutadas">0</aside>
				</section>
			</section>
			<section id="mapa">
				<div class="col-share">
					<div class="social-share" id="share-options">
				    <div class="inside">
				      <ul id="share-options">
				        <li class="fb-share">
				            <!-- <span class="count">153</span> -->
				            <a href="https://www.facebook.com/sharer/sharer.php?u=http://rpp.pe/elecciones-peru-2016/resultados-presidenciales&amp;t=Resultados Elecciones 2016: revisa aquí el flash electoral de Presidentes" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
				          <span class="icon-facebook"></span>
				          </a>
				        </li>
				        <li class="wa-share">
				          <a href="whatsapp://send?text=Resultados Elecciones 2016: revisa aquí el flash electoral de Presidentes http://rpp.pe/elecciones-peru-2016/resultados-presidenciales">
				          <span class="icon-whatsapp"></span>
				          </a>
				        </li>
				        <li class="tw-share">
				          <a href="https://twitter.com/intent/tweet?original_referer=http://rpp.pe/elecciones-peru-2016/resultados-presidenciales&amp;text=Resultados Elecciones 2016: revisa aquí el flash electoral de Presidentes&amp;url=http://rpp.pe/elecciones-peru-2016/resultados-presidenciales&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
				          <span class="icon-twitter"></span>
				          </a>
				        </li>
				        <li class="gp-share">
				          <a href="https://plus.google.com/share?url=http://rpp.pe/elecciones-peru-2016/resultados-presidenciales" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
				          <span class="icon-google-plus"></span>
				          </a>
				        </li>
				        <li class="in-share">
				          <a href="https://www.linkedin.com/shareArticle?url=http://rpp.pe/elecciones-peru-2016/resultados-presidenciales&amp;title=Resultados Elecciones 2016: revisa aquí el flash electoral de Presidentes&amp;summary=Los resultados de las Elecciones Presidenciales 2016 serán anticipados con los flash electorales." onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
				          <span class="icon-linkedin"></span>
				          </a>
				        </li>
				      </ul>
				    </div>
				    <div class="on-share">
				      <a href="#compartir" onclick="fn(this, event, {&quot;method&quot;:&quot;toggleClass&quot;, &quot;to&quot;: &quot;#share-options&quot;})">
				        <span class="icon-forward-share"></span>
				      </a>
				    </div>
				  </div>
				</div>
				<section>
					<!--div style="width: 80%; border: 5px solid #B63030; margin: 20px auto; position: relative;">
						<div title="click me!!!" style="width: 10px;
								     height: 10px;
								     -moz-border-radius: 50%;
								     -webkit-border-radius: 50%;
								     border-radius: 50%;
								     background: #B63030; position: absolute; left: 30%; top: -20px; cursor: pointer;">
						</div>
					</div-->
				</section>
				<div id="mapa-peru"></div>
			</section>

		</section>
	</section>
