<div class="pin-container" >
    <div class="pin-wrapper" >
        <div class="sidebar-panel content-automatic more-read" >
        <?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
            <h2 data-size-title="{{imgcb*1}}" class="panel-title module-automatic" style="background:transparent url('<?php echo @\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51'] ?>') left top no-repeat;"><a href="{{host}}/tema-{{ tag }}"> </a></h2>
            <h2 data-size-title="{{!imgcb*1}}" class="panel-title module-automatic-title">{{nombre}}</h2>
            <ol>
<?php $cantle=1; foreach (\Rpp\Services\Get\Flow::tag($tag,$cantidad) as $e => $item):?> 
               <li>
                    <h3>
                        <a class="group" href="{{nUrl(item._id)}}{{TrackUrl(1)}}">
                            <span class="order"><?=$cantle;?></span>
                            <span>{{getNode(item._id).titulo}}</span>
                        </a>
                    </h3>
                </li>
<?php $cantle++; endforeach;?>
            </ol>
        </div>
    </div>
    <!-- .more-read -->
</div>


