<div class="wrap group">
  <div class="content group">
                

        <header>
         <p class="cat cat-autor-title" data-size-ancla="0">

        <span class="autor-title-inside">Blog</span>
          <a href="#">{{notapreview.categoria['nombre']}}</a>

          {{ partial('partials/nota/header/pubtime',['fecha_publicacion': notapreview.fecha_publicacion ])}}
        </p>
        {{ partial('partials/nota/header/titulo',['titulo': notapreview.titulo   ]) }}
         {{ partial('partials/nota/header/bajada',['bajada': notapreview.bajada ]) }} 
        </header>


<section class="autor-nota autor-content">
<?php $autor = \Rpp\Services\Get\User::get(@$this->notapreview->autor['slug']); ?>

 <?php if(@$autor->foto_blog['w110']):?>
   <figure class="autor-figure">
       <img src="{{ autor.foto_blog['w110'] }}" alt="{{autor.nombre}}">
   </figure>
 <?php endif;?>
  
   <div class="autor-description">
       <h2><?php echo @$autor['nombre']?></h2>
       <button
       onclick="if(this.nextElementSibling.className==='autor-open-bio'){this.className='autor-btn-more';this.nextElementSibling.className='';}else{this.className='autor-btn-more autor-btn-minor';this.nextElementSibling.className='autor-open-bio';}"
       class="autor-btn-more autor-btn-minor"
       type="button">BIO</button>
       <p class="autor-open-bio"><?php echo @$autor->autor['biografia'] ;?></p>
       <ul class="autor-social-icons">
   <?php if(!empty($autor->autor['facebook'])):?>
    <li class="autor-fb"><a target="_blank" href="{{autor.autor['facebook']}}" title="Facebook"><i class="icon-1"></i></a></li>
   <?php endif;?>
   <?php if(!empty($autor->autor['twitter'])):?>
    <li class="autor-tw"><a target="_blank" href="{{autor.autor['twitter']}}" title="Twitter"><i class="icon-5"></i></a></li>
   <?php endif;?>
         <li class="autor-rss"><a target="_blank" href="{{host}}" title="RSS"><i class="icon-rss"></i></a></li>
       </ul>
   </div>
</section>


                <div class="group">
                    {{ partial('partials/nota/detalle/social') }}
                    {{ partial('partials/nota/detalle/socialmobile') }}
                    <div class="cont ajust_win">
                        {{ partial('partials/nota/detalle/open/' ~ model.package ) }}
                        {{ partial('partials/nota/detalle/block/firma/'~model.package) }} 
                        {{ partial('partials/nota/detalle/content/'~model.package) }}                            
                        <!-- .social-share -->                            
                        {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
                    </div>
                    <!-- .cont -->
                </div>

 <?php if(!(@$this->notapreview->comentariosfb === false) ) :?>                
                <!-- .entry-content -->
<div class="news-comments" id="ancla-comments">
    <h2 class="panel-title">¿Qué opinas?</h2>
    <div id="fbCommentPage" class="fb-comments" data-href="{{host}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
</div>
                <!-- .comments -->
<?php endif;?>

            </div>               
    <!-- .content -->
    {{ partial('partials/nota/sidebar/index') }} 
    <!-- .sidebar -->
</div>