<div class="wrap-galeria">
    <div class="galeria-full">
   {{ partial('partials/nota/header/index' ~ model.package) }}
    <div class="galeria">
      <div class="slide state" 
              data-params='{
                   "baseurl": "{{host}}"
                            }'
              data-vars='{
                   "comscore" : {
                                  "site" : "rpp",
                                  "name" : "portada.preview.paginaprincipal"
                                },
                    "posicion" : 1 ,
                    "params" : "",
                    "epl_tag" : [ "Top","Right" ]
                            }'>



        <div class="content">
          <div class="inner">
            <?php $size=0; foreach ($this->notapreview->contenido as $v => $contenido) :?>
         
           <?php if ($contenido['tipo'] == "photo"): ?>
            <div class="item">
              <figure class="hmedia">
                <img class="photo" src="{{ contenido['foto']['url'] }}" alt="{{ contenido['foto']['alt'] }}">
              </figure>
              <figcaption>{{ contenido['foto']['alt'] }}  | <strong>Fuente:</strong> {{ contenido['via'] }}  | <strong>Fotógrafo:</strong> {{ contenido['credito'] }} </figcaption>
            </div>

            <?php unset($this->notapreview->contenido[$v]); $size++; ?>
            <?php endif;?>
            <?php endforeach;?>

          </div>
        </div>

        <div class="arrows">
          <a href="#prev" class="prev">
            <span>
              <i class="icon-13"></i>
            </span>
          </a>
          <a href="#next" class="next">
            <span>
              <i class="icon-14"></i>
            </span>
          </a>
        </div>
        <div class="pagers">
          <div class="text-pager">
            <p>
              Foto <span class="g-num">1</span> de <span class="g-total">{{size}}</span>
            </p>
          </div>
     
          <ul class="pager-circle">
             <?php for ($i=1; $i <= $size ; $i++ ):?>
                <li data-pager="{{i}}" class="page"></li>
             <?php endfor;?>
          </ul>

            <div class="social-state">
                <span>Compartir: </span>
                <a  class="fc" href="javascript: void(0);" onclick="rpp.shareSocial(this, 'facebook', 'http://rpp.pe{{nUrl(model.nid)}}')">
                  <i class="icon-1"></i>
                </a>
                <a class="tw" href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter', '{{host}}/p/{{model.nid}}')">
                  <i class="icon-5"></i>
                </a>
              </div>
          
        </div>


      </div>
    </div> 
  </div>
  <div class="sidebar-galeria">
    {{ partial('partials/ads/right') }}
  </div>
</div>



<div class="wrap group">
    <div class="content group">  
        <div class="entry-content group">
            {{ partial('partials/nota/detalle/social') }}
            {{ partial('partials/nota/detalle/socialmobile') }}
            <div class="cont ajust_win">
                {{ partial('partials/nota/detalle/open/' ~ model.package ) }}
                {{ partial('partials/nota/detalle/block/firma/'~model.package) }} 
                {{ partial('partials/nota/detalle/content/'~model.package) }}                            
                <!-- .social-share -->                            
                {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
            </div>
            <!-- .cont -->
        </div>
        <!-- .entry-content -->
<?php if(!(@$this->notapreview->comentariosfb === false) ) :?>          
<div class="news-comments" id="ancla-comments">
    <h2 class="panel-title">¿Qué opinas?</h2>
    <div id="fbCommentPage" class="fb-comments" data-href="{{host}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
</div>
        <!-- .comments -->
<?php endif;?>

        <!-- .pub-wrap -->
        <!-- .related-news -->

    </div>   
    <!-- .content -->
    <aside class="sidebar">
        {{ partial('partials/nota/sidebar/mas_en_tag' ,[], trackurl ) }}
        {{ partial('partials/ads/perured_nota') }} 
        <!-- pub-300 -->                   
        {{ partial('partials/ads/right1') }}
    </aside>
    <!-- .sidebar -->
</div>