<?php if (@\Rpp\Services\Get\Destacados::portada($slug)->campana_cuerpo['slug']): ?>

    <?php $tipo = @\Rpp\Services\Get\Destacados::portada($slug)->campana_cuerpo['slug'] ?>

    <?php if ($tipo === "podcast"): ?>
        <div class="wrapper">
            <div class="especial" id="podcast" 
                 data-eplsrc="{{model.epl_sec}}"                 
                 data-src="{{host}}/podcast/{{ getGrilla(slug).campana_cuerpo['pcid'] }}"
                 ></div>
        </div>
        <script src="{{ehost}}/scripts/podcast.js"></script>          
    <?php else: ?>
        <div class="cint-banner">
            <div class="wrapper-cint-banner">
                <a href="/tema-{{ getGrilla(slug).campana_cuerpo['slug'] }}" target="_blank"><img  src="{{ehost}}/images/{{ getGrilla(slug).campana_cuerpo['slug'] }}.png" alt="{{ getGrilla(slug).campana_cuerpo['nombre'] }}"></a>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>