<?php if(@\Rpp\Services\Get\Destacados::portada($slug)->medio['slug']):?>
 <?php $cron = \Rpp\Services\Get\Destacados::portada($slug)->medio['slug'];?>
 <?php if( $this->_view->exists('partials/portada/bloque/cronologico/cron_'.$cron) ) :?>
  <?php $destacadas = @\Rpp\Services\Get\Destacados::portada($slug)->medio;  ?>
  {{ partial('partials/portada/bloque/cronologico/cron_' ~ cron , ['destacadas' : destacadas  , 'tag' : getGrilla(slug).medio['slug'] ,'nombre' : getGrilla(slug).medio['nombre'] ]) }}
<?php else :?>
<?php $destacadas = @\Rpp\Services\Get\Destacados::portada($slug)->medio;  ?>
{{ partial('partials/portada/bloque/cronologico/cron_general' , ['destacadas' : destacadas  , 'tag' : getGrilla(slug).medio['slug'] , 'nombre' : getGrilla(slug).medio['nombre'] ]) }}
<?php endif;?>
<?php endif;?>


