 <article class="{{class}} hnews group">
    <figure class="hmedia">
        {{ partial('partials/portada/grilla/block/icon/' ~ getNode(nid).tipo ) }}
        <a {{ partial('partials/portada/grilla/block/url/' ~ getNode(nid).tipo , [ 'nid' : nid ] ) }}>
            <img class="photo lazy" src="{{ehost}}/images/placeholder_rpp.png" data-src="{{ cdn_image(getNode(nid).imagen_portada['hash'], img_size ) }}"
                 alt="{{ getNode(nid).imagen_portada['alt'] }}">
        </a>
        <figcaption class="fn hide">{{ getNode(nid).titulo_corto }}</figcaption>
    </figure>

    <div class="entry-cont ">
        <{{title_h}} class="entry-title"><a {{ partial('partials/portada/grilla/block/url/' ~ getNode(nid).tipo , [ 'nid' : nid ] ) }}>{{ getNode(nid).titulo_corto }}</a></{{title_h}}>
        <footer class="hide">
            <p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
        </footer>
    </div>
</article> 




