 <article>
  <figure>
    <a {{ partial('partials/portada/grilla/block/url/' ~ getNode(nid).tipo , [ 'nid' : nid ] ) }}>
      <img src="{{ cdn_image(getNode(nid).imagen_portada['hash'], 'medium' ) }}" alt="{{ getNode(nid).imagen_portada['alt'] }}" width="280">
    </a>
  </figure>
<?php $size_brand = !empty(\Rpp\Services\Get\Content::part($nid,'imagen_branding'));?>
<?php $size_especial = !empty(\Rpp\Services\Get\Content::part($nid,'imagen_tag'));?>
  <p class="cat cat-cols" data-size-ancla="<?php echo (int)$size_brand + (int)$size_especial ?>">

      <a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($nid)->categoria['slug']) ;?>">{{getNode(nid).categoria['nombre']}}</a>

      <span data-size="<?php echo (int)$size_brand;?>" class="brand-logo-cb"><a href="{{host}}/tema-{{getPart( nid ,'imagen_branding')['slug']}}" ><img src="{{getPart( nid ,'imagen_branding')['url']}}" alt="{{getPart( nid ,'imagen_branding')['nombre']}}"></a></span>

      <span data-size="<?php echo (int)$size_especial;?>" data-size-brand="<?php echo (int)$size_brand;?>" class="brand-especial-cb"><a href="{{host}}/tema-{{getPart( nid ,'imagen_tag')['slug']}}" ><img src="{{getPart( nid ,'imagen_tag')['url']}}" alt="{{getPart( nid ,'imagen_tag')['nombre'] }}"></a></span>
      
  </p>
  <h2>
    <a {{ partial('partials/portada/grilla/block/url/' ~ getNode(nid).tipo , [ 'nid' : nid ] ) }}>{{ getNode(nid).titulo_corto }}</a>
  </h2>
</article>
