<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/votaperu.css?v={{ehost}}">
<body data-bg="{{model.epl_kvs}}" id='tema' class="{{model.tema}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/indextag_' ~ model.tag_personalidad ) }}

    <div class="wrapper body group">

   {{ partial('tag/cabecera_personalizada_' ~ model.tag_personalidad ) }}

    <?php $gnamespace = false;?>
    <div class="content group">

    <?php if(!empty($this->model->tag_info->personalidad)):?>

        {{ partial('partials/portada/bloque/tag/cronologico_1' , ['slug': model.tag_slug_portada ] ) }}
        
        <?php $gnamespace = @\Rpp\Services\Get\Destacados::portada($this->model->tag_slug_portada)->tipo['namespace'] ;?>

        {{ partial('partials/portada/grilla/block/tag/ultimo_' ~  gnamespace ) }}

        
        {{ partial('partials/portada/flujo/tag_full' , [] ) }}

    <?php else:?>
        <?php echo $this->partial('partials/redes/redes', array('slugne'=>'/tema-'.urlencode($this->model->tag_info->nombre))); ?>
        <!-- .redes -->
        {{ partial('partials/portada/flujo/tag2' , [] , trackurl) }}
    <?php endif;?>
                 
            </div>
            <!-- .content -->
            <aside class="sidebar">

<?php if($gnamespace=='tag'):?>
     <div class="ads ads-sidebar-widget">
     <?php echo @$this->model->tag_info->personalidad['twitter']['hashtag'] ?>
     </div>

     {{ partial('partials/portada/bloque/tag/lateral_1' , ['slug': model.tag_slug_portada] ) }}
     {{ partial('partials/ads/right1') }}
     {{ partial('partials/ads/perured') }}
     {{ partial('partials/portada/bloque/tag/lateral_2' , ['slug': model.tag_slug_portada] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_3' , ['slug': model.tag_slug_portada] ) }}
     <!-- #noticia-360 -->
     {{ partial('partials/ads/right2') }}

     {{ partial('partials/portada/bloque/tag/lateral_4' , ['slug': model.tag_slug_portada] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_5' , ['slug': model.tag_slug_portada] ) }}

     {{ partial('partials/ads/right3') }}


     {{ partial('partials/portada/bloque/tag/lateral_6' , ['slug': model.tag_slug_portada] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_7' , ['slug': model.tag_slug_portada] ) }}

     <!-- .dia-sidebar -->
     {{ partial('partials/ads/rightsmall') }}
     
     {{ partial('partials/portada/bloque/tag/lateral_8' , ['slug':  model.tag_slug_portada] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_9' , ['slug':  model.tag_slug_portada] ) }}  
<?php else:?>
        <!-- #rotafono -->  
         {{ partial('partials/ads/right') }}
        {{ partial('partials/sidebar/calientes' , ['slug':'home'] , trackurl ) }}

        {{ partial('partials/ads/right1') }}
        <!-- pub-300 -->
        {{ partial('partials/portada/sidebar/sdb_trafico' , ['tag':''  , 'nombre': ''] ) }}
        <!-- .weather-sidebar -->
         {{ partial('partials/ads/right2') }}
<?php endif;?>

            </aside>
            <!-- .sidebar -->
        </div>

        {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

        {{ partial('partials/portada/bloque/tag/cronologico_2' , ['slug': model.tag_slug_portada ] ) }}
    </div>

    
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
