<?php if($this->model->torneo=='champions'): ?>
<div class="header-tab">
  <ul>
   <li data-id="grupoa" class="item-header-tab <?php if($this->model->fase == $slug ):?>active<?php endif;?>">
    <a href="/resultados/fixture/{{model.torneo}}/fase-de-grupos">Grupos</a>
   </li>
   <li data-id="grupoa" class="item-header-tab <?php if($this->model->fase == $slug ):?>active<?php endif;?>">
    <a href="/resultados/fixture/{{model.torneo}}/octavos-de-final">Octavos</a>
   </li>
   <li data-id="grupoa" class="item-header-tab <?php if($this->model->fase == $slug ):?>active<?php endif;?>">
    <a href="/resultados/fixture/{{model.torneo}}/cuartos-de-final">Cuartos</a>
   </li>
  </ul>
</div>
<?php else:?>
<?php if( count((array)Rpp\Services\Get\Resultados::campeonato($this->model->torneo)->fase) > 1 ) :  ?>
<div class="header-tab">
  <ul>
    <?php foreach (@Rpp\Services\Get\Resultados::campeonato($this->model->torneo)->fase as $slug => $nombre) :?>
	    <li data-id="grupoa" class="item-header-tab <?php if($this->model->fase == $slug ):?>active<?php endif;?>">
	    <a href="/resultados/fixture/{{model.torneo}}/{{slug}}">{{nombre}}</a>
	    </li>
    <?php endforeach;?>
  </ul>
</div>
<?php endif; ?>
<?php endif;?>