<section class="social-detail nav-sociales fix-sociales new">
  <ul class="item-social-detail">
    <li class="large-social-top func-large"><a href="javascript: void(0);" onclie="rpp.shareSocial(this, 'facebook','{{host}}/resultados/{{model.package}}/{{model.torneo}}');" class="facebook"><i class="icon icon-facebook"></i><span>comparte</span></a></li>
    <li class="small-social-top func-small"><a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter','{{host}}/resultados/{{model.package}}/{{model.torneo}}');" class="twitter"><i class="icon icon-twitter"></i></a></li>
    <li class="small-social-top func-small"><a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'googlemas','{{host}}/resultados/{{model.package}}/{{model.torneo}}');" class="gplus"><i class="icon icon-google-plus"></i></a></li>
    <li class="li-whatsapp small-social-top func-small"><a href="#" class="whatsapp"><i class="icon icon-whatsapp"></i></a></li>
    <li class="li-icon func-icon"> <a href="" class="plus"><i class="icon icon-plus"></i><i class="icon icon-minus"></i></a></li>
  </ul>
</section>