              <nav class="breadcrumb">
                <ul>
                  <li>
                    <figure class="logo"><a href="/"><img src="{{ehost}}/img/logo_breadcrumb.png" alt="Logo La10"></a></figure>
                  </li>
                  {% for element in elements  %} 
                  <li><?php echo ucwords( $element ) ; ?></li>
                  {% endfor %}
                </ul>
              </nav>