<?php
$primer_texto_nota='';
$articleBody = '';
$imagen_nota=array();
$video_nota=array();
$audio_nota=array();
$laudio= array();
$lvideo=array();
$relacionada_nota= array();
$description = null;
foreach (\Rpp\Services\Get\Article::part($this->model->nid,'contenido') as $contenido){
   if($contenido['tipo'] == "text" ){ 
    //$primer_texto_nota=strip_tags($contenido['texto']); 
    $description = str_replace("<p></p>","",$contenido['texto']);
    $description = explode("</p>",$description); 
    $description = @$description[0];
    $description =  strip_tags($description);
    break; 
  }
}
foreach (\Rpp\Services\Get\Article::part($this->model->nid,'contenido') as $contenido){
   if($contenido['tipo'] == "text" ){
    $articleBody = $articleBody.strip_tags($contenido['texto']); 
    if(count(@$contenido['relacionado']['items'])>=1){
      foreach ($contenido['relacionado']['items'] as $value) {
       $relacionada_nota[]='"http://rpp.pe'.@\Rpp\Services\Get\Article::nurl($value['nid']).'"';
      }
    }
  }
}
foreach (\Rpp\Services\Get\Article::part($this->model->nid,'contenido') as $contenido){
      $imagen_nota[\Rpp\Services\Get\Article::node($this->model->nid)['imagen_portada']['hash']]= '"'. \Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Content::node($this->model->nid)['imagen_portada']['hash'], 'medium').'"';
   if($contenido['tipo'] == "photo" ){
      $imagen_nota[$contenido['foto']['hash']]='"'.\Rpp\Services\Get\UrlMedia::image($contenido['foto']['hash'], 'medium').'"' ;
   }else if($contenido['tipo'] == "audio" ){
      $laudio[] = '{
             "@type": "AudioObject",
             "name": "'.htmlentities(  \Rpp\Services\Get\Article::node($this->model->nid)['titulo']).'",
             "description": "'.htmlentities(  \Rpp\Services\Get\Article::node($this->model->nid)['bajada']).'",
             "thumbnailUrl": "'.@$contenido['audio']['url_cover'].'",
             "uploadDate": "'.date('Y-m-d\TH:i:sP' , \Rpp\Services\Get\Article::node($this->model->nid)['fecha_publicacion'] ).'",
             "contentUrl": "'.@$contenido['audio']['url'].'"
            }';
   }else if($contenido['tipo'] == "video" ){
      $lvideo[] = '{
                   "@type": "VideoObject",
                   "name": "'.htmlentities(  \Rpp\Services\Get\Article::node($this->model->nid)['titulo']).'",
                   "description": "'.htmlentities(  \Rpp\Services\Get\Article::node($this->model->nid)['bajada']).'",
                   "thumbnailUrl": "'.@$contenido['video']['url_cover'].'",
                   "uploadDate": "'.date('Y-m-d\TH:i:sP' , \Rpp\Services\Get\Article::node($this->model->nid)['fecha_publicacion'] ).'",
                   "contentUrl": "'. @$contenido['video']['url'] .'"
                  }';
   }
}

foreach ( \Rpp\Services\Get\Article::part($this->model->nid,'tags') as $tag){
     $tag_nota[]=$tag['nombre'];
}

?>
  <script type="application/ld+json">
   {
       "@context": "http://schema.org",
       "@type": "Article",
       "url": "{{host}}{{pUrl(model.nid)}}",
       "publisher": {
           "@type": "Organization",
           "name": "RPP Noticias",
           "url": "http://rpp.pe",
           "logo": "http://s3.amazonaws.com/rpp-static/images/rpp-noticias.png",
           "sameAs" : [
     "https://www.facebook.com/rppnoticias",
     "https://twitter.com/rppnoticias",
     "https://plus.google.com/113482325785133390225",
     "https://www.youtube.com/user/RPPNOTICIAS",
     "https://es.wikipedia.org/wiki/Radio_Programas_del_Per%C3%BA"
   ]
       },
      "articleSection": "<?php echo @\Rpp\Services\Get\Article::part($this->model->nid,'categorias')[0]['seccion'];?>",
       "headline": "<?php echo htmlentities(  \Rpp\Services\Get\Article::node($this->model->nid)['titulo_seo'] )  ?> | <?php echo \Rpp\Services\Get\Article::node($this->model->nid)['tipo'] ?> | <?php echo @$this->model->tags[0]['nombre'] ?> | <?php echo @$this->model->seccion['nombre'] ?> | <?php echo @$this->model->seccion['seccion'] ?> | RPP Noticias",
       "alternativeHeadline": "<?php echo htmlentities( \Rpp\Services\Get\Article::node($this->model->nid)['titulo']) ?>",
       "author": "Redacción RPP Noticias",
       "mainEntityOfPage": "{{host}}{{pUrl(model.nid)}}",
       "description": "<?php echo htmlentities( $description ) ?>",
       "articleBody": "<?=htmlentities($articleBody);?>",
       "keywords": "<?php echo implode(',', $tag_nota);  ?>",
       <?php if(count($imagen_nota) >=1){ ?>
       "image": {
           "@list": [
               <?php echo  implode(',', $imagen_nota); ?>
           ]
       },
       <?php } ?>
       <?php if(count($lvideo) > 0 ): ?>
       "video": {
          "@list": [
            <?php echo implode(',',$lvideo)?>
          ]
       },
       <?php endif; ?>
       <?php if(count($laudio) > 0): ?>
       "audio": {
          "@list": [
              <?php echo implode(',', $laudio)?>
          ]
       },
       <?php endif; ?>
       "datePublished": "<?php echo date('Y-m-d\TH:i:sP' , \Rpp\Services\Get\Article::node($this->model->nid)['fecha_publicacion'] )?>",
       "dateModified": "<?php echo date('Y-m-d\TH:i:sP' , \Rpp\Services\Get\Article::part($this->model->nid,'last_modified'))?>"
       <?php if(count($relacionada_nota) >=1) :  ?>
        , "sameAs" : [ <?php echo implode(',', $relacionada_nota); ?> ]
       <?php endif; ?>
   }
</script>
