<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body>
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}
<?php if($this->model->torneo=='peru') :?>
<div class="wrap_bannerclick">
<style type="text/css">body { background: #e3e3e3 url("http://ads.us.e-planning.net/eb/3/15cd9/02994db1f63a8e4d?o=i&rnd=$RANDOM") no-repeat center top fixed } </style>
<div class="wrap_bannerclick">
<a class="banner_left" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"></a>
<a class="banner_right" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"></a>
</div>
</div>
<?php endif;?>

    <main class="wrapper">
      {{ partial('partials/ads/top2') }}
     <section class="body detail">
        <section class="content news-flow">
          <!--News cards-->
          <div class="grid">

            <div class="col-2-2">

              <section  class="box">

                <div class="box-padd none480">

                  <section class="breadcrumb-social">
                   {{ partial('partials/breadcrum/index' ,['elements':[ df_campeonato(model.torneo).nombre ] ])  }}
                   {{ partial('partials/resultados/menu/social') }}
                  </section>

                </div>
                {{ partial('partials/resultados/detallebox') }}
                <div class="box-padd">
                  <div class="box-result">
                    <div class="body-resultados">
                    {{ partial('partials/resultados/encuentro_list_' ~ model.tipofase) }}
                   </div>
                   <div class="link-resultados"><a href="/resultados/fixture/{{model.torneo}}">Ver mas </a></div>

                   <section class="inner-detail n-padd">
                     <section class="content-news">
                       <section class="ads-full">
                         <section class="ads-sidebar"></section>
                         <section class="ads-sidebar"></section>
                       </section>
                       {{ partial('partials/resultados/social/conectate') }}
                     </section>
                     <div class="clear"></div>
                   </section>
               </div>
               </div>
         </section>
         </div>
        </div>

        </section>
        {{ partial('partials/nota/sidebar/index' , [] ) }}

      </section>

    </main>
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    <script>
    $(function(){
      $('#torneo_select').on('change', function () {
          var url = $(this).val(); // get selected value
          if (url) { // require a URL
              window.location = url; // redirect
          }
          return false;
      });
    });
   </script>
    {{ partial('partials/footer/tracking') }}
    </div>
  </body>
