<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
{{ partial('partials/head/indexportada') }}
  <body data-bg="{{model.epl_kvs}}" data-x="lazy, slide" class="page404">
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
  <div id="wrap">
    <!--Header-->
    {{ partial('partials/header/index') }}

    <div id="content" role="main">
      <div class="grid pad">
        <div class="col-primary">
          <div class="content-404">

            <h1>Página <br> no encontrada</h1>
            <form action="/buscar" method="POST" onsubmit='fn(this, event, {"method":"search"})' class="search-form">
              <input type="search" name="texto" placeholder="Ingrese su búsqueda y presione enter..." class="search-input">
              <button><span class="icon-magnifier"></span></button>
            </form>
          </div>
        </div>
        <aside class="col-secondary sidebar">
          {{ partial('partials/ads/right') }}
          <!-- pub-300 -->
          {{ partial('partials/sidebar/calientes' , ['slug':'home'] , trackurl ) }}
        </aside>
      </div>
    </div>

    <!-- .wrapper -->
    <!--Footer-->
    {{ partial('partials/footer/index' ,[] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
  </body>
</html>