<section id="featured" class=" group">
{{ partial('partials/portada/grilla/home/hp_'  ~ model.hora_planeta ) }}
<div class="feat-content">
    <div class="feat-block group">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>
     {{ partial('partials/portada/grilla/block/hentry', [ 'item' : item ]) }}
     <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
     <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
     <?php break;endforeach;?>
    </div>


    <div class="feat-block group">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?> 
        <?php if($position>=3) break; ?>     
        <?php if(empty(@$item['nid'])) continue;?>    
         <div class="col-3">            
          {{ partial('partials/portada/grilla/block/hentry_group', [ 'item' : item , 'class' : 'third' , 'img_size' : 'small']) }}
         </div>
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
         <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>        
        <?php endforeach;?> 


        <div class="col-3">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?> 
        <?php if($position>=5) break; ?>     
        <?php if(empty(@$item['nid'])) continue;?>           
          {{ partial('partials/portada/grilla/block/hentry_title', [ 'item' : item , 'class' : 'third']) }}
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>         
        <?php endforeach;?> 

        </div>

    </div><!-- .feat-block -->

</div>

    <!-- feat-content -->

    <aside class="feat-sidebar">
        {{ partial('partials/ads/right') }}

        <!-- pub-300 -->
        {{ partial('partials/portada/grilla/block/tag_portada') }}
    </aside>

</section>