<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}
<body data-bg="{{model.epl_kvs}}"  data-x="lazy, sticky, slide" class="result-search">
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
<div id="wrap">
    <!--Header-->
    {{ partial('partials/header/index') }}

    <div id="content" role="main">
        <div class="grid pad">
          <div class="col-primary">
            <div class="story-top box-mod pt10">
                {% if model.response is empty %}
              {% set result = 'empty' %}
            {%else%}
               {% set result = '' %}
            <h1>Alrededor de {{model.response.numFound}} resultados con: <mark >'<?php echo urldecode($this->model->search_text); ?>'</mark></h1>
            {% endif %}                
            </div>

            {% if model.response is empty %}
                  {% set result = 'empty' %}
                {%elseif model.response.numFound==0 %}
                   
                   <div class="noresult">
                    <p>Te recomendamos iniciar una nueva búsqueda</p>
                    <form class="search" id="search-content" action="/buscar" method="post">
                      <input type="text" placeholder="BUSCAR" name="texto">
                      <button><span class="icon-9"></span> Buscar</button>
                    </form>
                  </div>
                
            {% endif %}
           

            <div class="flow-row">
              <div class="row">
                   {{ partial('buscar/result' ~ result , ['response':model.response] , trackurl) }}

              </div>
              
            </div>
          </div>

          <aside class="col-secondary sidebar">
                
                {{ partial('partials/ads/right') }}
                {{  partial('partials/portada/grilla/block/tag_portada' , ['slug':'home'])  }}
                {{ partial('partials/ads/right1') }}
                <!-- partial('partials/sidebar/clima') -->
                {{ partial('partials/ads/right2') }}
                <?php $sdb = 'mas-leidas';?>
                  <?php $nombre = 'Las noticias más leídas';?>
                  <?php $cantidad = 10;?>
                  <?php $tipo ='estandar';?>
                  <?php $script =  '';  ?>
                   {{partial('partials/portada/sidebar/' ~ tipo ~ '/index_' ~ sdb ,['tag':  sdb , 'nombre': nombre , 'cantidad': cantidad ,'slug' : 'home' , 'script' : script ]) }}
                {{ partial('partials/ads/right3') }}                

          </aside>
          
        </div>

        {{ partial('partials/ads/middle2') }}
      </div>

    <!-- .wrapper -->
    <!--Footer-->
    {{ partial('partials/footer/index' ,[] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>