<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
{{ partial('partials/head/index') }}
  <body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
  <div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}
   <?php $gui = @$_GET['c']; ?>
    <div class="wrapper body group">
        <div class="category search wrap group">
          <iframe src="http://admin2.webrpp.com/concursos/fichasview.php?guid=<?php echo $gui ?>" style="width:100%;height:984px" ></iframe>
        </div>
    </div>
    <!-- .wrapper -->
    <!--Footer-->
    {{ partial('partials/footer/index' ,[] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
  </body>
</html>