<div class="row box-mod">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>   
     {{ partial('partials/portada/grilla/block/hentry_main', [ 'item' : item ]) }}
    <?php if($namespace=='home'){ ?>
    <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
    <?php }else{ ?>
    <?php $unset = 'unset_'.$namespace ;?>
    <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>
    <?php } ?>
    <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
    <?php break;endforeach;?>
</div>


