<div class="hdr-foot">
  <div data-x='{"variableWidth":true}' class="x-slide grid temas">
    <nav class="x-wrapper">
      <ul class="x-container">
        <?php if($this->model->slug_seccion == 'actualidad'):?>
                  <li class="x-item"><a href="/lima" rel="tag">Lima</a></li>
               <?php elseif ($this->model->slug_seccion == 'deportes'): ?>
                  <li class="x-item"><a href="/futbol" rel="tag">Futbol</a></li>
                  <li class="x-item"><a href="/voley" rel="tag">Voley</a></li>
                  <li class="x-item"><a href="/tenis" rel="tag">Tenis</a></li>
                  <li class="x-item"><a href="/automovilismo" rel="tag">Automovilismo</a></li>
                  <li class="x-item"><a href="/lucha" rel="tag">Lucha</a></li>
                  <li class="x-item"><a href="/multideportes" rel="tag">Multideportes</a></li>
               <?php elseif ($this->model->slug_seccion == 'entretenimiento'): ?>
                  <li class="x-item"><a href="/cultura" rel="tag">Cultura</a></li>
                  <li class="x-item"><a href="/tv" rel="tag">Tv</a></li>
                  <li class="x-item"><a href="/cine" rel="tag">Cine</a></li>
                  <li class="x-item"><a href="/musica" rel="tag">Musica</a></li>
                  <li class="x-item"><a href="/famosos" rel="tag">Famosos</a></li>
                <?php elseif ($this->model->slug_seccion == 'vida'): ?>
                  <li class="x-item"><a href="/vida-y-estilo" rel="tag">Vida Y Estilo</a></li>
                  <li class="x-item"><a href="/viajes" rel="tag">Viajes</a></li>
                  <li class="x-item"><a href="/gastronomia" rel="tag">Gastronomía</a></li>
                  <li class="x-item"><a href="/mascotas" rel="tag">Máscotas</a></li>
                <?php elseif ($this->model->slug_seccion == 'tec'): ?> 
                  <li class="x-item"><a href="/tecnologia" rel="tag">Tecnología</a></li> 
                  <li class="x-item"><a href="/ciencia" rel="tag">Ciencia</a></li> 
                <?php elseif ($this->model->slug_seccion == 'viral'): ?>
                  <li class="x-item"><a href="/virales" rel="tag">Virales</a></li> 
        <?php endif;?>
      </ul>
    </nav>
    <div class="x-arrows"><a href="#prev" class="x-prev"><span class="icon-chevron-left icon-prev"></span></a><a href="#next" class="x-next"><span class="icon-chevron-right icon-next"></span></a></div>
  </div>
</div>