                <div id="submenu-radio" class="submenu-section">
                    <div class="live-prog">
                        <a href="javascript:;">
                            <h2>Ampliación de Noticias</h2>
                            <img src="{{ehost}}/images/header-ampliacion-noticias.png" alt="Ampliación de Noticias">
                        </a>
                    </div>
                    <ul class="submenu-items group">
                        <li><a href="javascript:;">RPP Informando</a></li>
              <li><a href="javascript:;">Despierta Perú</a></li>
              <li><a href="javascript:;">Rotativa del aire primera edición</a></li>
              <li><a href="javascript:;">Ampliación de noticias</a></li>
              <li><a href="javascript:;">Siempre en casa</a></li>
              <li><a href="javascript:;">La rotativa del aire</a></li>
              <li><a href="javascript:;">Los histosos</a></li>
              <li><a href="javascript:;">Era tabú</a></li>
              <li><a href="javascript:;">El show del deporte</a></li>
              <li><a href="javascript:;">De frente y sin máscaras</a></li>
              <li><a href="javascript:;">Enfoque de los sábados</a></li>
              <li><a href="javascript:;">Diálogo de fe</a></li>
              <li><a href="javascript:;">La divina comida</a></li>
              <li><a href="javascript:;">Cuidando tu salud</a></li>
              <li><a href="javascript:;">Ventana ecónomica</a></li>
              <li><a href="javascript:;">En escena</a></li>
              <li><a href="javascript:;">Deporte al máximo</a></li>
              <li><a href="javascript:;">Más allá de las canas</a></li>
              <li><a href="javascript:;">Peruanos en el exterior</a></li>
              <li><a href="javascript:;">Ampliación del domingo</a></li>
              <li><a href="javascript:;">Domingo es fiesta</a></li>
              <li><a href="javascript:;">Todo deporte</a></li>
              <li><a href="javascript:;">Letras en el tiempo</a></li>
              <li><a href="javascript:;">Lo mejor de la semana de los chistosos</a></li>
              <li><a href="javascript:;">Los especiales del domingo</a></li>
              <li><a href="javascript:;">Buscapersonas</a></li>
              <li><a href="javascript:;">Lo mejor de en escena</a></li>
                    </ul>
                </div>