<div class="hdr-foot">
  <div data-x='{"variableWidth":true}' class="x-slide grid temas">
    <nav class="x-wrapper">
      <ul class="x-container">
        <?php if(@\Rpp\Services\Get\Temas::get_temas()):?>   
         <?php foreach ( \Rpp\Services\Get\Temas::get_temas()->tags as $tema) : ?>         
          <li class="x-item"><a href="{{host}}/tema-{{tema['slug']}}?ns_source=self&ns_mchannel=portada.home&ns_campaign=menu.temas" {{model.htmlrel}}>{{tema['nombre']}}</a></li>
         <?php endforeach;?>
        <?php endif;?> 
      </ul>
    </nav>
    <div class="x-arrows"><a href="#prev" class="x-prev"><span class="icon-chevron-left icon-prev"></span></a><a href="#next" class="x-next"><span class="icon-chevron-right icon-next"></span></a></div>
  </div>
</div>