   <div id="submenu-tv" class="submenu-section">
        <div class="live-prog">
            <a href="#">
                <h2>Central de Información</h2>
                <img src="{{ehost}}/images/header-ampliacion-noticias.png" alt="Central de Información">
            </a>
        </div>
        <ul class="submenu-items group">
            <li><a href="#">Chema a las 11</a></li>
            <li><a href="#">En primera fila</a></li>
            <li><a href="#">Las 5 de las 7</a></li>
            <li><a href="#">Central de información</a></li>
        </ul>
    </div>

    