<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/pl' ~ model.package) }}
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}" class="nota-{{model.tipo}}">

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=185239485185";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/indexnoticia') }}
    <div class="single-cont wrapper body group">

        <article class="hnews group">
        {{ partial('partials/nota/tipo/pl' ~ model.package  ~ '/index'  ~ model.tipo ) }}
        </article>

        {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

    </div>
    <!--Footer-->

    {{ partial('partials/footer/index') }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    <script src="{{ehost}}/scripts/fixed.js?v={{eversion}}"></script>
    {{ partial('partials/footer/tracking') }}
</div>
</body>
