<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:media="http://search.yahoo.com/mrss/" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0" xml:base="{{host}}">
<channel>
    <title>RPP NOTICIAS</title>
    <link>{{host}}</link>
    <description><![CDATA[ RPP Noticias tiene las &uacute;ltimas noticias sobre pol&iacute;tica, futbol y far&aacute;ndula nacional e internacional. Ediciones regionales y de todo el Peru ]]></description>
    <language>es</language>
    <copyright>RPP NOTICIAS</copyright>
    <lastBuildDate><?php echo date('r') ?></lastBuildDate>
    <ttl>15</ttl>

	<image>
		<title>RPP NOTICIAS</title>
		<url>{{ehost}}/images/rpp-noticias.png</url>
		<link>{{host}}</link>
	</image>

     <?php foreach(\Rpp\Services\Get\Flow::home(50) as $item) :  ?>
      <item>
        <title><![CDATA[{{getNode(item._id).titulo}}]]></title>
        <description><![CDATA[{{getNode(item._id).bajada}}]]></description>
        <pubDate>{{date('r',getNode(item._id).fecha_publicacion)}}</pubDate>
        <link>{{host}}{{nUrl(item._id)}}</link>
        <guid>{{item._id}}</guid>
        <dc:type>Artículo</dc:type>
                <media:content url="{{getNode(item._id).imagen_portada['url']}}" type="image/jpeg">
        <media:description/></media:content>
        <media:keywords><![CDATA[<?php foreach (\Rpp\Services\Get\Content::part($item->_id,'tags') as $tag): ?> {{tag['nombre']}},<?php endforeach; ?> Noticias Última Hora]]></media:keywords>
      </item>
     <?php endforeach;?>
</channel>
</rss>