<article>
  <figure>
    <a href="{{nUrl(nid)}}">
      <img src="{{ cdn_image(getNode(nid).imagen_portada['hash'], img_size ) }}" alt="{{ getNode(nid).imagen_portada['alt'] }}" width="280">
    </a>
    <figcaption>
      <span>Auspiciado por:</span>
      <a href="/tema-la-seguridad-vial">
        <img src="{{getPart(nid ,'imagen_branding')}}" alt="">
      </a>
    </figcaption>
  </figure>
  <h2>
    <a href="{{nUrl(nid)}}">{{ getNode(nid).titulo_corto }}</a>
  </h2>
</article>