<?php if(@\Rpp\Services\Get\Destacados::portada($slug)->campana_cabecera['slug']):?>
<?php $campana_cabecera = \Rpp\Services\Get\Destacados::portada($slug)->campana_cabecera['slug'];?>
<?php if( $this->_view->exists('partials/portada/bloque/tag/campana/'.$campana_cabecera) ) :?>
	{{ partial('partials/portada/bloque/tag/campana/' ~ campana_cabecera ) }}
<?php else:?>
<div class="pad no-pad-top">
	<div class="ads">
	 <a href="/tema-{{ getGrilla(slug).campana_cabecera['slug'] }}" target="_blank"><img  src="{{ehost}}/images/{{ getGrilla(slug).campana_cabecera['slug'] }}.png" alt="{{ getGrilla(slug).campana_cabecera['nombre'] }}"></a>
	 </div>
</div>
<?php endif;?>
<?php endif;?>

