<?php $sdb = @\Rpp\Services\Get\Destacados::portada($slug)->lateral_8['slug'];?>
<?php $nombre = @\Rpp\Services\Get\Destacados::portada($slug)->lateral_8['nombre'];?>
<?php $cantidad = @\Rpp\Services\Get\Destacados::portada($slug)->lateral_8['cantidad'];?>
<?php $tipo = @\Rpp\Services\Get\Destacados::portada($slug)->lateral_8['tipo'];?>
<?php $script =  @\Rpp\Services\Get\Destacados::portada($slug)->lateral_8['script'];  ?>

<?php if( $tipo ) :?>
	<?php if( $this->_view->exists('partials/portada/sidebar/'.$tipo.'/index_'.$sdb ) ) :?>
	{{partial('partials/portada/sidebar/' ~ tipo ~ '/index_' ~ sdb ,['tag':  sdb , 'nombre': nombre , 'cantidad': cantidad ,'slug' : slug]) }}
	<?php else: ?>
	{{partial('partials/portada/sidebar/' ~ tipo ~ '/index' ,['tag':  sdb , 'nombre': nombre , 'cantidad': cantidad ,'slug' : slug , 'script' : script ]) }}
	<?php endif; ?>
<?php endif; ?>
