<article class="card divided">
	<figure class="holder">
		<a {{ partial('partials/portada/grilla/block/url/' ~ getNode(item['nid']).tipo , [ 'nid' : item['nid'] ] ) }} class="cover">
		 {{ partial('partials/generic/lazy_image' , ['content' : cdn_image(item['imagen_portada']['hash'], 'small' ), 'alt': item['imagen_portada']['alt'] ]) }}
            {{ partial('partials/portada/grilla/block/icon/' ~ getNode(item['nid']).tipo ) }}
		</a>
	</figure>
	<div class="cont">
	  <h3><a  {{ partial('partials/portada/grilla/block/url/' ~ getNode(item['nid']).tipo, [ 'nid' : item['nid'] ] ) }}>{{item['titulo']}}</a></h3>
	</div>
</article>
