<section class="girl10-news module module-pink">          
  <h3>LA CHICA 10</h3>
  <div class="box">
    <ul class="title-top">
      <li>
      <?php foreach (\Rpp\Services\Get\Flow::tag('chica-10') as $item):?>
        <article>
          <figure class="media"><a href="{{nUrl(item._id)}}{{TrackUrl('image')}}">
          <img src="{{ cdn_image(getNode(item._id).imagen_portada['url']) }}" title="{{getNode(item._id).titulo}}" alt="{{getNode(item._id).titulo_corto}}">
          </a></figure>
          <h2><span><a href="{{nUrl(item._id)}}{{TrackUrl('texto')}}">{{getNode(item._id).titulo_corto}}</a></span></h2>
        </article>
      <?php break; endforeach; ?>
      </li>
    </ul>
  </div>
</section>