<section class="goals module module-blue">
<h3>PEPAZAS</h3>
<div class="box">
<ul class="title-top">
  <?php foreach (\Rpp\Services\Get\Flow::tag('pepazas',5) as $position => $item) : ?>
   <li>
    <article>
     <figure class="media"><a href="{{nUrl(item._id)}}{{TrackUrl(position+1)}}"><img src="{{cdn_image( getNode(item._id).imagen_portada['hash'] ,'medium')}}" alt="{{getNode(item._id).imagen_portada['alt']}}"></a></figure>
     <h2><span><a href="{{nUrl(item._id)}}{{TrackUrl(position+1)}}">{{getNode(item._id).titulo}}</a></span></h2>
    </article>
   </li>
<?php endforeach;?>
</ul>
</div>
</section>