
<?php  if( /*$this->model->user*/false):?>
<?php \Rpp\Services\Get\Recomendados::rebuild($this->model->user); ?>
{% cache "sidebar.recomendados." ~ model.user 360 %}
<?php var_dump(\Rpp\Services\Get\Recomendados::load($this->model->user))?>
<?php if(count(\Rpp\Services\Get\Recomendados::load($this->model->user))>0 ): ?>
<?php $position = 0;?>
<div class="sidebar-panel" id="more-topic">
    <h2 class="panel-title">Más sobre este tema</h2>
    <?php foreach (\Rpp\Services\Get\Recomendados::load($this->model->user) as $nid) : ?>
    <?php if(empty(\Rpp\Services\Get\Content::part($nid,'_id'))) continue;?>
    <article class="left-photo hnews hentry group">
        <figure class="hmedia">
            <a href="{{nUrl(nid)}}{{TrackUrl(position+1)}}">
              <img src="{{ cdn_image( getNode(nid).imagen_portada['hash'] ,'xsmall')  }}"  alt="{{getNode(nid).imagen_portada['alt']}}">
            </a>
            <figcaption class="fn hide">{{getNode(nid).imagen_portada['alt']}}</figcaption>
        </figure>

        <div class="entry-cont ">

            <h3 class="entry-title"><a class="url" href="{{nUrl(nid)}}{{TrackUrl(position+1)}}" rel="bookmark">{{getNode(nid).titulo}}</a></h3>

            <footer class="hide">
                <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                        Noticias</a></p>
            </footer>

        </div>
        <!-- .entry-cont -->


    </article>
    <?php if($position>=5) break; ?>
    <?php endforeach;?>
</div>
<?php else:?>
    <div class="sidebar-panel" id="more-topic">
    </div>
<?php endif ;?>
{% endcache %} 
<?php endif ;?>