    <section class="goals module module-yellow">          
      <h3>redes sociales</h3>
      <div class="box">
        <div class="wrapper-sociales-fix">
          <div style="width: 100%; height: 300px; overflow:hidden; line-height:100%;" data-crowdynews-widget="la10RPP/la10pe-widget-horizontal"></div>
          <div data-width="260" data-type="script" data-original="//widget.crowdynews.com/js/widget.js" class="pro lazy"></div>
        </div>
      </div>
    </section>