<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:video="http://www.google.com/schemas/sitemap-archivo/1.1">

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2016?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2015?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2014?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2013?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2012?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2011?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2010?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/2009?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>
</urlset>
