<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>               
            <loc>{{host}}/sitemap/web?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
   <sitemap>               
            <loc>{{host}}/sitemap/news?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
   <sitemap>               
            <loc>{{host}}/sitemap/archivos?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
</sitemapindex>