<div class="columns-2">
	<div class="cell no-border ads ads-300 x-lazy" data-x='{"type":"ads","position":"Interna{{position}}"}'>
		<!--script type="text/javascript">eplAD4M("Interna{{position}}");</script-->
	</div>
	<div class="cell no-border ads ads-300 x-lazy" data-x='{"type":"ads","position":"Interna{{position+1}}"}'>
		<!--script type="text/javascript">eplAD4M("Interna{{position+1}}");</script-->
	</div>
</div>