<?php
$misecr=trim(strtolower($this->model->epl_sec));
$idmisecr='';
switch ($misecr) {
    case 'politica':
        $idmisecr='00000001623b7bca';
        break;
    case 'lima':
        $idmisecr='00000001623c5db7';
        break;
    case 'mundo':
        $idmisecr='00000001623c5dbe';
        break;
    case 'vida-y-estilo':
        $idmisecr='00000001623c5dc5';
        break;
    case 'viajes':
        $idmisecr='00000001623c5dca';
        break;
    case 'gastronomia':
        $idmisecr='00000001623c5dcf';
        break;
    case 'mascotas':
        $idmisecr='00000001623c5dd5';
        break;
    case 'tecnologia':
        $idmisecr='00000001623c5df5';
        break;
    case 'ciencia':
        $idmisecr='00000001623c5e0f';
        break;
    case 'virales':
        $idmisecr='00000001623c5e28';
        break;
    case 'peru':
        $idmisecr='00000001623c5e52';
        break;
    case 'economia':
        $idmisecr='00000001623c5e59';
        break;
    case 'futbol':
        $idmisecr='00000001623c5e60';
        break;
    case 'voley':
        $idmisecr='00000001623c5e66';
        break;
    case 'tenis':
        $idmisecr='00000001623c5e7d';
        break;
    case 'automovilismo':
        $idmisecr='00000001623c5e8d';
        break;
    case 'lucha':
        $idmisecr='00000001623c5e9c';
        break;
    case 'multideportes':
        $idmisecr='00000001623c5eac';
        break;
    case 'cultura':
        $idmisecr='00000001623c5eb1';
        break;
    case 'tv':
        $idmisecr='00000001623c5ecd';
        break;
    case 'cine':
        $idmisecr='00000001623c5ef1';
        break;
    case 'musica':
        $idmisecr='00000001623c5f04';
        break;
    case 'famosos':
        $idmisecr='00000001623c5f13';
        break;
}

//echo $this->model->epl_sec.' '.$idmisecr.' '.$this->model->tipo;
?>
<?php if($idmisecr!=''){ ?>
<div class="perured"><div id="insertAdSpaceBeforeThis_<?=$idmisecr;?>" ></div></div>
  <!-- End Código Sidebar -->

  <!-- Begin PERÚ RED-->
  <script type="text/javascript">
    (function() {
      try {
          var scriptEl = document.createElement('script');
          scriptEl.type = 'text/javascript';
          scriptEl.async = 'async';
          scriptEl.src = ('https:' == document.location.protocol) ? 'https://scdn.cxense.com/cx.js' : 'http://cdn.cxense.com/cx.js';
          var targetEl = document.getElementsByTagName('script')[0];
          targetEl.parentNode.insertBefore(scriptEl, targetEl);
      } catch (e) {};
    }());
  </script>
  <script type="text/javascript">
    var cX = cX || {};
    cX.callQueue = cX.callQueue || [];
    cX.callQueue.push([ 'insertAdSpace', {
      // 000000015f477401 Cambiar por el código xde sección
      adSpaceId : '<?=$idmisecr;?>',
      resizeToContentSize : true,
      useMappedRenderTemplate : true
    } ]);
    </script>


<?php } ?>
