<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/' ~ model.package) }}
<body data-bg="{{model.epl_kvs}}" data-x="sticky, lazy, media, slide, gallery, ads-body" class="nota-{{model.tipo}}">
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
<div id="wrap">
    <!--Header-->
    {{ partial('partials/header/indexnoticia') }}
    <div id="content" role="main">
    {{ partial('partials/ads/top') }}
        <div class="grid pad">
            <div class="story">
                {{ partial('partials/nota/tipo/' ~ model.package  ~ '/index'  ~ model.tipo ) }}
            </div>
            {{ partial('partials/ads/middle2') }}
        </div>
    </div>
    <!--Footer-->

    {{ partial('partials/footer/index') }}
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
