<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/' ~ model.package) }}
<body data-x="social-native, gallery">
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
<div id="wrap">
    <!--Header-->
    {{ partial('partials/header/indexshort') }}
    <div id="content" role="main">
    <?php $galerias = array(); ?>
    <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'galeria') as $v => $key) :?>
    <?php $item['src']=  \Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['foto']['hash'], 'large');?>
    <?php $item['caption']= \Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['foto']['alt'] ;?>
    <?php if(!empty(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['via'])) $item['caption'] .= ' | Fuente: '.\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['via']?>
    <?php if(!empty(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['credito'])) $item['caption'] .= ' | Fotógrafo: '.\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['credito']?>
    <?php $galerias[]=$item; ?>
    <?php endforeach;?>
     <div  data-x='{"comscore" : "{{model.comscore}}", "ads":"Right", "page": <?=$this->model->position;?> , "urlState":"{{host}}{{nUrl(model.nid)}}", "title": "<?=urlencode(\Rpp\Services\Get\Content::node($this->model->nid)->titulo);?>"}' data-sources='<?=json_encode($galerias,JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE)?>' itemscope itemtype="http://schema.org/ImageGallery" class="x-gallery x-gallery-expanded">
        <a href="{{host}}{{nUrl(model.nid)}}" class="x-close"><i class="icon-cancel"></i></a>
     </div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
    
</div>
</body>
