<div class="date-table">
    <h2 class="panel-title">Fechas Anteriores</h2>
	<div
	id="rpp-calendar"
	data-date-local="<?php echo date('Y-m-d' , $this->model->time) ?>"
	data-date-current="<?php echo date('Y-m-d') ?>"
    <?php if($this->model->mode=='seccion'):?>
    data-path="/archivo/{{model.slug}}/"
    <?php else:?>
    data-path="/archivo/"   
    <?php endif;?>
	data-year-scope="5"
	></div>
</div>