<div class="sidebar-panel weather-sidebar">
    <h2 class="panel-title">El clima en tu ciudad</h2>

    <div class="weather-title group">
        <h3>Lima</h3>
        <select class="city" dir="rtl">
            <option value="Amazonas">Amazonas</option>
            <option value="Ancash">Ancash</option>
            <option value="Apurimac">Apurimac</option>
            <option value="Arequipa">Arequipa</option>
            <option value="Ayacucho">Ayacucho</option>
            <option value="Cajamarca">Cajamarca</option>
            <option value="Cuzco">Cuzco</option>
            <option value="Huancavelica">Huancavelica</option>
            <option value="Huanuco">Huanuco</option>
            <option value="Ica">Ica</option>
            <option value="Junin">Junin</option>
            <option value="La Libertad">La Libertad</option>
            <option value="Lambayeque">Lambayeque</option>
            <option value="Lima">Lima</option>
            <option value="Loreto">Loreto</option>
            <option value="Madre de Dios">Madre de Dios</option>
            <option value="Moquegua">Moquegua</option>
            <option value="Pasco">Pasco</option>
            <option value="Piura">Piura</option>
            <option value="Puno">Puno</option>
            <option value="San Martin">San Martin</option>
            <option value="Tacna">Tacna</option>
            <option value="Tumbes">Tumbes</option>
            <option value="Ucayali">Ucayali</option>
        </select>
    </div>
    <ul class="weather-forecast group">
        <li>
            <h4>Ahora</h4>

            <div class="w1">25º <span></span></div>
        </li>
        <li>
            <h4>Por la noche</h4>

            <div class="w2">22º <span></span></div>
        </li>
        <li class="last">
            <h4>Mañana</h4>

            <div class="w3">26º <span></span></div>
        </li>
    </ul>
</div>