<div class="sidebar-panel" id="noticia-360">
                    <h2 class="panel-title"><a href="#">La Noticia 360</a></h2>

                    <article class="left-photo hnews group">

                        <figure class="hmedia">

                            <a href="#">


                                <img class="photo" src="{{ehost}}/images/small-article-03.jpg"
                                     alt="Denuncia: Roban anillo matrimonial a anciano en hospital Rebagliati">
                            </a>
                            <figcaption class="fn hide">Denuncia: Roban anillo matrimonial a anciano en hospital
                                Rebagliati
                            </figcaption>
                        </figure>

                        <div class="entry-cont ">

                            <h3 class="entry-title"><a class="url" href="#" rel="bookmark">Denuncia: Roban anillo
                                    matrimonial a anciano en hospital Rebagliati</a></h3>


                            <footer class="hide">
                                <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                                        Noticias</a></p>
                            </footer>

                        </div>
                        <!-- .entry-cont -->


                    </article>

                    <article class="left-photo hnews hentry group">

                        <figure class="hmedia">

                            <a href="#">


                                <img class="photo" src="{{ehost}}/images/small-article-04.jpg"
                                     alt="Chosica: Ocho huaicos afectan viviendas en diferentes puntos del distrito">
                            </a>
                            <figcaption class="fn hide">Chosica: Ocho huaicos afectan viviendas en diferentes puntos del
                                distrito
                            </figcaption>
                        </figure>

                        <div class="entry-cont ">

                            <h3 class="entry-title"><a class="url" href="#" rel="bookmark">Chosica: Ocho huaicos afectan
                                    viviendas en diferentes puntos del distrito</a></h3>


                            <footer class="hide">
                                <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                                        Noticias</a></p>
                            </footer>

                        </div>
                        <!-- .entry-cont -->


                    </article>

                </div>