<div class="sidebar-panel dia-sidebar">
<h2 class="panel-title">Un día como hoy <a class="right-link" href="#">
        <time class="pubdate" datetime="2015-01-26T15:16:03-05:00">26 de enero</time>
    </a></h2>

<article class=" hnews group">

    <figure class="hmedia">

        <a href="#">
            <span class="icon icon-8"></span>

            <img class="photo" src="{{ehost}}/images/dia-sidebar-01.jpg"
                 alt="Entra en vigor el protocolo de Kioto">
        </a>
        <figcaption class="fn hide">Entra en vigor el protocolo de Kioto</figcaption>
    </figure>

    <div class="entry-cont ">

        <h3 class="entry-title"><a class="url" href="#" rel="bookmark">Entra en vigor el protocolo
                de Kioto</a></h3>


        <footer class="hide">
            <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                    Noticias</a></p>
        </footer>

    </div>
    <!-- .entry-cont -->


</article>

</div>