<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" id='tema' class="{{model.tema}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/indextag_1'  ) }}

    <div class="wrapper body group">

      <div class="wrap group wrapper-especial">



            {{ partial('tag/cabecera/cb_encuesta', ['portada':'encuesta'] ) }}



  <style>
    .iframeWrapper {
        position: relative;
        padding-bottom: 58.75%;
        padding-top: 25px;
        height: 0;
    }
    .iframeWrapper iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
    @media (max-width: 767px) {
        .iframeWrapper {
            margin-top: 10px;
        }
    }
  </style>
  <div class="iframeWrapper">
         <iframe style="width:100%; margin-bottom:20px; height:640pxgit" src="http://rpp.pe/elecciones-peru-2016/infografia_evolucion_intencion_de_voto.html" frameborder="0" scrolling="no" ></iframe>
  </div>

<div style="height:20px"></div>

        {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->
    </div>

    
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
