<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" id='tema' class="{{model.tema}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/indextag_1') }}

    <div class="wrapper body group">

      <div class="wrap group wrapper-especial">

 

            {{ partial('tag/cabecera/cb_' ~ model.slug , ['portada':'redes'] ) }}

            <section id="featured" class="group">

                    <iframe style="width:100%; margin-bottom:20px; height:1800px" src="http://widget.crowdynews.com/fullpage/#?cnCO=RPPpe/elecciones-2016-full"></iframe>

            </section>     


        </div>

        {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->
    </div>

    
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
