<select id="torneo_select">
  <option>Más torneos</option>
  <option value="/resultados/fecha/peru">Copa Movistar</option>
  <option value="/resultados/fecha/premierleague">Premier League</option>
  <option value="/resultados/fecha/espana">Liga BBVA</option>
  <option value="/resultados/fecha/alemania">Bundesliga</option>
  <option value="/resultados/fecha/italia">Serie A</option>
  <option value="/resultados/fecha/champions">Champions League</option>
</select>
