    <!-- Laterales -->
    <script type='text/javascript'>
      (function() {
        var useSSL = 'https:' == document.location.protocol;
        var src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
        document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
      })();
    </script>
    <script type='text/javascript'>
      googletag.cmd.push(function() {
        googletag.defineSlot('/1028310/La10.pe-Lateral1', [160, 600], 'div-gpt-ad-1435012693333-0').addService(googletag.pubads());
        googletag.defineSlot('/1028310/La10.pe-Lateral2', [160, 600], 'div-gpt-ad-1435012770989-0').addService(googletag.pubads());
        googletag.pubads().enableSingleRequest();
        googletag.pubads().collapseEmptyDivs();
        googletag.pubads().enableSyncRendering();
        googletag.enableServices();
      });
    </script>
    <!-- END Laterales -->