<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{model.titulo}} </title>
    {{ partial('partials/head/metas') }}

    <meta property="og:title" itemprop="headline" content="{{model.titulo_social}}" />
    <meta property="og:description" itemprop="description" content="{{model.description}}" />
    <meta property="og:image" itemprop="image" content="{{model.img_social}}" />
    <meta property="og:url" itemprop="url" content="{{host}}{{model.urlcanonical }}" />
    {{ partial('partials/head/twittercard') }}
    {{ partial('partials/head/dublin') }}

    <!-- Canonical -->
    <link rel="canonical" href="{{host}}{{model.urlcanonical}}"/>

    <link rel="shortcut icon" type="image/x-icon" href="{{ehost}}/favicon.ico">
    <link rel="apple-touch-icon" sizes="57x57" href="{{ehost}}/images/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ehost}}/images/favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ehost}}/images/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ehost}}/images/favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ehost}}/images/favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ehost}}/images/favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ehost}}/images/favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ehost}}/images/favicons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ehost}}/images/favicons/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="{{ehost}}/images/favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="{{ehost}}/images/favicons/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="{{ehost}}/images/favicons/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="{{ehost}}/images/favicons/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="{{ehost}}/images/favicons/manifest.json">



    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/reset.css?v={{eversion}}">
    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/jquery.jvectormap.css?v={{eversion}}">
    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/icons.css?v={{eversion}}">
    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/main.css?v={{eversion}}">
    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/responsive.css?v={{eversion}}">
    <link rel="stylesheet" type="text/css" href="{{ehost}}/styles/carousel.css?v={{eversion}}">
  <script id="navegg" type="text/javascript" src="//tag.navdmp.com/tm22924.js" ></script>
  {{ partial('partials/head/epl') }}





   <!-- Begin comScore Inline Tag 1.1111.15 -->
   <script type="text/javascript">
   function udm_(a)
   {
    var b="comScore=",c=document,d=c.cookie,e="",f="indexOf",g="substring",h="length",i=2048,j,k="&ns_",l="&",m,n,o,p,q=window,r=q.encodeURIComponent||escape;
    if(d[f](b)+1)
    for(o=0,n=d.split(";"),p=n[h];o<p;o++)
     m=n[o][f](b),m+1&&(e=l+unescape(n[o][g](m+b[h])));
     a+=k+"_t="+ +(new Date)+k+"c="+(c.characterSet||c.defaultCharset||"")+"&c8="+r(c.title)+e+"&c7="+r(c.URL)+"&c9="+r(c.referrer),a[h]>i&&a[f](l)>0&&(j=a[g](0,i8).lastIndexOf(l),a=(a[g](0,j)+k+"cut="+r(a[g](j+1)))[g](0,i)),c.images?(m=new Image,q.ns_p||(ns_p=m),m.src=a):c.write("<","p","><",'img src="',a,'" height="1" width="1" alt="*"',"><","/p",">");
   }
   udm_('http'+(document.location.href.charAt(4)=='s'?'s://sb':'://b')+'.scorecardresearch.com/b?c1=2&c2=6906613&ns_site=rpp&name={{model.comscore}}{{model.dax_category_script}}{{model.dax_theme_script}}');
   </script>
   <noscript>
   <p><img src="http://b.scorecardresearch.com/p?c1=2&amp;c2=6906613&amp;ns_site=rpp&amp;name={{model.comscore}}{{model.dax_category_img}}{{model.dax_theme_img}}" height="1" width="1" alt="*"></p>
   </noscript>
   <!-- End comScore UDM code -->



</head>
