
<!-- Open Graph -->
<meta property="og:site_name" content="rpp.pe" />
<meta property="og:type" content="<?php if(@$this->model->portada=='home'): ?>website<?php else: ?>article<?php endif;?>">
<meta property="og:url"  content="{{host}}{{model.url_social}}" />
<meta property="og:title"  content="{{model.titulo_social}}" />
<meta property="og:description"  content="<?php echo  htmlentities($this->model->description) ?>" />
<?php if(@$this->model->tipo=='galeria'):?>
<?php $pgaleria = @\Rpp\Services\Get\Content::part($this->model->nid,'galeria')[$this->model->position] ;?>
<meta property="og:image"  content="{{ cdn_image(getPart(model.nid,'contenido')[pgaleria]['foto']['hash'],'normal') }}" />
<?php else:?>
<meta property="og:image"  content="{{model.img_social}}" />
<?php endif;?>
<meta property="og:updated_time" content="{{date('Y-m-d\TH:i:sP',model.fecha_social)}}" />

<!-- fin Open Graph -->