<?php if(!empty($this->model->torneo)): ?>
<div class="menu-mas box">
<button class="hidden"><span class="hamburger">+</span></button>
<ul class="visible-links">
  <li <?php if( $this->model->torneo == 'peru'  ):?>class="active"<?php endif; ?>><a href="{{host}}/futbol-peruano/descentralizado">Copa Movistar</a></li>
  <li <?php if( $this->model->torneo == 'alemania'  ):?>class="active"<?php endif; ?>> <a href="{{host}}/futbol-internacional/bundesliga">Bundesliga</a></li>
  <li <?php if( $this->model->torneo == 'premierleague'  ):?>class="active"<?php endif; ?>><a href="{{host}}/futbol-internacional/premier-league">Premier League</a></li>
  <li <?php if( $this->model->torneo == 'espana'  ):?>class="active"<?php endif; ?>> <a href="{{host}}/futbol-internacional/liga-bbva">Liga BBVA</a></li>
  <li <?php if( $this->model->torneo == 'italia'  ):?>class="active"<?php endif; ?>> <a href="{{host}}/futbol-internacional/serie-a">Serie A</a></li> 
  <li <?php if( $this->model->torneo == 'champions'  ):?>class="active"<?php endif; ?>><a href="{{host}}/futbol-internacional/champions-league">Champions</a></li></ul>
<ul class="hidden-links hidden"></ul>
</div>
<?php endif; ?>