<section id="featured" class="tag-especial noskin group">
<div class="feat-title">
    <h1>{{model.seccion_info.seccion}}</h1>
</div>
{{ partial('partials/portada/bloque/tag/cabecera' , ['slug': model.slug_seccion ] ) }}

<?php $order = @\Rpp\Services\Get\Destacados::portada($this->model->slug_seccion)->tipo['slug'] ;?>
<?php $namespace = @\Rpp\Services\Get\Destacados::portada($this->model->slug_seccion)->tipo['namespace'] ;?>

{{ partial('partials/portada/grilla/seccion/show_' ~ order , [ 'slug':model.slug ,  'ads' : '300x380' , 'namespace' : namespace ] ) }}
<!-- feat-content -->

</section>

{{ partial('partials/portada/bloque/tag/campana_cuerpo' , ['slug': model.slug_seccion ] ) }}

{{ partial('partials/ads/middle1') }}
<!-- pub-980 -->

{{ partial('partials/portada/bloque/tag/medio' , ['slug': model.slug_seccion ] ) }}