<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<script >
    $(document).ready(function () {
        refes_automatico();
        var entra = setInterval('refes_automatico()', 300000);
    });

    function refes_automatico() {
        /*$.ajax({type: 'POST', url: "/envivo/json", cache: false, success: function (html) {
                var actu_re = $(html).text().split('%8%');
                $("#actu_envivoj h2").text(actu_re[0]);
                $("#actu_envivoj p#actu_envivoj_p").text(actu_re[1]);
            }})*/
            var fecha = new Date();
            var d = fecha.getDay();
            var jurl = 'http://s3.amazonaws.com/rpp-static/json/envivo_'+d+'.json';
            $.getJSON(jurl,function(res){
               var fecha = new Date();
               var m = fecha.getMinutes();
               var h  = fecha.getHours();
               if( m < 30 ){
                m  = 1;
               }else{
                 m  = 2;
               }
               var message  = res[h][m];
               console.log(message);
               var message = message.split('%8%');

               console.log(message);

               $("#actu_envivoj h2").text(message[0]);
               $("#actu_envivoj p#actu_envivoj_p").text(message[0]);

             });

    }
</script>
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
    <div>
        <!--Header-->
        {{ partial('partials/header/index') }}
        <div class="wrapper body group">

            <section id="featured" class="envivo group">

                <div class="feat-title">
                    <h1>En Vivo</h1>
                </div>

                {{ partial('envivo/index') }}
                <!-- feat-content -->

                <aside class="sidebar">                
                    {{ partial('partials/sidebar/radioenvivo') }}
                    {{ partial('partials/ads/right') }}
                    {{ partial('partials/ads/right1') }}
                    {{ partial('partials/sidebar/calientes' , ['slug':'home'] , trackurl ) }}
                </aside>

            </section>
            <!-- .featured -->

            {{ partial('partials/ads/middle2') }}
            <!-- pub-980 -->

        </div>
        <!--Footer-->

        {{ partial('partials/footer/index') }}
        <div id="pad-swipe-nav"></div>
        {{ partial('partials/footer/scripts') }}
        {{ partial('partials/footer/tracking') }}
    </div>
</body>
