<!--Head-->
<head>
</head>
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}" style="margin: 0px !important; overflow-y: hidden;">
    {% if(model.player.estado === 0) %}
    <div class="media-player" >
        <img src="{{ehost}}/images/nodisponible.jpg" alt="Transmisión no disponible" title="Transmisión no disponible" style="width: 100%; min-width: 100%; height: 100% !important" >
    </div>
    {% else %}
    <div class="media-player" >
        <div id="{{model.slug}}"></div>
        <script type="text/javascript">
            var file = "{{model.file}}";
            var playlist = '[{% for k,media in model.player.media %}{"file" : "{{media}}"}{% if k < (model.player.media|length - 1) %},{% endif %}{% endfor %}]';
            var rtag = "{{model.preroll}}";
            
            {% if(model.cover !== "") %}
            var cover = "{{ehost}}/{{model.cover}}";
            {% else %}
            var cover = "";
            {% endif %}
        </script>
    </div>
    {% endif %}

</div>
    <script src="{{ehost}}/scripts/jquery-1.11.2.min.js?f={{eversion}}"></script>
    <script src="http://p.jwpcdn.com/player/v/7.0.2/jwplayer.js"></script> 
    <script>jwplayer.key = "L/ARBHy5b4pG1YAD0ou40gMzoAVHnOcJetOEvw==";</script>
    <script src="{{ehost}}/scripts/functions.js?v=22082015"></script>
     <script type="text/javascript">
            setJW7("{{model.slug}}", file, cover, playlist, '{{model.tipop}}', rtag);
    </script>
    {{ partial('partials/footer/comscore') }}
    {{ partial('partials/footer/tracking') }}
   
</body>
