<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body>
<div data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
    <!--Header-->
    {{ partial('partials/header/index') }}
    <div class="wrapper body group">

        <div class="wrap group">

            <div class="feat-title">
                <h1>Horario de Programación Radial</h1>
            </div>


            {{ partial('partials/redes/redes', ['slugne':'/' ~ model.slug]) }}

            <div class="programacion-table">
                <table border="2">
                    <thead>
                    <tr>
                        <th class="blank"></th>
                        <th class="l">Lunes</th>
                        <th class="mv">Martes - Viernes</th>
                        <th class="s">Sábado</th>
                        <th class="d">Domingo</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="start-hour">00:00 - 00:30</td>
                        <td rowspan="8">
                            <h2>RPP Informando</h2>

                            <p>con Carlos Montalvo</p>
                        </td>
                        <td colspan="2" rowspan="4" class="white">
                            <h2>SIEMPRE EN CASA [Repetición]</h2>

                            <p>con Sara Abu-Sabbah</p>
                        </td>
                        <td rowspan="10">
                            <h2>RPP Informando</h2>

                            <p>con Carlos Montalvo</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">00:30 - 01:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">01:00 - 01:30</td>
                    </tr>
                    <tr>
                        <td class="half-hour">01:30 - 02:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">02:00 - 02:30</td>
                        <td colspan="2" rowspan="2" class="white"><h2>ERA TABÚ [Repetición] </h2>

                            <p>con Fernando Maestre & especialistas</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">02:30 - 03:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">03:00 - 03:30</td>
                        <td class="white" colspan="2" rowspan="2">
                            <h3>LOS CHISTOSOS [Repetición]</h3>

                            <p>con Guillermo Rossini, Hernán Vidaurre, Giovanna Castro y Manolo Rojas</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">03:30 - 04:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">04:00 - 04:30</td>
                        <td colspan="2" rowspan="2"><h2>DESPIERTA PERÚ</h2>

                            <p>con Yamil Abusabal</p></td>
                        <td rowspan="2"><h2>DESPIERTA PERÚ </h2>

                            <p>con Carlos Montalvo</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">04:30 - 05:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour"><strong>05:00</strong> - 05:30</td>
                        <td colspan="2" rowspan="6">
                            <h2>ROTATIVA DEL AIRE </h2>

                            <h3>PRIMERA EDICIÓN</h3>

                            <p>con Fernando Carvallo y Ricardo Gómez</p>
                        </td>
                        <td rowspan="6">
                            <h2>ROTATIVA DEL AIRE </h2>

                            <h3>PRIMERA EDICIÓN</h3>

                            <p>con Armando Canchanya</p>
                        </td>
                        <td rowspan="6">
                            <h2>Rotativa del Aire</h2>

                            <h3>Primera Edición</h3>

                            <p>con Fernando Carvallo y Ricardo Gómez</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">05:30 - 06:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">06:00 - 06:30</td>
                    </tr>
                    <tr>
                        <td class="half-hour">06:30 - 07:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">07:00 - 07:30</td>
                    </tr>
                    <tr>
                        <td class="half-hour">07:30 - 08:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour"><strong>08:00</strong> - 08:30</td>
                        <td colspan="2" rowspan="4">
                            <h2>AMPLIACIÓN DE NOTICIAS </h2>

                            <p>con Raúl Vargas, Patricia Del Río y Ricardo Gómez</p>
                        </td>
                        <td rowspan="2">
                            <h3>AMPLIACIÓN DE NOTICIAS </h3>

                            <p>con Raúl Vargas y Armando Canchanya</p>
                        </td>
                        <td rowspan="4">
                            <h3>AMPLIACIÓN DEL DOMINGO </h3>

                            <p>con José María Salcedo, Fernando Carvallo y Ricardo Gómez</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">08:30 - 09:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">09:00 - 09:30</td>
                        <td rowspan="2">
                            <h3>ENFOQUE DE LOS SÁBADOS </h3>

                            <p>con Raúl Vargas</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">09:30 - 10:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">10:00 - 10:30</td>
                        <td class="white" colspan="2" rowspan="6">
                            <h2>SIEMPRE EN CASA </h2>

                            <p>con Sara Abu-Sabbah</p>
                        </td>
                        <td class="white"><h3>DIÁLOGO DE FE </h3>

                            <p>con Cardenal Juan Luis Cipriani y Armando Canchanya</p></td>
                        <td class="white"><h3>DOMINGO ES FIESTA </h3>

                            <p>con Padre Clemente Sobrado y Miguel H. Aguirre</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">10:30 - 11:00</td>
                        <td class="white" rowspan="2">
                            <h3>LA DIVINA COMIDA </h3>

                            <p>con Cucho La Rosa</p>
                        </td>
                        <td class="white" rowspan="1">
                            <h3>Familia Punto Com</h3>
                            <p>con Jesús Veliz</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="start-hour">11:00 - 11:30</td>
                        <td class="white" rowspan="3">
                            <h3>TODO DEPORTE </h3>

                            <p>con Margarita Rivera</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">11:30 - 12:00</td>
                        <td class="white" rowspan="3">
                            <h3>CUIDANDO TU SALUD </h3>

                            <p>con Elmer Huerta</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="start-hour">12:00 - 12:30</td>
                    </tr>
                    <tr>
                        <td class="half-hour">12:30 - 13:00</td>
                        <td class="white" rowspan="4">
                            <h3>EN ESCENA </h3>

                            <p>con Johnny Padilla</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="start-hour"><strong>13:00</strong> - 13:30</td>
                        <td colspan="2" rowspan="3">
                            <h2>ROTATIVA DEL AIRE </h2>

                            <p>con José María Salcedo</p>
                        </td>
                        <td class="white" rowspan="2">
                            <h3>VENTANA ECÓNOMICA </h3>

                            <p>con Guido Sánchez Yabar</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">13:30 - 14:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">14:00 - 14:30</td>
                        <td class="white" rowspan="4">
                            <h3>EN ESCENA </h3>

                            <p>con Johnny Padilla</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">14:30 - 15:00</td>
                        <td class="white" colspan="2" rowspan="4">
                            <h2>LOS CHISTOSOS</h2>

                            <p>con Guillermo Rossini, Hernán Vidaurre, Giovanna Castro y Manolo Rojas</p>
                        </td>
                        <td class="white" rowspan="2">
                            <h3>LETRAS EN EL TIEMPO </h3>

                            <p>con Renato Cisneros</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="start-hour">15:00 - 15:30</td>
                    </tr>
                    <tr>
                        <td class="half-hour">15:30 - 16:00</td>
                        <td class="white" rowspan="3"><h3>LO MEJOR DE LA SEMANA DE LOS CHISTOSOS</h3></td>
                    </tr>
                    <tr>
                        <td class="start-hour">16:00 - 16:30</td>
                        <td class="white" rowspan="4"><h3>DEPORTE AL MÁXIMO </h3>

                            <p>con invitados especiales</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">16:30 - 17:00</td>
                        <td class="white" colspan="2" rowspan="3">
                            <h2>ERA TABÚ </h2>

                            <p>con Fernando Maestre & especialistas</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="start-hour">17:00 - 17:30</td>
                        <td class="white" rowspan="2"><h3>DEPORTE AL MÁXIMO </h3>

                            <p>con Dante Mateo</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">17:30 - 18:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour"><strong>18:00</strong> - 18:30</td>
                        <td colspan="2" rowspan="4">
                            <h2>ROTATIVA DEL AIRE </h2>

                            <p>con Mariella Balbi</p>
                        </td>
                        <td rowspan="2"><h2>LA ROTATIVA DEL AIRE </h2>

                            <p>con Eduardo Lindo</p></td>
                        <td rowspan="2"><h2>LA ROTATIVA DEL AIRE </h2>

                            <p>con Jesús Verde</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">18:30 - 19:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">19:00 - 19:30</td>
                        <td class="white" rowspan="2">
                            <h3>MÁS ALLÁ DE LAS CANAS </h3>

                            <p>con Miguel Humberto Aguirre</p>
                        </td>
                        <td class="white" rowspan="2"><h3>LOS ESPECIALES DEL DOMINGO </h3>

                            <p>con Fernando Carvallo</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">19:30 - 20:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">20:00 - 20:30</td>
                        <td class="white" colspan="2" rowspan="2">
                            <h3>EL SHOW DEL DEPORTE </h3>

                            <p>con Óscar Moral, Dante Mateo y Juan Carlos Hurtado</p>
                        </td>
                        <td class="white" rowspan="2">
                            <h3>PERUANOS EN EL EXTERIOR </h3>

                            <p>con Eduardo Lindo</p>
                        </td>
                        <td class="white" rowspan="2">
                            <h3>LETRAS EN EL TIEMPO [Repetición] </h3>

                            <p>con Renato Cisneros</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">20:30 - 21:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">21:00 - 21:30</td>
                        <td class="white" colspan="2" rowspan="2">
                            <h3>DE FRENTE Y SIN MÁSCARAS </h3>

                            <p>con Carmen Gonzáles</p>
                        </td>
                        <td rowspan="2">
                            <h3>ENFOQUE DE LOS SÁBADOS [Repetición] </h3>

                            <p>con Raúl Vargas</p>
                        </td>
                        <td class="white" rowspan="2">
                            <h3>BUSCAPERSONAS </h3>

                            <p>con Miguel Humberto Aguirre</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">21:30 - 22:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour"><strong>22:00</strong> - 22:30</td>
                        <td colspan="2" rowspan="4">
                            <h2>ROTATIVA DEL AIRE </h2>

                            <p>con José María Salcedo</p>
                        </td>
                        <td class="white" rowspan="4">
                            <h3>EN ESCENA [Repetición] </h3>

                            <p>con Johnny Padilla</p>
                        </td>
                        <td class="white" rowspan="2"><h3>DEPORTE AL MÁXIMO </h3>

                            <p>con Óscar Moral</p></td>
                    </tr>
                    <tr>
                        <td class="half-hour">22:30 - 23:00</td>
                    </tr>
                    <tr>
                        <td class="start-hour">23:00 - 23:30</td>
                        <td class="white" rowspan="2">
                            <h3>LO MEJOR DE EN ESCENA </h3>

                            <p>con Johnny Padilla</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="half-hour">23:30 - 24:00</td>
                    </tr>
                    </tbody>
                </table>
            </div>


        </div>

    </div>
    <!--Footer-->

    {{ partial('partials/footer/index') }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
