<?php if(count($relacionado['items'])>0): ?>
<?php if(count($relacionado['items'])>1): ?>
<div class="related">
	<div class="title">Noticias Relacionadas</div>
	<div class="inner">
		<ul>
		<?php foreach ($relacionado['items'] as  $rel) :?>
		  <li>
	        <h3><a href="/relacionada/permalink/{{rel['nid']}}">{{rel['titulo']}}</a></h3>
	      </li>
		<?php endforeach;?>
		</ul>
	</div>
</div>
<?php else: ?>
<?php foreach ($relacionado['items'] as  $rel) :?>
<div class="related one">
  <figure>
  	<a href="/relacionada/permalink/{{rel['nid']}}" class="cover">
  		<img class="x-lazy" src="{{ehost}}/static/img/placeholder.gif" data-x='{"content":"{{cdn_image( rel['hash'] ,'normal')}}"}'  >
  		{{ partial('partials/nota/detalle/block/relacionado/icono/'  ~ rel['tipo']) }}
  	</a>
  </figure>
  <div class="inner">
    <div class="title">Noticia Relacionada</div>
    <h3><a href="/relacionada/permalink/{{rel['nid']}}">{{rel['titulo']}}</a></h3>
  </div>
</div>
<?php break;?>
<?php endforeach;?>
<?php endif ?>
<?php endif ?>