<?php if(/*@$this->model->tags[0]*/false): ?>
<div class="sidebar-panel" id="more-topic">
<h2 class="panel-title">Más en {{model.tags[0]['nombre']}}</h2>
<?php $e=1; foreach (\Rpp\Services\Get\LFlow::tag($this->model->tags[0]['slug']) as $e => $item): ?>
<?php if(empty( \Rpp\Services\Get\Content::part($item->_id,'_id') )) continue;  ?>
<?php if($this->model->nid == $item->_id) continue;?>
{{ partial('partials/portada/bloque/tag/tag_item', [ 'nid' : item._id , 'class' : 'left-photo' , 'title_h' : 'h3' , 'img_size' : 'small']) }}
<?php if($e >= 3) break;?>
<?php $e++ ; ?>
<?php endforeach; ?>
</div>
<?php endif;?>