                <div class="txt-center">
                  <div class="wancho" data-params='{"variableWidth":true}'>
                    <div class="content">
                      <ul class="inner">
                     <?php if(@\Rpp\Services\Get\Temas::get_temas()):?>   
                     <?php foreach ( \Rpp\Services\Get\Temas::get_temas()->tags as $tema) : ?>         
                      <li class="item"><a href="{{host}}/tema-{{tema['slug']}}?ns_source=self&ns_mchannel=portada.home&ns_campaign=menu.temas" rel="tag">{{tema['nombre']}}</a></li>
                     <?php endforeach;?>
                    <?php endif;?> 
                      </ul>
                      </div>
                      <div class="arrows">
                        <a href="#prev" class="prev">
                            <span>
                                <i class="icon-13"></i>
                            </span>
                        </a>
                        <a href="#next" class="next">
                            <span>
                                <i class="icon-14"></i>
                            </span>
                        </a>
                      </div>
                  </div>
                </div>