<!doctype html>

<html>

  <head>
   
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Swiffy Output</title>
    <script src="{{ehost}}/scripts/swiffy.js?v={{eversion}}"></script>
  </head>

  <body style="margin: 0; overflow: hidden">

    <style>

	html, body {width: 100%; height: 100%}

	

	.envoltorio{

		position: relative;

		width: 300px;

		height: 600px;

	}

	.envoltorio a.link{

		position: absolute;

		top: 0;

		left: 0;

		display: block;

		width: 100%;

		height: 100%;

		z-index: 999999;

	}

	

	.envoltorio > div#swiffycontainer{

		z-index: 0 !important;

		position: absolute;

		top: 0;

		left: 0;

	}


    </style>

	<script type="text/javascript" src="https://www.gstatic.com/swiffy/v7.4/runtime.js"></script>

    <script type="text/javascript" src="object.js"></script>

  <div class="envoltorio">
  	<a class="link" href="http://rpp.pe/concursos.php?c=sueno-de-tu-vida-rpp_304" target="_blank"></a>
    <div id="swiffycontainer" style="width: 300px; height: 600px">

    </div>

  </div>

    <script>

      

      var stage = new swiffy.Stage(document.getElementById('swiffycontainer'),

          swiffyobject, {});

      stage.start();

    </script>

  </body>

</html>

