  <?php $size_brand = !empty(@\Rpp\Services\Get\Content::part($nid,'imagen_branding'));?>
  <?php $size_especial = !empty(@\Rpp\Services\Get\Content::part($nid,'imagen_tag'));?>
<p class="cat" data-size-ancla="<?php echo (int)$size_brand + (int)$size_especial ?>">
  <a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($nid)->categoria['slug']) ;  ?>{{TrackUrl(position)}}">{{getNode(nid).categoria['nombre']}}</a>


<span data-size="<?php echo (int)$size_brand;?>" class="brand-logo-cb"><a href="{{host}}/tema-{{getPart( nid ,'imagen_branding')['slug']}}" ><img src="{{getPart( nid ,'imagen_branding')['url']}}" alt="{{getPart( nid ,'imagen_branding')['nombre']}}"></a></span>

<span data-size="<?php echo (int)$size_especial;?>" data-size-brand="<?php echo (int)$size_brand;?>" class="brand-especial-cb"><a href="{{host}}/tema-{{getPart( nid ,'imagen_tag')['slug']}}" ><img src="{{getPart( nid ,'imagen_tag')['url']}}" alt="{{getPart( nid ,'imagen_tag')['nombre'] }}"></a></span>
  

  <?php $fecha_actual = time();?>
  <?php $fecha_publicacion  = \Rpp\Services\Get\Content::node($nid)->fecha_publicacion  ?>
  <?php if($fecha_publicacion > $fecha_actual) $fecha_publicacion = $fecha_actual; ?>
  <time class="pubdate" datetime="{{date('Y-m-d H:i', fecha_publicacion ) }}">{{date('d/m/y', fecha_publicacion )}}</time>
</p>