<article class=" hnews group">

    <figure class="hmedia">
        <a href="{{nUrl(nid)}}{{TrackUrl(position)}}">
           <span class="icon icon-6"></span>
            <img class="photo lazy" src="{{ehost}}/images/placeholder_rpp.png"  data-src="{{ cdn_image(getNode(nid).imagen_portada['hash'],size) }}" alt="{{getNode(nid).imagen_portada['alt']}}">
        </a>
        <figcaption class="fn hide">{{getNode(nid).titulo_corto}}</figcaption>
    </figure>

    <div class="entry-cont ">
        {{ partial('partials/portada/flujo/box/cat', [ 'nid' : nid ]) }}

        <h2 class="entry-title"><a class="url" href="{{nUrl(nid)}}{{TrackUrl(position)}}" rel="bookmark">{{getNode(nid).titulo_corto}}</a></h2>
        <p>{{getNode(nid).bajada}}</p>


        <footer>
            <div class="entry-actions group">

                <a class="entry-comments" href="#">
                    <span class="icon-7"></span>
                    300 comentarios
                </a>

                {{ partial('partials/portada/flujo/box/social', [ 'nid' : nid ]) }}
                
            </div>
            <p class="hide source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                    Noticias</a></p>
        </footer>

    </div>
    <!-- .entry-cont -->


</article>
