    <ul class="social-icons">
        <li class="fb"><a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'facebook', 'http://rpp.pe{{nUrl(nid)}}' , 'flujo')"><i class="icon-1"></i><span>Facebook</span></a></li>
        <li class="tw"><a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter', '{{host}}/p/{{nid}}', 'flujo')"><i class="icon-5"></i><span>Twitter</span></a></li>
        <li class="wa"><a href="whatsapp://send?text={{getNode(nid).titulo}} {{host}}{{nUrl(nid)}}"><i class="icon-18"></i><span>Whatsapp</span></a></li>
    </ul>