                <a href="#" data-type="s-click" data-idfb="287920207998918" class="lazy comenta bot">&nbsp;</a>
                <section id="coment" class="comment">
                	<h4>COMENTA:</h4>
                     <div id="fb-root" class="fb"></div>
                          <div data-numposts="5" data-colorscheme="light" data-href="{{host}}{{nUrl(model.nid)}}" class="fb-comments"></div><span class="wrapper-icon-circle-o-notch"><i class="icon icon-circle-o-notch fa-spin"></i></span>
                </section>