<div class="box-mod box-row brand-{{tag}}">
	<?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
	<?php if((int)$imgcb==1){ ?>
	<div style="background: url('<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn_raiz(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']) ?>') left top no-repeat;" class="box-header back-image">
	  <h3 class="title"><a href="{{host}}/tema-{{ tag }}">{{nombre}}</a></h3>
	</div>
	<?php } ?>

	<?php $cantle=1; foreach (\Rpp\Services\Get\Flow::tag($tag,$cantidad) as $e => $item):?> 
		{{ partial('partials/portada/bloque/tag/tag_foto_ancho', [ 'nid' : item._id , 'img_size' : 'medium' , 'tag' : tag  ]) }}
	<?php $cantle++; endforeach;?>
</div>
