<section class="social-detail nav-sociales fix-sociales new">
<ul class="item-social-detail">
  <li class="large-social-top func-large"><a href="{{host}}{{nUrl(model.nid)}}{{TrackUrlSocial('facebook',position)}}" class="facebook"><i class="icon icon-facebook"></i><span>comparte</span></a></li>
  <li class="small-social-top func-small"><a href="{{host}}{{nUrl(model.nid)}}{{TrackUrlSocial('twitter',position)}}" class="twitter"><i class="icon icon-twitter"></i></a></li>
  <li class="small-social-top func-small"><a href="{{host}}{{nUrl(model.nid)}}{{TrackUrlSocial('googleplus',position)}}" class="gplus"><i class="icon icon-google-plus"></i></a></li>
  <li class="li-whatsapp small-social-top func-small"><a href="{{host}}{{nUrl(model.nid)}}{{TrackUrlSocial('whatsapp',position)}}" class="whatsapp"><i class="icon icon-whatsapp"></i></a></li>
  <li class="li-icon func-icon"> <a href="" class="plus"><i class="icon icon-plus"></i><i class="icon icon-minus"></i></a></li>
</ul>
</section>
