<div class="media">
<figure itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
  <meta itemprop="width" content="635">
  <meta itemprop="height" content="357">
  <div class="cover">
    {{ partial('partials/nota/contenido/bloque/'~model.package~'imagen',contenido) }}
  </div>
  <figcaption itemprop="description"><?php echo @$contenido['foto']['alt']; ?>
  {% if not(contenido['via'] is empty) %}
  | <strong>Fuente:</strong> {{ contenido['via'] }}
  {% endif %}
  {% if not(contenido['credito'] is empty) %}
  | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
  {% endif %}   
  </figcaption>
</figure>
</div>