<?xml version="1.0"?>
<oidosocial>
    {% for part in socialtv.contenido %}
    <tuit>
        <hashtag>{{socialtv.hashtags}}</hashtag>
        <NombreUsuario>{{part['nombreusuario']}}</NombreUsuario>
        <Cuentausuario>{{part['cuentausuario']}}</Cuentausuario>
        <UrlImagen>{{part['avatar']}}</UrlImagen>
        <Mensaje>{{part['mensaje']}}</Mensaje>
        <fechayhora>{{part['datetime']}}</fechayhora>
    </tuit>
    {% endfor %}
</oidosocial>