<section id="featured" class=" group">
    <div class="feat-content">
        <div class="feat-block group">
        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>
         {{ partial('partials/portada/grilla/block/hentry', [ 'item' : item ]) }}
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
         <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
         <?php break;endforeach;?>
        </div>

        <!-- .feat-block -->
        <div class="feat-block group">
        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?>           
         {{ partial('partials/portada/grilla/block/hentry_group', [ 'item' : item , 'class' : 'second' , 'img_size' : 'medium']) }}
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
        <?php if($position>=2) break; ?>           
        <?php endforeach;?>           
        </div>
        <!-- .feat-block -->
    </div>
    <!-- feat-content -->

    <aside class="feat-sidebar">
        {{ partial('partials/ads/right') }}

        <!-- pub-300 -->
        {{ partial('partials/portada/grilla/block/tag_portada') }}
    </aside>

</section>