<section id="featured" class=" group">
    
    <div class="feat-fin">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>   
     {{ partial('partials/portada/grilla/block/hentry_full', [ 'item' : item ]) }}
    <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
    <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
    <?php break;endforeach;?>
    </div>

    <div class="feat-content">
        <div class="feat-block group">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?> 
         <div class="col-3">            
          {{ partial('partials/portada/grilla/block/hentry_group', [ 'item' : item , 'class' : 'third' , 'img_size' : 'small']) }}
         </div>
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
         <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
        <?php if($position>=2) break; ?>           
        <?php endforeach;?> 


        <div class="col-3">

        <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item): ?>            
          {{ partial('partials/portada/grilla/block/hentry_title', [ 'item' : item , 'class' : 'third']) }}
         <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
        <?php if($position>=4) break; ?>           
        <?php endforeach;?> 

        </div>

        </div><!-- .feat-block -->
    </div><!-- feat-content -->

    <aside class="feat-sidebar">

        {{ partial('partials/ads/right') }}

    </aside>
</section><!-- .featured -->