<section id="featured" class=" group">
	<div class="feat-fin">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>   
     {{ partial('partials/portada/grilla/block/hentry_main', [ 'item' : item ]) }}
    <?php Rpp\Services\Get\Flow::unset_home($item['nid']); ?>
    <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
    <?php break;endforeach;?>
	</div>
</section><!-- .featured -->

