<div class="row box-mod">
    <?php foreach ( @\Rpp\Services\Get\Destacados::portada($slug)->destacadas as $position => $item ): ?>   
     {{ partial('partials/portada/grilla/block/hentry', [ 'item' : item ]) }}
     <?php $unset = 'unset_'.$namespace ;?>
     <?php Rpp\Services\Get\Flow::$unset($slug,$item['nid']); ?>
    <?php Rpp\Services\Get\Destacados::delete($slug,$position); ?>
    <?php break;endforeach;?>
</div>
<!-- .featured -->


    

    