<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:video="http://www.google.com/schemas/sitemap-archivo/1.1">
	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/01?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/02?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/03?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/04?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/05?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/06?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/07?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/08?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/09?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

	<url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/10?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/11?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>

    <url>
		<loc>{{host}}/sitemap/archivos/{{slug}}/{{anio}}/12?ns_source=organico</loc>
		<lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
	</url>
</urlset>
