<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>{{host}}/sitemap/news/politica?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/lima?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/mundo?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/vida-y-estilo?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/viajes?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>


   <sitemap>
      <loc>{{host}}/sitemap/news/gastronomia?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/mascotas?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/tecnologia?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>


   <sitemap>
      <loc>{{host}}/sitemap/news/ciencia?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/virales?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/peru?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/economia?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/futbol?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>


   <sitemap>
      <loc>{{host}}/sitemap/news/voley?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>


   <sitemap>
      <loc>{{host}}/sitemap/news/tenis?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/automovilismo?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/lucha?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/multideportes?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/cultura?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/tv?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>


   <sitemap>
      <loc>{{host}}/sitemap/news/cine?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/musica?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

   <sitemap>
      <loc>{{host}}/sitemap/news/famosos?ns_source=organico</loc>
      <lastmod>{{date('Y-m-d\TH:i:sP')}}</lastmod>
   </sitemap>

</sitemapindex>