<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>               
            <loc>{{host}}/sitemap/{{slug}}/web?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
   <sitemap>               
            <loc>{{host}}/sitemap/{{slug}}/news?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
   <sitemap>               
            <loc>{{host}}/sitemap/{{slug}}/archivos?ns_source=organico</loc>
            <lastmod>{{date('Y-m-d')}}</lastmod>
   </sitemap>
</sitemapindex>