<style type="text/css">body { background: #e3e3e3 url("http://ads.us.e-planning.net/eb/3/15cd9/02994db1f63a8e4d?o=i&rnd=$RANDOM") no-repeat center top fixed } </style>
        		   <div class="wrap_bannerclick">
        		   		    <a class="banner_left" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"> </a>
        		   			<a class="banner_right" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"> </a>
        		   </div>