<?php if(/*@$this->model->tags[0]*/false): ?>
<div class="box-mod box-row ">
  <div class="box-header">
    <h3 class="title">Más en {{model.tags[0]['nombre']}}</h3>    
  </div>
<?php $f=0; foreach (\Rpp\Services\Get\LFlow::tag($this->model->tags[0]['slug']) as $e => $item): ?>
<?php if(empty( \Rpp\Services\Get\Content::part($item->_id,'_id') )) continue;  ?>
<?php if($this->model->nid == $item->_id) continue;?>
{{ partial('partials/portada/bloque/tag/tag_item', [ 'nid' : item._id , 'class' : 'left-photo' , 'title_h' : 'h3' , 'img_size' : 'small']) }}
<?php $f++ ; ?>
<?php if($f >= 3) break;?>
<?php endforeach; ?>
</div>
<?php endif;?>