<?php if(count(Rpp\Services\Get\Recomendados::load($this->model->user))>0): ?>
<div class="box-mod box-row ">
  <div class="box-header">
    <div class="title">Noticias Recomendadas</div>    
  </div>

<?php $e=1; foreach (Rpp\Services\Get\Recomendados::load($this->model->user) as $nid): ?>
<?php if(empty( \Rpp\Services\Get\Content::part($nid,'_id') )) continue;  ?>
<?php if($this->model->nid == $nid) continue;?>
{{ partial('partials/portada/bloque/tag/tag_thumb_nofollow', [ 'nid' : nid , 'class' : 'left-photo' , 'title_h' : 'h3' , 'img_size' : 'small']) }}
<?php if($e >= 4) break;?>
<?php $e++ ; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>