<div class="col-2">
    <?php foreach (\Rpp\Services\Get\Gallery::home(1) as $position => $item) :?>
        <a href="{{nUrl(item._id)}}{{TrackUrl(position)}}" class="holder"><img src="{{cdn_image(getNode(item._id).imagen_portada['hash'],'large')}}" alt="{{getNode(item._id).imagen_portada['alt']}}">
            <div class="count-media big"><span class="icon-gallery"></span><span class="num"><?=count(\Rpp\Services\Get\Content::part($item['_id'],'galeria'));?></span></div></a>
        <!-- .entry-cont -->
        <?php $primeid_foto=$item['_id'];
    endforeach; ?>
</div>
<div class="col-1">
    <div class="box-header">
        <h3 class="title"><a href="{{nUrl(primeid_foto)}}{{TrackUrl(position)}}">{{getNode(primeid_foto).titulo_corto}}</a></h3>
        <p>{{getNode(primeid_foto).bajada}}</p>
    </div>
    <div class="box-body">
        <div class="row-top">
            <div class="info-l"><a href="javascript: void(0);">Más galerías</a></div>
            <!-- <div class="pull-right"><a href="#link">Ver todas</a></div> -->
        </div>

        <?php $countj=0; foreach (\Rpp\Services\Get\Gallery::home(3) as $position => $item) : $countj=$countj+1; ?>
            <?php if($countj>1){ ?>
                <div class="row">
                    <div class="fig"><a href="{{nUrl(item._id)}}{{TrackUrl(position)}}" class="holder"><img src="{{cdn_image(getNode(item._id).imagen_portada['hash'],'small')}}" alt="{{getNode(item._id).imagen_portada['alt']}}">
                            <div class="count-media"><span class="icon-gallery"></span><span class="num"><?=count(\Rpp\Services\Get\Content::part($item['_id'],'galeria'));?></span></div></a></div>
                    <h3><a href="{{nUrl(item._id)}}{{TrackUrl(position)}}">{{getNode(item._id).titulo_corto}}</a></h3>
                </div>
            <?php } ?>
        <?php endforeach; ?>
    </div>
</div>
