<div class="row great">
<?php if(is_array(@\Rpp\Services\Get\Destacados::portada('home')->portadas)):?>
      <div class="columns-4">
      <?php foreach (\Rpp\Services\Get\Destacados::portada('home')->portadas as $position => $portada): ?>
        <div class="cell">
          <div class="box-mod">
            <div class="box-header">
              <div class="title">{{portada['nombre']}}</div>
            </div>
        <?php $slug_portada = str_replace(SITESLUG.'/' , '', $portada['slug'])?> 
        
        <?php if(is_array(@\Rpp\Services\Get\Destacados::portada($slug_portada)->destacadas)):?>
         
          <?php foreach(@\Rpp\Services\Get\Destacados::portada($slug_portada)->destacadas as  $e => $item):?>
           <?php  $gene_img['type']='html';$gene_img['content'] ='<img src="'.\Rpp\Services\Get\UrlMedia::image( $item['imagen_portada']['hash'], 'medium') .'" alt=" '.$item['imagen_portada']['alt'].' ">'; 
          $jsongene_img=json_encode($gene_img, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE);
          ?>
          <figure>
           <a href="{{nUrl(item['nid'])}}" data-x='<?=$jsongene_img;?>' class="cover fig-center x-lazy">
              {{ partial('partials/portada/grilla/block/icon/' ~ item['tipo'] ) }}
           </a>
          </figure>
        <?php break;?>
        <?php endforeach;?>
        
        <div class="box-body">
         <?php foreach (@\Rpp\Services\Get\Destacados::portada($slug_portada)->destacadas as  $e => $item) : ?>
           <div class="row">
              <h3><a href="{{nUrl(item['nid'])}}">{{item['titulo']}}</a></h3>
           </div>
          <?php if($e>=3)break;?>
         <?php endforeach;?>
        </div>
      <?php endif;?>

          </div>
        </div>
   <?php if($position>=3)break;?>
   <?php endforeach;?>

      </div>
  <?php endif;?>
</div>  