<div class="col-secondary sidebar x-sticky"> 
     <div data-x='{"fixto":".col-primary.main"}' class="x-column-fix">
     {{ partial('partials/portada/bloque/tag/lateral_1' , ['slug':'home'] ) }}

     {{ partial('partials/ads/right1') }}
     {{ partial('partials/portada/bloque/tag/lateral_2' , ['slug':'home'] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_3' , ['slug':'home'] ) }}
     <!-- #noticia-360 -->
     {{ partial('partials/ads/swiffy') }}
     {{ partial('partials/ads/right2') }}

     {{ partial('partials/portada/bloque/tag/lateral_4' , ['slug':'home'] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_5' , ['slug':'home'] ) }}

     {{ partial('partials/ads/right3') }}


     {{ partial('partials/portada/bloque/tag/lateral_6' , ['slug':'home'] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_7' , ['slug':'home'] ) }}

     <!-- .dia-sidebar -->
     {{ partial('partials/ads/rightsmall') }}

     {{ partial('partials/portada/bloque/tag/lateral_8' , ['slug':'home'] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_9' , ['slug':'home'] ) }}
     </div>
</div>