<aside role="complementary" class="col-secondary x-sticky">
  <div data-x='{"fixto":".col-primary"}' class="x-column-fix">
     {{ partial('partials/portada/bloque/tag/lateral_1' , ['slug': slug] ) }}
     {{ partial('partials/ads/right1') }}
     {{ partial('partials/ads/perured') }}
     {{ partial('partials/portada/bloque/tag/lateral_2' , ['slug': slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_3' , ['slug': slug] ) }}
     <!-- #noticia-360 -->
     {{ partial('partials/ads/right2') }}

     {{ partial('partials/portada/bloque/tag/lateral_4' , ['slug': slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_5' , ['slug': slug] ) }}

     {{ partial('partials/ads/right3') }}


     {{ partial('partials/portada/bloque/tag/lateral_6' , ['slug': slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_7' , ['slug': slug] ) }}

     <!-- .dia-sidebar -->
     {{ partial('partials/ads/rightsmall') }}
     
     {{ partial('partials/portada/bloque/tag/lateral_8' , ['slug':  slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_9' , ['slug':  slug] ) }}  
     {{ partial('partials/portada/bloque/tag/lateral_10' , ['slug':  slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_11' , ['slug':  slug] ) }}    
     {{ partial('partials/portada/bloque/tag/lateral_12' , ['slug':  slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_13' , ['slug':  slug] ) }}  
     {{ partial('partials/portada/bloque/tag/lateral_14' , ['slug':  slug] ) }}
     {{ partial('partials/portada/bloque/tag/lateral_15' , ['slug':  slug] ) }}  
  </div>
</aside>