<article class="{{class}}-article hnews group">

<figure class="hmedia">
   {{ partial('partials/portada/grilla/block/icon/' ~ item['tipo'] ) }}
   
    <a {{ partial('partials/portada/grilla/block/url/' ~ item['tipo'] , [ 'nid' : item['nid'] ]) }}>
        <img class="photo" src="{{ cdn_image(item['imagen_portada']['hash'], img_size ) }}" alt="{{ item['imagen_portada']['alt'] }}">
    </a>
    <figcaption class="fn hide">{{item['titulo']}}</figcaption>
</figure>

<div class="entry-cont ">

{{ partial('partials/portada/grilla/block/entry-cont/categoria_' ~ getGrilla(slug).tipo['namespace'] , [ 'nombre' : item['categoria']['nombre'] ,'slug' : item['categoria']['slug'] ] ) }}

    <h2 class="entry-title"><a class="url" {{ partial('partials/portada/grilla/block/url/' ~ item['tipo'] , [ 'nid' : item['nid'] ]) }} >{{item['titulo']}}</a></h2>
    <?php $lautor = @$item['autor']?>
    {{ partial('partials/portada/grilla/block/entry-cont/autor_' ~ getGrilla(slug).tipo['namespace'] , [ 'autor' :  lautor , 'slug' : item['categoria']['slug'] ] ) }}

    <footer class="hide">
        <p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
    </footer>

</div>
<!-- .entry-cont -->

</article>



     