<article class="main-article hnews group">

    <figure class="hmedia">

        <a  {{ partial('partials/portada/grilla/block/url/' ~ item['tipo'] , [ 'nid' : item['nid'] ]) }}  >
            
           {{ partial('partials/portada/grilla/block/icon/' ~ item['tipo'] ) }}

            <img class="photo"  src="{{ cdn_image(item['imagen_portada']['hash'],'normal') }}"
                 alt="{{ item['imagen_portada']['alt'] }}">
        </a>
        <figcaption class="fn hide">
        {{item['titulo']}}
        </figcaption>
    </figure>

<div class="entry-cont ">

{{ partial('partials/portada/grilla/block/entry-cont/categoria_' ~ getGrilla(slug).tipo['namespace'] , [ 'nombre' : item['categoria']['nombre'] ,'slug' : item['categoria']['slug'] ] ) }}

<h1 class="entry-title"><a class="url" {{ partial('partials/portada/grilla/block/url/' ~ item['tipo'] , [ 'nid' : item['nid']]) }} >{{item['titulo']}}</a></h1>
<?php $lautor = @$item['autor']?>
{{ partial('partials/portada/grilla/block/entry-cont/autor_' ~ getGrilla(slug).tipo['namespace'] , [ 'autor' :  lautor , 'slug' : item['categoria']['slug'] ] ) }}

<p>{{item['bajada']}}</p>

<footer class="hide">
    <p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
</footer>

</div>
<!-- .entry-cont -->

</article>


