<div class="sidebar-branding content-automatic">
<?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
<a href="{{host}}/tema-{{ tag }}" data-size-title="{{imgcb*1}}" class="title-branding module-automatic" style="background:transparent url('<?php echo @\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51'] ?>') left top no-repeat;">{{nombre}}</a>
 <div>
  <?php foreach (\Rpp\Services\Get\LFlow::tag($tag,$cantidad) as $e => $item) : ?>
   {{ partial('partials/portada/bloque/tag/tag_foto_ancho', [ 'nid' : item._id , 'img_size' : 'medium' , 'tag' : tag  ]) }}
  <?php endforeach;?>
 </div>
</div>