<?php foreach (\Rpp\Services\Get\Flow::tag($tag) as $e => $item):?> 
  <?php if(@\Rpp\Services\Get\Content::node($item->_id)->tipo == 'video'):?>
  	<?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
	<div class="sidebar-panel dia-sidebar content-automatic content-widget">
		 <h2 class="panel-title">
		    <a data-size-title="{{imgcb*1}}" class="module-automatic" style="background:transparent url('<?php echo @\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51'] ?>') left top no-repeat;" href="{{host}}/tema-{{ tag }}"></a>
		    <a data-size-title="{{!imgcb*1}}" class="module-automatic-title" href="{{host}}/tema-{{ tag }}">{{nombre}}</a>
		 </h2>
   <?php foreach ( \Rpp\Services\Get\Content::part($item->_id,'contenido') as $contenido):?>
   	 <?php if($contenido['tipo'] == "video"): ?>
	        <article class=" hnews group">
	            <div id="swfplayer_{{tag}}"></div>

                <script type="text/javascript">setJW7("swfplayer_{{tag}}", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}',"{{contenido['video']['hash']}}","",false);</script>
                <h2><a  rel="bookmark" {{ partial('partials/portada/grilla/block/url/' ~ getNode(item._id).tipo , [ 'nid' : item._id ] ) }}>{{ getNode(item._id).titulo_corto }}</a></h2>
	        	<div class="entry-cont ">
	        		<footer class="hide">
	        			<p class="source-org vcard"><a class="fn url org" href="http://rpp.pe">RPP Noticias</a></p>
	        		</footer>
	        	</div>
	        </article>
	 <?php break;?>
	 <?php elseif ($contenido['tipo'] == "youtube") :?>
            <article class=" hnews group">

                <iframe width="100%" height="169" src="https://www.youtube.com/embed/{{contenido['youtube']['id']}}" frameborder="0" allowfullscreen></iframe>
                <h2><a  rel="bookmark" {{ partial('partials/portada/grilla/block/url/' ~ getNode(item._id).tipo , [ 'nid' : item._id ] ) }}>{{ getNode(item._id).titulo_corto }}</a></h2>
	        	<div class="entry-cont ">
	        		<footer class="hide">
	        			<p class="source-org vcard"><a class="fn url org" href="http://rpp.pe">RPP Noticias</a></p>
	        		</footer>
	        	</div>
	        </article>
     <?php  break;endif;?>
     <?php endforeach ;?>
    </div>
   <?php break;endif;?>
<?php endforeach;?>	