  {% cache "nota.wrap.group." ~ model.nid 604800 %}
  <!-- <div class="entry-content group"> -->
   <div class="group">
        {{ partial('partials/nota/detalle/social') }}
        {{ partial('partials/nota/detalle/socialmobile') }}
        <div class="cont ajust_win">
            {{ partial('partials/nota/detalle/open/' ~ model.package ) }} 
            {{ partial('partials/nota/detalle/block/firma/'~model.package) }}
            {{ partial('partials/nota/detalle/content/'~model.package) }}                            
            <!-- .social-share -->                            
            {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
        </div>
        <!-- .cont -->
    </div>
<?php if(!(@\Rpp\Services\Get\Content::part($this->model->nid,'comentariosfb')===false)) :?>    
    <!-- .entry-content -->
    <div class="news-comments" id="ancla-comments">
        <h2 class="panel-title">¿Qué opinas?</h2>
        <div id="fbCommentPage" class="fb-comments" data-href="{{host}}{{nUrl(model.nid)}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
    </div>
<?php endif;?>
    <!-- .comments -->
   {% endcache %} 