<div class="wrap group">
            <div class="content group">






<header>

 <p class="cat cat-autor-title" data-size-ancla="0">

  <span class="autor-title-inside">Blog</span>
  <a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($this->model->nid)->categoria['slug']) ;  ?>">{{getNode(model.nid).categoria['nombre']}}</a>

  {{ partial('partials/nota/header/pubtime',['fecha_publicacion': getNode(model.nid).fecha_publicacion] )}}
</p>
 {{ partial('partials/nota/header/titulo',['titulo': getNode(model.nid).titulo ]) }}

 {{ partial('partials/nota/header/bajada',['bajada': getNode(model.nid).bajada]) }} 
</header>

<section class="autor-nota autor-content">
<?php $autor = \Rpp\Services\Get\User::get(@\Rpp\Services\Get\Content::part($this->model->nid,'autor')['slug']); ?>

 <?php if(@$autor->foto_blog['w110']):?>
   <figure class="autor-figure">
       <img src="{{ autor.foto_blog['w110'] }}" alt="{{autor.nombre}}">
   </figure>
 <?php endif;?>
  
   <div class="autor-description">
       <h2>{{autor.nombre}}</h2>
       <button
       onclick="if(this.nextElementSibling.className==='autor-open-bio'){this.className='autor-btn-more';this.nextElementSibling.className='';}else{this.className='autor-btn-more autor-btn-minor';this.nextElementSibling.className='autor-open-bio';}"
       class="autor-btn-more autor-btn-minor"
       type="button">BIO</button>
       <p class="autor-open-bio"><?php echo @$autor->autor['biografia'] ;?></p>
       <ul class="autor-social-icons">
   <?php if(!empty($autor->autor['facebook'])):?>
    <li class="autor-fb"><a target="_blank" href="{{autor.autor['facebook']}}" title="Facebook"><i class="icon-1"></i></a></li>
   <?php endif;?>
   <?php if(!empty($autor->autor['twitter'])):?>
    <li class="autor-tw"><a target="_blank" href="{{autor.autor['twitter']}}" title="Twitter"><i class="icon-5"></i></a></li>
   <?php endif;?>
      <li class="autor-rss"><a target="_blank" href="{{host}}/feed<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($this->model->nid)->categoria['slug']) ;  ?>" title="RSS"><i class="icon-rss"></i></a></li> 
       </ul>
   </div>
</section>



<!-- <div class="entry-content group"> -->
<div class="group">
    {{ partial('partials/nota/detalle/social') }}
    {{ partial('partials/nota/detalle/socialmobile') }}
    <div class="cont ajust_win">
        {{ partial('partials/nota/detalle/open/' ~ model.package ) }}
        {{ partial('partials/nota/detalle/block/firma/'~model.package) }} 
        {{ partial('partials/nota/detalle/content/'~model.package) }}                            
        <!-- .social-share -->                            
        {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
    </div>
    <!-- .cont -->
</div>
<?php if(!(@\Rpp\Services\Get\Content::part($this->model->nid,'comentariosfb')===false)) :?>
<!-- .entry-content -->
<div class="news-comments" id="ancla-comments">
    <h2 class="panel-title">¿Qué opinas?</h2>
    <div id="fbCommentPage" class="fb-comments" data-href="{{host}}{{nUrl(model.nid)}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
</div>
<!-- .comments -->
<?php endif;?>




 
               {{ partial('partials/ads/interna_full' , ['position':9]) }}
                <!-- .pub-wrap -->
                {{ partial('partials/nota/sugeridas/index' , [] , trackurl ) }}
                {{ partial('partials/ads/interna_full' , ['position':10]) }}
                <!-- .related-news -->

            </div>
    <!-- .content -->
   {{ partial('partials/nota/sidebar/index') }}  
    <!-- .sidebar -->
</div>