<div class="social-share">
    <h3 class="panel-title">Compartir</h3>
    <ul class="socials">
        <li class="facebook-share">
      <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'facebook', '{{host}}/{{model.slug}}')">
        <i class="icon-1"></i>
      </a>
      <span></span>
    </li>
        <li class="whatsapp-share">
            <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'whatsapp', '')">
        <i class="icon-whatsapp"></i>
      </a>
      <span>234</span>
        </li>
        <li class="twitter-share">
            <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter', '{{host}}/{{model.slug}}')">
        <i class="icon-5"></i>
      </a>
      <span></span>
        </li>
        <li class="google-share">
            <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'googlemas', '{{host}}/{{model.slug}}')">
        <i class="icon icon-google-plus"></i>
      </a>
      <span>0</span>
        </li>
    <li class="linkedin-share">
      <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'linkedin', '{{host}}/{{model.slug}}')">
        <i class="icon icon-linkedin"></i>
      </a>
      <span></span>
    </li>
    <li class="comentar">
      <a href="#ancla-comments">
        <i class="icon icon-11"></i>
        <span>Comentar</span>
      </a>
    </li>
    </ul>
</div>

<div class="social-share-mobile">
    <ul>
        <li class="twitter-share"><a href="javascript: void(0);" class="twitter" onclick="shareSocial(this,url)"><i class="icon-5"></i><span>Twitter</span></a></li>
        <li class="facebook-share"><a href="javascript: void(0);" class="facebook" onclick="shareSocial(this,url)"><i class="icon-1"></i><span>Facebook</span></a></li>
        <li class="google-share"><a href="javascript: void(0);" class="googlemas" onclick="shareSocial(this,url)"><i class="icon-2"></i><span>Google+</span></a></li>
        <li class="pinterest-share"><a href="javascript: void(0);" onclick="shareSocial(this,url)"><i class="icon-26"></i><span>Pinterest</span></a></li>
        <li class="whatsapp-share"><a href="javascript: void(0);" onclick="shareSocial(this,url)"><i class="icon-18"></i><span>Whatsapp</span></a></li>
    </ul>
</div>