<?php foreach (\Rpp\Services\Get\Flow::home(1) as $item) : ?>
                 <article class="flow-prominent">
                    <h1> <a href="/nota/detalle/{{node._id}}">{{node.titulo}}</a></h1>
                    <div class="prominent-media">

                   {% for contenido in node.contenido  %} 
                      <?php if(isset($contenido['tipo'])):?>                     
                      {% if contenido['tipo'] == "text" %}
                       {% if contenido['foto']['url'] %}
                       {% else %}  
                      <figure class="media"><a href="/nota/detalle/{{node._id}}"><img src="{{contenido['foto']['url']}}" alt="{{contenido['foto']['alt']}}s" width="445" height="251"></a></figure>
                       {%break%}
                       {%endif%}
                      {% elseif contenido['tipo'] == "embed" %}                   
                       {{contenido['embed']}} 
                      {%break%}
                      {% elseif contenido['tipo'] == "youtube" %}
                        <p><iframe width="445" height="251" src="https://www.youtube.com/embed/{{contenido['youtube']['id']}}" frameborder="0" allowfullscreen=""></iframe></p>
                        {%break%}
                      {% endif  %}
                      <?php endif; ?>
                    {% endfor %}
                      <div class="prominent-txt"> 
                        <p>
                          {{node.bajada}}
                        </p>
                        <div class="time-related">Publicado el 
                          <time datetime="{{date('Y-m-d H:i',node.fecha_publicacion)}}"> {{date('d/m/y',node.fecha_publicacion)}}  </time>
                        </div>
                      </div>
                    </div>
                  </article>
<?php break; endforeach;?>