<?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
<div class="sidebar-panel dia-sidebar content-automatic">
 <h2 class="panel-title">
    <a data-size-title="{{imgcb*1}}" class="module-automatic" style="background:transparent url('<?php echo @\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51'] ?>') left top no-repeat;" href="{{host}}/tema-{{ tag }}"></a>
    <a data-size-title="{{!imgcb*1}}" class="module-automatic-title" href="{{host}}/tema-{{ tag }}">{{nombre}}</a>
 </h2>
<?php foreach (\Rpp\Services\Get\Flow::tag($tag,$cantidad) as $e => $item):?> 
<article class=" hnews group">
	<figure class="hmedia">
		<a {{ partial('partials/portada/grilla/block/url/' ~ getNode(item._id).tipo , [ 'nid' : item._id ] ) }}>
			
			<img class="photo" src="{{ cdn_image(getNode(item._id).imagen_portada['hash'], 'medium' ) }}" alt="{{ getNode(item._id).imagen_portada['alt'] }}" width="300">
		</a>
		<figcaption class="fn hide">{{ getNode(item._id).titulo_corto }}</figcaption>
	</figure>
	<div class="entry-cont ">
		<footer class="hide">
			<p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
		</footer>
		
	</div><!-- .entry-cont -->
</article>
<?php endforeach;?>
</div>