<header>
<?php $size_brand = !empty(\Rpp\Services\Get\Article::part($this->model->nid,'imagen_branding'));?>
<?php $size_especial = !empty(\Rpp\Services\Get\Article::part($this->model->nid,'imagen_tag'));?>
 <p class="cat" data-size-ancla="<?php echo (int)$size_brand + (int)$size_especial ?>">
  {{ partial('partials/nota/header/categoria' ,[ 'nombre' : gNode(model.nid)['categoria']['nombre'] , 'nid' : model.nid ])}}
  <span data-size="<?php echo (int)$size_brand;?>" class="brand-logo-cb"><a href="{{host}}/tema-{{gPart( model.nid ,'imagen_branding')['slug']}}" ><img  src="{{gPart( model.nid ,'imagen_branding')['url']}}" alt="{{gPart( model.nid ,'imagen_branding')['nombre']}}" /></a></span>
  <span  data-size="<?php echo (int)$size_especial;?>" data-size-brand="<?php echo (int)$size_brand;?>" class="brand-especial-cb">
  <a href="{{host}}/tema-{{gPart( model.nid ,'imagen_tag')['slug']}}" ><img src="{{gPart( model.nid ,'imagen_tag')['url']}}" alt="{{gPart( model.nid ,'imagen_tag')['nombre']}}" /></a></span>

  {{ partial('partials/nota/header/pubtime',[ 'fecha_publicacion': gNode(model.nid)['fecha_publicacion'] ] )}}
</p>
 {{ partial('partials/nota/header/titulo',[ 'titulo': gNode(model.nid)['titulo'] ]) }}

 {{ partial('partials/nota/header/bajada',[ 'bajada': gNode(model.nid)['bajada'] ]) }} 
</header>