<header>
<?php $size_brand = !empty(\Rpp\Services\Get\Content::part($this->model->nid,'imagen_branding'));?>
<?php $size_especial = !empty(\Rpp\Services\Get\Content::part($this->model->nid,'imagen_tag'));?>
 <p class="cat" data-size-ancla="<?php echo (int)$size_brand + (int)$size_especial ?>">
  {{ partial('partials/nota/header/categoria' ,[ 'nombre' : getNode(model.nid).categoria['nombre'] , 'nid' : model.nid ])}}
  <span data-size="<?php echo (int)$size_brand;?>" class="brand-logo-cb"><a href="{{host}}/tema-{{getPart( model.nid ,'imagen_branding')['slug']}}" ><img  src="{{getPart( model.nid ,'imagen_branding')['url']}}" alt="{{getPart( model.nid ,'imagen_branding')['nombre']}}" /></a></span>
  <span  data-size="<?php echo (int)$size_especial;?>" data-size-brand="<?php echo (int)$size_brand;?>" class="brand-especial-cb">
  <a href="{{host}}/tema-{{getPart( model.nid ,'imagen_tag')['slug']}}" ><img src="{{getPart( model.nid ,'imagen_tag')['url']}}" alt="{{getPart( model.nid ,'imagen_tag')['nombre']}}" /></a></span>

  {{ partial('partials/nota/header/pubtime',['fecha_publicacion': getNode(model.nid).fecha_publicacion] )}}
</p>
 {{ partial('partials/nota/header/titulo',['titulo': getNode(model.nid).titulo ]) }}

 {{ partial('partials/nota/header/bajada',['bajada': getNode(model.nid).bajada]) }} 
</header>