<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}

    <div class="wrapper body group">
        <div class="category search wrap group">
            <div class="content group">
             {{ partial('clima/block/header') }}
              

    <div class="weather-map group">

        <div id="mapaPeru"></div>
       {{ partial('clima/block/weather_group') }}
       {{ partial('clima/block/weather_table') }}
    </div>




            </div>
            
            <!-- .content -->
            <aside class="sidebar">
                {{ partial('partials/ads/right') }}
                {{ partial('partials/portada/sidebar/sdb_trafico' , ['tag':''  , 'nombre': ''] ) }}
                {{ partial('partials/ads/right1') }}
                <!-- pub-300 -->                   
                {{ partial('partials/sidebar/recomendados' ,[] , trackurl ) }}
                {{ partial('partials/ads/right2') }}

                {{ partial('partials/sidebar/calientes' , ['slug':'home'] , trackurl ) }}
                {{ partial('partials/ads/right3') }}
            </aside>
            <!-- .sidebar -->
        </div>

         {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

    </div>
    <!-- .wrapper -->
    <!--Footer-->
    {{ partial('partials/footer/index' ,[] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}

<script>
  /* Selector del elemento dentro del cual dibujar el mapa. */
  var MAP_WRAPPER_SEL = '#mapaPeru';

  /* Esta variable decide cual es el departamento o los departamentos que
  aparecen seleccionado en el mapa.  Se usan los nombres de los departamentos
  sin acentos, en minúsculas y con guiones bajos (_) en vez de espacios.

  Valores válidos son los siguientes:

      amazonas, ancash, apurimac, arequipa, ayacucho, cajamarca, cuzco,
      huancavelica, huanuco, ica, junin, la_libertad, lambayeque, lima, loreto,
      madre_de_dios, moquegua, pasco, piura, puno, san_martin, tacna,
      tumbes, ucayali
  */
  var MAP_SELECTED = ['{{model.slug}}'];

  /* Enlaces de las distintas zonas en el mapa.
  Una zona enlazada cambiará el cursor, al pasarlo por encima,
  y te llevará a su dirección al hacerle click.
  */
  var MAP_LINKS = {
    amazonas: '{{host}}/clima/amazonas',
    ancash: '{{host}}/clima/ancash',
    apurimac: '{{host}}/clima/apurimac',
    arequipa: '{{host}}/clima/arequipa',
    ayacucho: '{{host}}/clima/ayacucho',
    cajamarca: '{{host}}/clima/cajamarca',
    cuzco: '{{host}}/clima/cuzco',
    huancavelica: '{{host}}/clima/huancavelica',
    huanuco: '{{host}}/clima/huanuco',
    ica: '{{host}}/clima/ica',
    junin: '{{host}}/clima/junin',
    la_libertad: '{{host}}/clima/la_libertad',
    lambayeque: '{{host}}/clima/lambayeque',
    lima: '{{host}}/clima/lima',
    loreto: '{{host}}/clima/loreto',
    madre_de_dios: '{{host}}/clima/madre_de_dios',
    moquegua: '{{host}}/clima/moquegua',
    pasco: '{{host}}/clima/pasco',
    piura: '{{host}}/clima/piura',
    puno: '{{host}}/clima/puno',
    san_martin: '{{host}}/clima/san_martin',
    tacna: '{{host}}/clima/tacna',
    tumbes: '{{host}}/clima/tumbes',
    ucayali: '{{host}}/clima/ucayali'
  };
</script>
<script src="{{ehost}}/scripts/jquery.jvectormap.js?v=2"></script>
<script src="{{ehost}}/scripts/map-peru.js?v=2"></script>



    {{ partial('partials/footer/tracking') }}
</div>
</body>