<?php $i=0;foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $contenido): ?> 
     {% if contenido['tipo'] == "photo" %}
    <section class="img-news img-principal">                                           
    <figure class="hmedia main-photo"><img class="photo lazy" src="{{ehost}}/images/placeholder_rpp.png"  data-src="{{cdn_image( contenido['foto']['hash'] ,'normal')}}" alt="{{contenido['subtitulo']}}" title="{{contenido['subtitulo']}}">
      <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?>
      <!--    <?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
      <span> <?php // echo @$contenido['credito']; ?> </span>-->
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}      
      </figcaption>
    </figure>
    </section>
     <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "video" %}
       <section class="img-news">
        <div id="swfplayer_open" class="nd_galeriaopen_">   </div>
        <script type="text/javascript">setJW7("swfplayer_open", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}',"{{contenido['video']['hash']}}","{{model.preroll}}");</script>
        <div class="help-media">
      <?php echo @$contenido['video']['descripcion']; ?> 
          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
        <span> <?php // echo @$contenido['credito']; ?> </span>-->
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}
      </div>
       </section>
       <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "youtube" %}
     <section class="img-news">
            <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
            <div class="help-media">
            <?php echo @$contenido['youtube']['descripcion']; ?> 
          <!--<?php // if(!empty($contenido['via'])): ?>| fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->
              {% if not(contenido['via'] is empty) %}
              | <strong>Fuente:</strong> {{ contenido['via'] }}
              {% endif %}
              {% if not(contenido['credito'] is empty) %}
              | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
              {% endif %}
            </div>
     </section>
     <?php if(empty($contenido['youtube']['url_cover'])) : ?>
     <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg", undefined, undefined, "{{model.preroll}}");</script>
     <?php else: ?>
      <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "{{contenido['youtube']['url_cover']}}", undefined, undefined, "{{model.preroll}}");</script>
     <?php endif;?>
     <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>