<div class="gallery-single slider">
	<div id="slider">
	    <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $key => $contenido): ?> 
        	<?php if ($contenido['tipo'] == 'photo') { ?> 
        <figure class="hmedia">
            {{ partial('partials/nota/contenido/bloque/'~model.package~'imagen',contenido) }}
            <figcaption><?php echo @$contenido['foto']['alt']; ?> 
               <!--> | <strong>Fuente:</strong> {{contenido['via']}}  <?php // echo @$contenido['credito']; ?>-->
            {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
            </figcaption>
        </figure>
        	<?php break; } ?>
    	<?php endforeach;?>
        <ul class="gallery-nav">
            
            <li><a class="btn-prev" href="#"><span>Anterior</span></a></li>
           
           
            <li><a class="btn-next" href="#"><span>Siguiente</span></a></li>
            
        </ul>
	</div>

	<div id="carouselnormal" class="flexslider carousel">
		<ul class="slides group">
            <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $key => $contenido): ?> 
        	<?php if ($contenido['tipo'] == 'photo') { ?>
            <li>
                <a href="#"><img src="{{cdn_image( contenido['foto']['hash'] ,'small')}}" alt="{{contenido['foto']['alt']}}"></a>
            </li>
            <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$key);  ?>
           <?php  } ?>
    	<?php endforeach;?>
            
        </ul>
		
	</div>

</div>