<div class="breadcrumb">
  <ul itemscope="" itemtype="http://schema.org/BreadcrumbList">
    <li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"><a itemprop="item" href="{{host}}"><span itemprop="name">Portada</span></a>
      <meta itemprop="position" content="1">
    </li>
    <li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem" class="active"><a itemprop="item" href="/"><span itemprop="name">{{nombre}}</span></a>
      <meta itemprop="position" content="2">
    </li>
  </ul>
</div>