<?php $i=0;foreach ($this->notapreview->contenido as $contenido):?> 
     {% if contenido['tipo'] == "audio" %}
     <?php 
      $gene_img['type']='audio';
      $gene_img['video_source'] =$contenido['audio']['url']; 
      $gene_img['video_img'] =$contenido['audio']['url_cover']; 
      $gene_img['playlist'] ='undefined'; 
      $gene_img['hash'] ='undefined';
      $gene_img['rtag'] = false;
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- audio-->
      <div itemprop="video" itemscope itemtype="http://schema.org/VideoObject" class="media">
        <figure>
            <div class="cover cover-media">
                <a href="#video" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['audio']['descripcion']; ?>"><span class="icon-video"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['audio']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
          </figcaption>
        </figure>
      </div> 
     <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>