<?php $i=0; foreach ($this->notapreview->contenido as $contenido): ?>  
     {% if contenido['tipo'] == "photo" %}

     <!-- foto-->
      <div class="media">
        <figure itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
          <meta itemprop="width" content="635">
          <meta itemprop="height" content="357">
          <div class="cover"><img itemprop="url" content="{{contenido['foto']['data']['data']}}" src="{{contenido['foto']['data']['data']}}" alt="{{contenido['foto']['alt']}}" title="{{contenido['foto']['alt']}}"></div>
          <figcaption itemprop="description"><?php echo @$contenido['foto']['alt']; ?>
          {% if not(contenido['via'] is empty) %}
          | <strong>Fuente:</strong> {{ contenido['via'] }}
          {% endif %}
          {% if not(contenido['credito'] is empty) %}
          | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
          {% endif %}   
          </figcaption>
        </figure>
      </div>

     <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
     {% elseif contenido['tipo'] == "video" %}
       <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] =$contenido['video']['url']; 
      $gene_img['video_img'] =$contenido['video']['url_cover']; 
      if(!isset($contenido['video']['playlist'])){ $contenido['video']['playlist']='[]'; }
      $gene_img['playlist'] =json_encode($contenido['video']['playlist']); 
      $gene_img['hash'] =$contenido['video']['hash'];
      $gene_img['rtag'] =false;
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- video-->
      <div itemprop="video" itemscope itemtype="http://schema.org/VideoObject" itemref="author-name" class="media">
        <meta itemprop="encodingFormat" content="mp4">
        <meta itemprop="uploadDate" content="">
        <meta itemprop="contentUrl" content="<?=$gene_img['video_source'];?>">
        <meta itemprop="duration" content="<?php echo @$contenido['video']['duracion']; ?>">
        <figure>
            <div class="cover cover-media">
                <a href="#escuchar" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img itemprop="thumbnailURL" src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['video']['descripcion']; ?>"><span class="icon-play"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['video']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
        </figcaption>
        </figure>
      </div>
       <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
     {% elseif contenido['tipo'] == "youtube" %}
        <?php 
      $gene_img['type']='video';
      $gene_img['video_source'] ="https://www.youtube.com/watch?v=".$contenido['youtube']['id'];
      if(empty($contenido['youtube']['url_cover'])){
        $gene_img['video_img'] =  "http://img.youtube.com/vi/".$contenido['youtube']['id']."/0.jpg"; 
      } else{
        $gene_img['video_img'] =  $contenido['youtube']['url_cover']; 
      }
      
      $gene_img['playlist'] ='undefined'; 
      $gene_img['hash'] ='undefined';
      $gene_img['rtag'] ='undefined';
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- youtube-->
      <div itemprop="video" itemscope itemtype="http://schema.org/VideoObject" class="media">
        <figure>
            <div class="cover cover-media">
                <a href="#video" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['youtube']['descripcion']; ?>"><span class="icon-video"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['youtube']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
          </figcaption>
        </figure>
      </div> 
     <?php unset($this->notapreview->contenido[$i]) ?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>