<div class="row">
	<div class="box-mod box-header-section">
		<div class="box-header">
			<h1 class="title-mod">Autores</h1>
		</div>
	</div>

	
<?php $order = @\Rpp\Services\Get\Destacados::portada($this->model->slug_seccion)->tipo['slug'] ;?>
<?php $namespace = @\Rpp\Services\Get\Destacados::portada($this->model->slug_seccion)->tipo['namespace'] ;?>


{{ partial('partials/portada/grilla/seccion/show_' ~ order , [ 'slug': 'autores' , 'ads':'300x250x2' , 'namespace' : namespace ] ) }}
<!-- feat-content -->
</div>

{{ partial('partials/ads/middle1') }}
<!-- pub-980 -->