<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}
    <main class="wrapper">
      {{ partial('partials/ads/top2') }}
      {{ partial('partials/widget/resultados') }}
      <section class="body archive body-full">
       <div class="box"> 
          <div class="box-inner">
            <section class="breadcrumb-full">
              <nav class="breadcrumb">
                <ul>
                  <li>
                    <figure class="logo"><a href="#"><img src="{{host}}/img/logo_breadcrumb.png" alt="Logo La10"></a></figure>
                  </li>
                  <li>Fútbol Internacional</li>
                </ul>
              </nav>
            </section>
            <h3 class="title-flow">Archivo</h3>
            <aside class="sidebar">
              <!--Sidebar-->
              <!--Search-->
              <section class="search-flow">
                <div class="search-flow-inner">
                  <form action="#">
                    <input type="text" value="buscar">
                    <button type="button"><i class="icon icon-search"></i></button>
                  </form>
                </div>
              </section>
              <!--CALENDAR-->
              <section class="calendar">
                <div class="box"></div>
              </section>
              <!--FILTER-->
              <section class="filter-date">
                <div class="box">
                  <h3> Filtro cronológico</h3>
                  <nav>
                    <ul>
                      <li class="active"><a href="#">Últimas 12 horas</a></li>
                      <li><a href="#">Últimas 24 horas</a></li>
                      <li><a href="#">Última semana</a></li>
                      <li><a href="#">Último mes</a></li>
                    </ul>
                  </nav>
                </div>
              </section>
            </aside>
          </div>
       </div>
      </section>


    </main>  
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
    </div>
  </body>