<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
{{ partial('partials/resultados_electorales/congreso/style') }}
<script type="text/javascript">
  stage_file = '{{model.s3_raiz}}';
</script>
<style type="text/css">
  body,  #content>.grid.pad.submenujchs{background: #ebebeb;}
  .wrap-especial .box-header{margin-bottom: 0px;}
</style>
<body data-bg="{{model.epl_kvs}}"  data-x="slide, lazy, media, sticky"  data-x="lazy, columns-fit, sticky, media, column-fix, social-native">
    <div id="wrap">
    {{ partial('partials/header/indextag_1'  ) }}
    <div id="content" role="main">
        {{ partial('partials/ads/top') }}
        <div class="grid pad submenujchs">
          {{ partial('tag/cabecera/cb_resultados_flash' , ['portada':'congreso'] ) }}
          <div class="story">



<div id="cont_jp" class="congresoprejp">
  <h2 class="titujp1a">RESULTADOS CONGRESO 2016</h2>
    <header class="menuprinjp">
      <nav >
          <!--<a href="javascript:;" onclick="initjps2('ONPE');" class="activemjp">ONPE</a>
            <a href="javascript:;" onclick="initjps2('IPSOS');">IPSOS</a>
            <a href="javascript:;" onclick="initjps2('CPI');">CPI</a>
            <a href="javascript:;" onclick="initjps2('GFK');">GFK</a>
            <a href="javascript:;" onclick="initjps2('DATUM');">DATUM</a>-->
        </nav>
        <div class="florrcabejp"><div>AL <span class="florrcabejp_a"></span>%</div></div>
    </header>
  <div class="parte1jp">

      <div class="titujp1">POR BANCADA</div>
        <div class="titujp4">130<span>ESCAÑOS</span>
        </div>
      <div id="containerjp" ></div>
      <div id="leyendjp" ></div>

    </div>
    <div class="limpia"></div>
    <div class="parte23jp">
      <div class="palo1jp"></div>
        <div class="parte2jp">
          <div class="fondoblajp"></div>
            <div class="popparpolijp">fgfdgf</div>
          <div class="titujp1">POR PARTIDO POLÍTICO</div>
            <div class="cont_part2jp">

            </div>
        </div>
        <div class="parte3jp">
          <div class="titujp1">POR REGIÓN</div>

            <div id="mapa">
              <div id="mapa-peru"></div>
            </div>

        </div>
        <div class="limpia"></div>
    </div>
    <div class="col-share">
        <div class="social-share" id="share-options">
          <div class="inside">
            <ul id="share-options">
              <li class="fb-share">
                  <!-- <span class="count">153</span> -->
                  <a href="https://www.facebook.com/sharer/sharer.php?u=http://rpp.pe/elecciones-peru-2016/resultados-congreso&amp;t=Resultados Elecciones 2016: revisa aquí el flash electoral al Congreso" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
                <span class="icon-facebook"></span>
                </a>
              </li>
              <li class="wa-share">
                <a href="whatsapp://send?text=Resultados Elecciones 2016: revisa aquí el flash electoral al Congreso http://rpp.pe/elecciones-peru-2016/resultados-congreso">
                <span class="icon-whatsapp"></span>
                </a>
              </li>
              <li class="tw-share">
                <a href="https://twitter.com/intent/tweet?original_referer=http://rpp.pe/elecciones-peru-2016/resultados-congreso&amp;text=Resultados Elecciones 2016: revisa aquí el flash electoral al Congreso&amp;url=http://rpp.pe/elecciones-peru-2016/resultados-congreso&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
                <span class="icon-twitter"></span>
                </a>
              </li>
              <li class="gp-share">
                <a href="https://plus.google.com/share?url=http://rpp.pe/elecciones-peru-2016/resultados-congreso" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
                <span class="icon-google-plus"></span>
                </a>
              </li>
              <li class="in-share">
                <a href="https://www.linkedin.com/shareArticle?url=http://rpp.pe/elecciones-peru-2016/resultados-congreso&amp;title=Resultados Elecciones 2016: revisa aquí el flash electoral al Congreso&amp;summary=Los resultados de las Elecciones Congresales 2016 serán anticipados con los flash electorales." onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
                <span class="icon-linkedin"></span>
                </a>
              </li>
            </ul>
          </div>
          <div class="on-share">
            <a href="#compartir" onclick="fn(this, event, {&quot;method&quot;:&quot;toggleClass&quot;, &quot;to&quot;: &quot;#share-options&quot;})">
              <span class="icon-forward-share"></span>
            </a>
          </div>
        </div>
      </div>
</div>


            <br><br>


          </div>
        </div>
      </div>
      {{ partial('partials/footer/index') }}
        {{ partial('partials/footer/scripts') }}
        <script type="text/javascript">
          url_path = '{{host}}/elecciones-peru-2016/resultados-congreso';
        </script>
        {{ partial('partials/resultados_electorales/congreso/script') }}
        {{ partial('partials/footer/tracking') }}

</div>

</body>
