<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}
<script src="/elecciones-peru-2016/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/votaperu.css?v={{ehost}}">
<script type="text/javascript">
  stage_file = '{{model.s3_raiz}}';
</script>
<style type="text/css">
  body,  #content>.grid.pad.submenujchs{background: #ebebeb;}
  .wrap-especial .box-header{margin-bottom: 0px;}
</style>
<body data-bg="{{model.epl_kvs}}"  data-x="slide, lazy, media, sticky" class="terminos" >
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
    <div id="wrap">
        <!--Header-->
        {{ partial('partials/header/index') }}
        <div id="content" role="main">
        <div class="grid pad submenujchs">
          {{ partial('tag/cabecera/cb_resultados_flash' , ['portada':'andino'] ) }} 
          <div class="story">
           
    <section class="contenedor-pa">
        <style>
            .pa-desktop { display: block; width: 100%; text-align: center; }
            .pa-mobile { display: none; }
            .pa-desktop img, 
            .pa-mobile img { width: 100%; display: inline-block; text-align: center; }
            @media (max-width: 480px){
                .pa-desktop {display: none; }
                .pa-mobile { display: block; }
            }
        </style>
        <div class="pa-desktop">
            
        </div>
        <div class="pa-mobile">
            
        </div>
        <script>
        var url_host = "{{model.s3_raiz}}";
        try {
            url_host = stage_file;
        }
        catch(err) {
            url_host = "{{model.s3_raiz}}";
        }
        $(function(){
            
            var request = $.ajax({
                url: url_host+"elecciones/parlamento-andino.json",
                method: "GET",
                dataType: "json"
            });

            request.done(function( result ) {
                console.log(result, 'rrr');
                var data = result.data;
                $('.pa-desktop').append("<img src='"+data.imgdesktop+"' alt='Parlamento Andino'>");
                $('.pa-mobile').append("<img src='"+data.imgmobile+"' alt='Parlamento Andino'>");
            });

            request.fail(function( jqXHR, textStatus ) {
                console.log( "Request failed: " + textStatus );
            });

        });
        </script>
    </section>



          </div>
      </div>
      </div>

    <!--Footer-->
      {{ partial('partials/footer/index') }}
      {{ partial('partials/footer/scripts') }}
      <script type="text/javascript">
          url_path = '{{host}}/elecciones-peru-2016/resultados-parlamento-andino';
      </script>
      {{ partial('partials/resultados_electorales/presidenciales/script') }}
      {{ partial('partials/footer/tracking') }}
</div>

</body>