<script src="{{ehost}}/elecciones-peru-2016/js/highcharts.js?v={{eversion}}"></script>
<script src="{{ehost}}/elecciones-peru-2016/js/exportingsrc.js?v={{eversion}}"></script>
<script src="{{ehost}}/elecciones-peru-2016/js/jqvmap2.js?v={{eversion}}"></script>
<script src="{{ehost}}/elecciones-peru-2016/js/jvectormapperu.js?v={{eversion}}"></script>
<script src="{{ehost}}/elecciones-peru-2016/js/srcijp.js?v={{eversion}}"></script>