<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}
<body data-bg="{{model.epl_kvs}}"  data-x="slide, lazy, media, sticky" class="radio-live" >
  {{ partial('partials/head/epl') }}
  {{ partial('partials/head/comscore') }}
    <div id="wrap">
        <!--Header-->
        {{ partial('partials/header/index') }}
        <div id="content" role="main">
        <div class="grid pad">

<link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/elecciones-restructured.css?v={{eversion}}">

<div class="box-mod wrap-especial in-content" id="menu-votaperu">
    <div class="box-header">
        <h3 class="title">
            <a href="{{host}}/elecciones-peru-2016">
                <span class="hide">Elecciones Perú 2016</span>
                <img src="{{host}}/elecciones-peru-2016/img/logo_header.gif" alt="Elecciones Perú 2016">
            </a>
            <button
                class="especial-btn"
                type="button"
                onclick='fn(this, event, {"method":"toggleClass", "to": "#menu-votaperu"})'>
                <span class="icon-chevron-down"></span>
            </button>
        </h3>
        <figure class="pull-right">
            <ul class="nav">
                <li ><a href="{{host}}/elecciones-peru-2016">noticias</a></li>
                <li ><a href="{{host}}/elecciones-peru-2016/candidatos.html">candidatos</a></li>
                <li ><a href="{{host}}/elecciones-peru-2016/redes">en redes</a></li>
                <li class="active" ><a href="{{host}}/elecciones-peru-2016/encuesta" >encuestas</a></li>
                <li ><a href="http://rpp.pe/politica/congreso/elecciones-peru-2016-estos-son-los-candidatos-al-congreso-noticia-940142">lista congreso</a></li>
                <li><a href="{{host}}/elecciones-peru-2016/comparaya.html">Compara Ya</a></li>
                <li><a href="{{host}}/elecciones-peru-2016/gps-electoral.html">GPS Electoral</a></li>
            </ul>
        </figure>
    </div>
</div>


 
<div class="story">
            <div class="col-primary">
              <div class="flow-row">
                <div class="row">
<div id="fb-root"></div>
                    <script>(function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0];
                      if (d.getElementById(id)) return;
                      js = d.createElement(s); js.id = id;
                      js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.5";
                      fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                    <link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/debate.css?v={{eversion}}">
                    <div class="debate-box" id="debate-resultados">
                        <div class="debate-box-top">
                            <div class="breadcrumb">
                              <ul>
                                <li>
                                    <a>
                                        <span>Debate</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="this">
                                        <span>Resultados</span>
                                    </a>
                                </li>
                              </ul>
                            </div>
                            <div class="vp-share-perfil">
                                  <div class="vp-fb-boton">
                                      <div class="fb-like" data-href="{{host}}/elecciones-peru-2016/debate/resultados" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                                  </div>
                                  <div class="vp-tw-boton">
                                      <a href="https://twitter.com/share" class="twitter-share-button" {count} data-via="rppnoticias">Tweet</a>
                                      <script>
                                          ! function(d, s, id) {
                                              var js, fjs = d.getElementsByTagName(s)[0],
                                                  p = /^http:/.test(d.location) ? 'http' : 'https';
                                              if (!d.getElementById(id)) {
                                                  js = d.createElement(s);
                                                  js.id = id;
                                                  js.src = p + '://platform.twitter.com/widgets.js';
                                                  fjs.parentNode.insertBefore(js, fjs);
                                              }
                                          }(document, 'script', 'twitter-wjs');

                                      </script>
                                  </div>

                            </div>
                        </div>
                        <div class="debate-candidatos">
                        <?php $e=1; foreach (\Rpp\Services\Get\Candidatos::listado() as $slug => $candidato): ?>                      
                          <div class="debate-candidato">
                            <div class="candidato-datos">
                              <div class="posicion">{{e}}</div>
                              <div class="img-candidato {{slug}}"></div>
                              <div class="el-candidato">
                                <div class="nombre-candidato">{{candidato['nombre_corto']}}</div>
                                  <div class="partido-candidato">{{candidato['partido']}}</div>
                              </div>
                            </div>
                            <?php //var_dump($this->redis->get("elecciones:debate:votaciones:$slug:like"),$this->redis->get("elecciones:debate:votaciones:$slug:dislike"))?>
                            <?php $like = $this->redis->get("elecciones:debate:votaciones:$slug:like");?>
                            <?php if(empty($like)) $like = 0;?>
                            <?php $dislike = $this->redis->get("elecciones:debate:votaciones:$slug:dislike");?>
                            <?php if(empty($dislike)) $dislike = 0;?>
                            <?php $total = $like+$dislike;?>
                            <?php if($total<=0): ?>
                            <?php $like_porcentaje = 0;?>
                            <?php $dislike_porcentaje =0; ?>
                            <?php else:?>
                              <?php $like_porcentaje = round(100*$like/$total);?>
                              <?php $dislike_porcentaje = 100 - $like_porcentaje;?>
                            <?php endif;?>

                            <div class="candidato-resultados">
                              <div class="candidato-likes candidato-like">
                                <div class="likes-mini is-like-mini"></div>
                                <div class="percent-like">
                                  <span>Me gusta</span>
                                 <!-- <span class="icon-up"></span> -->
                                  <div class="number">{{like_porcentaje}}%</div>
                                  <div class="votes">{{like}} votos</div>
                                </div>
                              </div>
                              <div class="line"></div>
                              <div class="candidato-likes candidato-dislike">
                                <div class="likes-mini is-dislike-mini"></div>
                                <div class="percent-dislike">
                                  <span>No me gusta</span>
                                  <!-- <span class="icon-up"></span> -->
                                  <div class="number">{{dislike_porcentaje}}%</div>
                                  <div class="votes">{{dislike}} votos</div>
                                </div>
                              </div>
                            </div>
                          </div>
                    <?php $e++;?>
                    <?php endforeach;?>

                        </div>
                        <div class="debate-box-bottom">
                        </div>
                    </div>
                    <!-- debate -->
                </div>
              </div>
            </div>
           <aside class="col-secondary sidebar x-sticky">
           {{ partial('partials/ads/right') }}
              <div class="box-mod box-row">
                <div class="title-box-rr">¿Qué opinas?</div>
                <div id="fb-root" class="fb"></div>
                <div data-numposts="5" data-colorscheme="light" data-width="100%" data-href="{{host}}/elecciones-peru-2016/debate/resultados" class="fb-comments"></div><span class="wrapper-icon-circle-o-notch"><i class="icon icon-circle-o-notch fa-spin"></i></span>
       
              </div>
            </aside>
          </div>

          </div>
        </div>
        {{ partial('partials/footer/index') }}
        {{ partial('partials/footer/scripts') }}
        <script type="text/javascript" src="{{ehost}}/elecciones-peru-2016/debate.js?v={{eversion}}"></script>
        {{ partial('partials/footer/tracking') }}

</div>

</body>


     