<div class="content group">
    {{ partial('partials/portada/bloque/tag/cronologico_1' , ['slug':'home'] ) }}
    <!-- .especial -->

    <div class="especial group ttl-new cajaarequipa-new">
        <h1>
            Lo Último
        </h1>
        <figure class="figure_ttl-new">
            <a href="http://ads.us.e-planning.net/ei/3/17632/Home/Ultimas?it=i&rnd=$RANDOM" target="_blank"><img src="http://ads.us.e-planning.net/eb/3/17632/Home/Ultimas?o=i&rnd=$RANDOM
" alt="Logo Caja Arequipa" /></a>
        </figure>
    </div>


    {{ partial('partials/portada/flujo/home' , [] , trackurl) }}
    
    <div class="more-news">
        <a class="btn" href="/archivo">Ver más noticias</a>
    </div>
</div>
