{% cache "portada.bodyopen.home"  604800 %}
{{ partial('partials/portada/bloque/tag/cabecera' , ['slug':'home'] ) }}
{{ partial('partials/portada/grilla/index', ['slug':'home'] , trackurl ) }}
{{ partial('partials/portada/bloque/tag/campana_cuerpo' , ['slug':'home'] ) }}
<!-- .featured -->
{{ partial('partials/ads/middle1') }}
<!-- pub-980 -->
{{ partial('partials/portada/bloque/tag/medio' , ['slug':'home'] ) }}
{% endcache %} 