<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}

<!-- Css Hora del planeta Desktop -->
<link rel="stylesheet" type="text/css" href="{{host}}/hora-planeta/css/hp.css">

<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}" id="{{model.hora_planeta}}">

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=185239485185";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div id="contenedor_div">
    <!--Header-->

    {{ partial('partials/header/indexportada') }}

    <div class="wrapper body group">

        {{ partial('index/body_open' ~ model.no_view_cache_open ) }}

        <div class="wrap group">

           {{ partial('index/body_central' ~ model.no_view_cache_central ) }}

            <!-- .content -->
            {{ partial('partials/portada/bloque/sidebar_home') }}
            <!-- .sidebar -->
        </div>

       {{ partial('partials/ads/middle2') }}

      {{ partial('index/body_close' ~ model.no_view_cache_close ) }}

    </div>
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "http://rpp.pe",
    "name":"RPP NOTICIAS",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "http://rpp.pe/buscar?q={search_term}",
      "query-input": "required name=search_term"
     }
   }
  </script>
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    
<!-- Js Hora del planeta Desktop -->

<script type="text/javascript">
<?php $time = date('F j, Y G:i:s')?>
var count = 0;
var now = new Date("{{time}}");
var deadline = new Date("March 19, 2016 20:30:00");

function getTimeRemaining(endtime) {
  count++;
  var t = Date.parse(endtime) - (Date.parse(now) + 1000*count);
  var seconds = Math.floor((t / 1000) % 60);
  var minutes = Math.floor((t / 1000 / 60) % 60);
  var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
  var days = Math.floor(t / (1000 * 60 * 60 * 24));
  return {
    'total': t,
    'days': days,
    'hours': hours,
    'minutes': minutes,
    'seconds': seconds
  };
}

(function initializeClock(_class, endtime) {
  var clock = document.querySelectorAll(_class);
  var daysSpanD = clock[0].querySelector('.days');
  var hoursSpanD = clock[0].querySelector('.hours');
  var minutesSpanD = clock[0].querySelector('.minutes');
  var secondsSpanD = clock[0].querySelector('.seconds');

  var daysSpanM = clock[1].querySelector('.days');
  var hoursSpanM = clock[1].querySelector('.hours');
  var minutesSpanM = clock[1].querySelector('.minutes');
  var secondsSpanM = clock[1].querySelector('.seconds');

  function updateClock() {
    var t = getTimeRemaining(endtime);
    daysSpanD.innerHTML = ('0' + t.days).slice(-2);
    hoursSpanD.innerHTML = ('0' + t.hours).slice(-2);
    minutesSpanD.innerHTML = ('0' + t.minutes).slice(-2);
    secondsSpanD.innerHTML = ('0' + t.seconds).slice(-2);

    daysSpanM.innerHTML = ('0' + t.days).slice(-2);
    hoursSpanM.innerHTML = ('0' + t.hours).slice(-2);
    minutesSpanM.innerHTML = ('0' + t.minutes).slice(-2);
    secondsSpanM.innerHTML = ('0' + t.seconds).slice(-2);
    console.log(t.total);
    if (t.total == 0) {
      clearInterval(timeinterval);
      document.getElementById('hora-planeta-d').style.display = 'none';
      document.getElementById('hora-planeta-d').style.display = 'none';
      location.reload();
    } else if ( t.total < 0 )
    {
      document.getElementById('hora-planeta-d').style.display = 'none';
      document.getElementById('hora-planeta-d').style.display = 'none';
    }
  }
  updateClock();
  var timeinterval = setInterval(updateClock, 1000);
})('.clock-hp', deadline);
    </script>
   
    {{ partial('partials/footer/tracking') }}
    
</div>
</body>
