<?php $position = 1 ;foreach (\Rpp\Services\Get\Flow::autor() as $item) : ?>
      <article class=" hnews group">
        <figure class="hmedia">
          
          <a href="{{nUrl(item._id)}}">          
            
            <img class="photo" src="{{ cdn_image(getNode(item._id).imagen_portada['hash'],'small') }}" alt="{{getNode(item._id).imagen_portada['alt']}}">
          </a>
          <figcaption class="fn hide">{{getNode(item._id).imagen_portada['alt']}}</figcaption>
        </figure>
        
        <div class="entry-cont ">
          <p class="cat">
           <time class="pubdate" datetime="{{date('Y-m-d H:i',getNode(item._id).fecha_publicacion)}}"><?php echo utf8_encode(ucfirst(strftime('%e.%b.%y',  strtotime(date("Y-m-d")) )) );?> </time>
          </p>
          <h2 class="entry-title"><a class="url" href="{{nUrl(item._id)}}{{TrackUrl(position)}}" rel="bookmark">{{getNode(item._id).titulo_corto}}</a></h2>

          
          <div class="author vcard group">
            <img class="photo" src="{{getPart(item._id,'autor')['foto']}}" alt="{{getPart(item._id,'autor')['nombre']}}">
            <p>Escrito por:</p>

            <a class="fn url" href="{{host}}<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($item->_id)->categoria['slug']) ;  ?>">{{getPart(item._id,'autor')['nombre']}}</a>
          </div>      
          <p>{{getNode(item._id).bajada}}</p>

          
          <footer>
            <div class="entry-actions group">
              
              <a class="entry-comments" href="#">
                <span class="icon-7"></span>
                300 comentarios
              </a>
              
              <ul class="social-icons">
                <li class="fb"><a href="#"><i class="icon-1"></i><span>Facebook</span></a></li>
                <li class="tw"><a href="#"><i class="icon-5"></i><span>Twitter</span></a></li>
                <li class="wa"><a href="#"><i class="icon-18"></i><span>Whatsapp</span></a></li>
              </ul>
            </div>
            <p class="hide source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP Noticias</a></p>
          </footer>
          
        </div><!-- .entry-cont -->
      </article>   
    <?php $position++;?>
<?php endforeach;?>