<?php $blog_list = \Rpp\Services\Get\Flow::seccion($slug,50);?> 

<?php $imp=0;$e=1;$ads =1 ; $left = 1 ; $ads_left = array() ;?>

<div id="col-1" class="cont-col">
<?php foreach ($blog_list as $offset =>  $item) : ?>
  <?php if(empty(\Rpp\Services\Get\Content::part($item->_id,'_id' ))) continue; ?>
  <?php if ($e%2!=0) :  ?>
       
       <?php if($e%5==0): ?>
       {{partial('partials/ads/interna', [ 'position': ads ])}}
        <?php ++$ads; ?>
       <?php endif;?>

       {{partial('partials/portada/flujo/box/full',['nid':item._id, 'position': e, 'size' : 'medium'])}}
        <?php unset($blog_list[$offset]) ;?>

   <?php else:?>
       <?php if($e%5==0): ?>
          <?php $ads_left[$left] = $ads;?>
          <?php ++$ads; ?>

     <?php endif;?>
    <?php $left ++;?>
   <?php endif;?>

<?php $e++;?>
<?php endforeach;?>
</div>

<div id="col-2" class="cont-col">
<?php $e=1; foreach ($blog_list as $offset =>  $item) : ?>
  <?php if(empty(\Rpp\Services\Get\Content::part($item->_id,'_id' ))) continue; ?>
    <?php  if(array_key_exists($e,$ads_left)): ?>
    {{partial('partials/ads/interna', [ 'position': ads_left[e] ])}}
    <?php endif;?>

    {{partial('partials/portada/flujo/box/full',['nid':item._id, 'position': e , 'size':'medium'])}}
   
<?php $e++;?>
<?php endforeach;?>
</div>