
<?php $e=1;$ads =1 ; $left = 1 ; $ads_left = array() ;?>
<div id="col-1" class="cont-col">
<?php foreach (\Rpp\Services\Get\Flow::home(50) as $item) : ?>
  <?php if ($e%2!=0) :  ?>
	     <?php if($e%5==0): ?>
		   {{partial('partials/ads/interna', [ 'position': ads ])}}
	    	<?php ++$ads; ?>
	     <?php else:?>
       <!-- <?php echo $item->_id ?> -->
    	 {{partial('partials/portada/flujo/box/'~getNode(item._id).tipo,['nid':item._id, 'position': e, 'size' : 'medium'])}}
         <?php \Rpp\Services\Get\Flow::unset_home($item->_id) ;?>
         <?php endif;?>
   <?php else:?>
       <?php if($e%5==0): ?>
          <?php $ads_left[$left] = $ads;?>
          <?php ++$ads; ?>
	   <?php endif;?>
	 <?php $left ++;?>
   <?php endif;?>
<?php $e++;?>
<?php endforeach;?>
</div>

<div id="col-2" class="cont-col">
<?php $e=1; foreach (\Rpp\Services\Get\Flow::home($left) as  $item) : ?>
	 <?php	if(array_key_exists($e,$ads_left)): ?>
		{{partial('partials/ads/interna', [ 'position': ads_left[e] ])}}
     <?php else:?>
      <!-- <?php echo $item->_id ?> -->
     	{{partial('partials/portada/flujo/box/'~getNode(item._id).tipo,['nid':item._id, 'position': e , 'size':'medium'])}}
	 <?php endif;?>
<?php $e++;?>
<?php endforeach;?>
</div>