<link rel="stylesheet" type="text/css" href="{{host}}/elecciones-peru-2016/css/vp-styles.css?v=0.2">
<link rel="stylesheet" type="text/css" href="{{host}}/elecciones-peru-2016/css/vp-mediaq.css?v=0.2">

<!--  <div class="vp-header">
      <h1 class="vp-logo"><a href="/elecciones-peru-2016"><span>Vota Perú</span></a></h1>
      <div class="vp-show-items-resp">
       <a href="#"></a>
      </div>
      <ul class="vp-nav">
        <li><a href="/elecciones-peru-2016" class="vp-noticias">noticias</a></li>
        <li><a href="/elecciones-peru-2016/candidatos.html" class="vp-candidatos">candidatos</a></li>
        <li><a href="/elecciones-peru-2016/redes" class="vp-redes">en redes</a></li>
        <li><a href="/elecciones-peru-2016/encuesta" class="vp-encuestas active">encuestas</a></li>
        <li><a href="/elecciones-peru-2016/comparaya.html" class="vp-comparaya">Compara Ya</a></li>
      </ul>

      <div class="vp-social"></div>
  </div>  -->


    <header class="especial-header wrapper clearfix">
        <h1 class="especial-logo">
           <a href="/elecciones-peru-2016">
                <span class="hide">Elecciones Perú 2016</span>
                <img src="{{host}}/elecciones-peru-2016/img/logo_header.gif" alt="Elecciones Perú 2016" />
            </a>
            <button
                data-icon="w"
                class="especial-btn-rwd"
                type="button"
                onclick="if(this.parentElement.nextElementSibling.className==='especial-nav especial-nav-open'){ this.parentElement.nextElementSibling.className = 'especial-nav'; this.className='especial-btn-rwd'; }else{ this.parentElement.nextElementSibling.className = 'especial-nav especial-nav-open'; this.className='especial-btn-rwd especial-btn-rwd-close'; }"
              ></button>
        </h1>
        <ul class="especial-nav">
            <li ><a href="{{host}}/elecciones-peru-2016">noticias</a></li>
            <li ><a href="{{host}}/elecciones-peru-2016/candidatos.html">candidatos</a></li>
            <li ><a href="{{host}}/elecciones-peru-2016/redes">en redes</a></li>
            <li class="active" ><a href="{{host}}/elecciones-peru-2016/encuesta">encuestas</a></li>
            <li ><a href="http://rpp.pe/politica/congreso/elecciones-peru-2016-estos-son-los-candidatos-al-congreso-noticia-940142">lista congreso</a></li>
            <li><a href="{{host}}/elecciones-peru-2016/comparaya.html">Compara Ya</a></li>
            <li><a href="{{host}}/elecciones-peru-2016/gps-electoral.html">GPS Electoral</a></li>
        </ul>
    </header>


<div class="body-rs"> 
    <div class="vp-breadcrumb">
            <div class="vp-share-perfil" >

                    <div class="vp-fb-boton">
                        <div class="fb-like" data-href="http://rpp.pe/elecciones-peru-2016/encuesta" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
                    </div>

                <div class="vp-tw-boton">
                    <a href="https://twitter.com/share" class="twitter-share-button"{count} data-via="rppnoticias">Tweet</a> 
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </div>


    
            </div>
    </div>
</div>



   


<script>
$(document).ready(function(){
    $("div.vp-show-items-resp").click(function(){
        $("ul.vp-nav").toggle();
    });
});
</script>