<link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/elecciones.css?v={{eversion}}">

  <!-- <div class="vp-header">
      <h1 class="vp-logo"><a href="/elecciones-peru-2016"><span>Vota Perú</span></a></h1>
      <div class="vp-show-items-resp">
       <a href="#"></a>
      </div>
      <ul class="vp-nav">
       <li><a href="/elecciones-peru-2016" class="vp-noticias <?php if(@$portada == 'home'):?> active <?php endif;?>">noticias</a></li>
       <li><a href="/elecciones-peru-2016/candidatos.html" class="vp-candidatos">candidatos</a></li>
       <li><a href="/elecciones-peru-2016/redes" class="vp-redes <?php if(@$portada == 'redes'):?> active <?php endif;?>">en redes</a></li>
       <li><a href="/elecciones-peru-2016/encuesta" class="vp-encuestas">encuestas</a></li>
       <li><a href="/elecciones-peru-2016/comparaya.html" class="vp-comparaya">Compara Ya</a></li>
      </ul>

      <div class="vp-social"></div>
  </div>  -->


    <!-- header -->
    <header class="especial-header wrapper clearfix">
        <h1 class="especial-logo">
            <a href="{{host}}/elecciones-peru-2016">
                <span class="hide">Elecciones Perú 2016</span>
                <img src="{{ehost}}/elecciones-peru-2016/img/logo_header.gif" alt="Elecciones Perú 2016" />
            </a>
            <button
                data-icon="w"
                class="especial-btn-rwd"
                type="button"
                onclick="if(this.parentElement.nextElementSibling.className==='especial-nav especial-nav-open'){ this.parentElement.nextElementSibling.className = 'especial-nav'; this.className='especial-btn-rwd'; }else{ this.parentElement.nextElementSibling.className = 'especial-nav especial-nav-open'; this.className='especial-btn-rwd especial-btn-rwd-close'; }"
              ></button>
        </h1>
        <ul class="especial-nav">
            <li <?php if(@$portada == 'home'):?> class="active" <?php endif;?> ><a href="{{host}}/elecciones-peru-2016">noticias</a></li>
            <li ><a href="{{host}}/elecciones-peru-2016/candidatos.html">candidatos</a></li>
            <li <?php if(@$portada == 'redes'):?> class="active" <?php endif;?>><a href="{{host}}/elecciones-peru-2016/redes">en redes</a></li>
            <li><a href="{{host}}/elecciones-peru-2016/encuesta">encuestas</a></li>
            <li ><a href="http://rpp.pe/politica/congreso/elecciones-peru-2016-estos-son-los-candidatos-al-congreso-noticia-940142">lista congreso</a></li>
            <li><a href="{{host}}/elecciones-peru-2016/comparaya.html">Compara Ya</a></li>
            <li><a href="{{host}}/elecciones-peru-2016/gps-electoral.html">GPS Electoral</a></li>
        </ul>
    </header>

    <!-- /header -->


<?php if(@$portada != 'redes'):?>
<!-- <section id="vp-encuestas-img">
    <figure>
        <img data-desktop="true" src="{{host}}/images/elecciones2016-encuesta.jpg" alt="Encuesta Elecciones 2016" />
        <img data-mobile="false" src="{{host}}/images/elecciones2016-encuesta-mobile.jpg" alt="Encuesta Elecciones 2016" />
    </figure>
</section> -->

{{ partial('votaperu/elecciones_sondeo' ) }}
<?php endif;?>

<!-- <script>
$(document).ready(function(){
    $("div.vp-show-items-resp").click(function(){
        $("ul.vp-nav").toggle();
    });
});
</script> -->


    <script type="text/javascript">
        //EFFECT COUNT
        function porcentAnimate(id, start, end, duration, decimal) {
            var obj = id;
            var range = end - start;
            var minTimer = 50;
            var stepTime = Math.abs(Math.floor(duration / range));
            stepTime = Math.max(stepTime, minTimer);
            var startTime = new Date().getTime();
            var endTime = startTime + duration;
            var timer;
            function run() {
                var now = new Date().getTime();
                var remaining = Math.max((endTime - now) / duration, 0);
                var value = Math.round(end - (remaining * range));
                obj.innerHTML = value;
                if (value == end) {
                    if(decimal){ obj.innerHTML = Number(value) + Number(decimal); }
                    clearInterval(timer);
                }
            }
            var timer = setInterval(run, stepTime);
            run();
        };
        var query = '.e-count';
        var attr = 'data-count';
        var obj = document.querySelectorAll(query);
        for (var i = 0; i < obj.length; i++) {
            var _obj = obj[i];
            var end = _obj.getAttribute(attr);
            var endInteger = parseInt(end);
            var decimal = (end % 1).toFixed(1);
            var _decimal = (decimal && decimal != 0.0)?decimal:false;
            porcentAnimate(_obj, 0, endInteger, 2000, _decimal);
        }
    </script>