<?php $imgcabecera = @$this->model->tag_info->personalidad['sitios'][0]['tag_especial']['url_1020x65']  ?>
<?php if($imgcabecera):?> 
<div class="feat-title feat-automatic">
  <h1 style="background:transparent url('{{imgcabecera}}') left top no-repeat; height:140px;">{{model.tag_info.nombre}}</h1>
</div>

<?php else:?>
    <div class="feat-title {{model.slug}}">
        <h1>{{model.tag_info.nombre}}</h1>
    </div>
<?php endif;?>