<?php $i=0;foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $contenido): ?> 
     {% if contenido['tipo'] == "audio" %}
     <?php 
      $gene_img['type']='audio';
      $gene_img['video_source'] = \Rpp\Services\Get\UrlMedia::replace_cdn_raiz($contenido['audio']['url']);  
      $gene_img['video_img'] = \Rpp\Services\Get\UrlMedia::replace_cdn_raiz($contenido['audio']['url_cover']); 
      if(!isset($contenido['audio']['playlist'])) $contenido['audio']['playlist']='[]';
      else $contenido['video']['playlist'] = \Rpp\Services\Get\UrlMedia::replace_cdn($contenido['audio']['playlist'],'media');
      $gene_img['playlist'] =json_encode($contenido['audio']['playlist']);  
      $gene_img['hash'] ='undefined';
      $gene_img['rtag'] = @$this->model->preroll;
      $gene_img['section'] = @$this->model->epl_sec;
      $gene_img['vtemas'] = @$this->model->epl_kvs;      
    $jsongene_img=json_encode($gene_img);
      ?>
     <!-- audio-->
      <div itemprop="audio" itemscope itemtype="http://schema.org/AudioObject" class="media">
      <meta itemprop="encodingFormat" content="mp3">
      <meta itemprop="contentUrl" content="<?=$contenido['audio']['url'];?>">
        <figure>
            <div class="cover cover-media">
                <a href="#escuchar" data-x='<?=$jsongene_img;?>' class="x-media big">
                    <img itemprop="url" content="<?=$gene_img['video_img'];?>" src="<?=$gene_img['video_img'];?>" alt="<?php echo @$contenido['audio']['descripcion']; ?>"><span class="icon-audio"></span>
                </a>
            </div>
          <figcaption itemprop="description">
            <?php echo @$contenido['audio']['descripcion']; ?> {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}
          </figcaption>
        </figure>
      </div> 
     <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>
