<?php \Rpp\Services\Get\Content::part($this->model->nid,'contenido') ?>
<?php $cant_j=0; foreach (\Rpp\Services\Get\Content::part($this->model->nid,'galeria') as $v => $key) :?>
	<?php if($cant_j==0){ ?>
	<div class="media" style="display:none;">
        <figure itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
          <meta itemprop="width" content="635">
          <meta itemprop="height" content="357">
          <div class="cover"><img itemprop="url" src="{{ehost}}/static/img/placeholder.gif" content="{{ cdn_image(getPart(model.nid,'contenido')[key]['foto']['hash'],'large') }}" ></div>
          <figcaption  itemprop="caption description"><?php echo @$contenido['foto']['alt']; ?>
          {% if not(contenido['via'] is empty) %}
          | <strong>Fuente:</strong> {{ contenido['via'] }}
          {% endif %}
          {% if not(contenido['credito'] is empty) %}
          | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
          {% endif %}   
          </figcaption>
        </figure>
      </div>
      <?php } ?>
<?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$key); $cant_j=$cant_j+1;  ?>
<?php endforeach;?>
