<!-- slide-->
<div class="media">
    <div data-x='{"lazy":true}' itemscope itemtype="http://schema.org/ImageGallery" class="x-slide">
      <meta itemprop="creator" content="radio rpp">
      <meta itemprop="datePublished" content="<?=date(DATE_ATOM,\Rpp\Services\Get\Content::node($this->model->nid)->fecha_publicacion);?>">
      <div class="x-wrapper">
        <div class="x-container">
        <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $key => $contenido): ?> 
            <?php if ($contenido['tipo'] == 'photo') { ?>
            <div class="x-item">
                <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject" class="cover">
                  <img src="{{cdn_image( contenido['foto']['hash'] ,'normal')}}" alt="{{contenido['foto']['alt']}}">
                  <figcaption itemprop="description">{{contenido['foto']['alt']}}</figcaption>
                </figure>
            </div>
            <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$key);  ?>
           <?php  } ?>
        <?php endforeach;?>
        </div>
      </div>
      <div class="x-arrows"><a href="#prev" class="x-prev"><span class="icon-chevron-left icon-prev"></span></a><a href="#next" class="x-next"><span class="icon-chevron-right icon-next"></span></a></div>
    </div>
</div>