<!--Head-->
{{ partial('partials/head/index') }}

<script>
   (function() {
     var cx = '015342578124197715322:pwgaaemzyje';
     var gcse = document.createElement('script');
     gcse.type = 'text/javascript';
     gcse.async = true;
     gcse.src = (document.location.protocol == 'https:' ? 'https:' : 
'http:') +
         '//cse.google.com/cse.js?cx=' + cx;
     var s = document.getElementsByTagName('script')[0];
     s.parentNode.insertBefore(gcse, s);
   })();
</script>
<div style="display:none;">
<gcse:search></gcse:search>
</div>
<body data-bg="{{model.epl_kvs}}" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}

    <div class="wrapper body group">
        <div class="category search wrap group">
            <div class="content group">

                <div class="feat-title">
                    {% if model.response is empty %}
                  {% set result = 'empty' %}
                {%else%}
                   {% set result = '' %}
                <h1>Alrededor de <strong>{{model.response.numFound}} resultados</strong> con <span class='search-text'>'<?php echo urldecode($this->model->search_text); ?>'</span></h1>
                {% endif %}
                    
                </div>

                {% if model.response is empty %}
                  {% set result = 'empty' %}
                {%elseif model.response.numFound>=1 %}
                {{ partial('partials/redes/redes', ['slugne':'/' ~ model.slug]) }}
                <!-- .redes -->
                {% endif %} 
                <!-- .social-share -->
                {% if model.response is empty %}
                  {% set result = 'empty' %}
                {%elseif model.response.numFound==0 %}
                   
                   <div class="noresult">
                    <p>Te recomendamos iniciar una nueva búsqueda</p>
                    <form class="search" id="search-content" action="/buscar" method="post">
                      <input type="text" placeholder="BUSCAR" name="texto">
                      <button><span class="icon-9"></span> Buscar</button>
                    </form>
                  </div>
                
                {% endif %}
                {{ partial('buscar/result' ~ result , ['response':model.response] , trackurl) }}

            </div>
            <!-- .content -->
            <aside class="sidebar">
                
                {{ partial('partials/ads/right') }}
                {{  partial('partials/portada/grilla/block/tag_portada' , ['slug':'home'])  }}
                {{ partial('partials/ads/right1') }}
                {{ partial('partials/sidebar/clima') }}
                {{ partial('partials/ads/right2') }}
                {{ partial('partials/sidebar/calientes' , ['slug':'home'] , trackurl ) }}
                {{ partial('partials/ads/right3') }}                

            </aside>
            <!-- .sidebar -->
        </div>

         {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

    </div>
    <!-- .wrapper -->
    <!--Footer-->
    {{ partial('partials/footer/index' ,[] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>