<?php \Rpp\Services\Get\UrlTrack::$ns_source = 'rpp'; ?>

<div id="footer" role="contentinfo">
<div class="footer-brands">
  <div class="grid">
    <div class="copy"><img class="logo-footer" src="{{ehost}}/static/img/rpp-min.svg?v=21" alt="RPP Noticias" width="48" height="48"> <span class="copyright">Copyright © 2016</span></div>
    <ul>
      <li>Visita también:</li>
      <li><a  href="http://www.capital.com.pe/{{TrackUrl()}}" target="_blank"
               title="Radio Capital" {{model.htmlrel}}>Capital</a></li>
        <li><a  href="http://www.la10.pe/{{TrackUrl()}}" target="_blank"
               title="Radio La10" {{model.htmlrel}}>La10</a></li>
        <li><a  href="http://www.studio92.com/{{TrackUrl()}}" target="_blank"
               title="Radio Studio 92" {{model.htmlrel}}>Studio 92</a></li>
        <li><a  href="http://www.oxigeno.com.pe/{{TrackUrl()}}" target="_blank"
               title="Radio Oxigeno" {{model.htmlrel}}>Oxigeno</a></li>
        <li><a  href="http://www.lazona.com.pe/{{TrackUrl()}}" target="_blank"
               title="Radio La Zona" {{model.htmlrel}}>La Zona</a></li>
        
        <li><a  href="http://www.radiocorazon.com.pe/{{TrackUrl()}}" target="_blank"
               title="Radio Corazón 94.3" {{model.htmlrel}}>Corazón</a></li>
        <li><a  href="http://www.felicidad.com.pe/{{TrackUrl()}}" target="_blank"
               title="Radio Felicidad" {{model.htmlrel}}>Felicidad</a></li>
        
      
    </ul>
  </div>
</div>
<div class="footer-corp">
  <div class="grid">
    <div class="info">
      <ul>
        <li><a href="http://contactenos.gruporpp.com.pe/" target="_blank" {{model.htmlrel}}>Contáctenos</a></li>
            <li><a href="/legal" {{model.htmlrel}}>Aviso legal</a></li>
            <li><a href="mailto:publicidadweb@gruporpp.com.pe"  {{model.htmlrel}}>Anuncie aquí</a></li>
            <li><a href="http://snrtv.org.pe/codigo.php"  target="_blank" {{model.htmlrel}}>Código de ética</a></li>
            <li><a href="http://snrtv.org.pe/solucion.php"  target="_blank" {{model.htmlrel}}>Solución de quejas SNRTV</a></li>
            <li><a href="javascript:;" {{model.htmlrel}}>Mapa del sitio</a></li>
      </ul>
      <ul>
        <li class="grupo-rpp"><a href="#link" target="_blank" class="grupo-rpp" {{model.htmlrel}}>Grupo RPP  </a></li>
        <li>Auditado por: <a  target="_blank" href="http://www.comscore.com/esl/" {{model.htmlrel}}>Comscore</a></li>
            <li>Asociado a: <a  target="_blank" href="http://www.iabperu.com/" {{model.htmlrel}}>IAB Perú</a></li>
            <li>Licenciado por: <a  target="_blank" href="http://www.apdayc.org.pe/" {{model.htmlrel}}>APDAYC</a></li>
      </ul>
    </div>
  </div>
</div>
</div>