<script src="{{ehost}}/static/js/lib/libs.js?v={{eversion}}"></script>
<script src="{{ehost}}/static/js/rpp-app.js?v={{eversion}}" id="js-main"></script>
<script src="{{ehost}}/static/js/lib/podcast.js?v={{eversion}}"></script>
<script type="text/javascript">
  stage_file = '{{model.s3_raiz}}';
</script>
<script src="{{ehost}}/static/js/lib/flash-widget.js?v={{eversion}}"></script>


{{ partial('partials/footer/comscore') }}
