<script type="text/javascript">
   var nhost = '<?php echo TRACKINGNODE_HOST; ?>';
    var urlTrack = '<?php echo TRACKING_HOST ?>/?site=<?php echo SITESLUG ?>&cokkie_user=<?php echo $this->model->user?><?php if(isset($this->model->nid)) echo "&nid=".$this->model->nid?><?php if(!empty($this->model->ref)) echo "&ref=". implode(":",$this->model->ref)  ?><?php if(isset($this->model->portada)) echo "&portada=".$this->model->portada?><?php if(isset($this->model->tema)) echo "&tema=".$this->model->tema ?><?php if(isset($this->model->search_text)) echo "&search=".$this->model->search_text ?>' ;
  (function() {
    var owntrck = document.createElement('script'); 
	owntrck.setAttribute("id", "trackJS");

    owntrck.type = 'text/javascript'; owntrck.async = true;
    owntrck.src = urlTrack ;
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(owntrck, s);
  })();
</script>
<div class="x-lazy" data-x='{"type":"ads","position":"Intersticial"}'></div>