<?php header('Content-type: text/xml');?>
<?xml version="1.0" encoding="UTF-8"?>
<music>
	<song>
		<id>1</id>
		<title>Radio RPP Noticias.</title>
		<slogan>Te informa primero</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/rppx72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/frpp.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamRPPRD</stream_url>
		<web_url>http://www.rpp.com.pe</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>2</id>
		<title>Radio Capital.</title>
		<slogan>Tu opinión importa</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/capitalx72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/fcapital.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamCAPRD</stream_url>	
		<web_url>http://www.capital.com.pe</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>3</id>
		<title>Radio Studio92.</title>
		<slogan>La música que viene</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/studiox72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/fstudio92.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamST9RD</stream_url>	
		<web_url>http://www.studio92.com</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>4</id>
		<title>Radio Oxigeno.</title>
		<slogan>Llena tu vida de rock</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/oxigenox72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/foxigeno.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamOXIRD</stream_url>	
		<web_url>http://www.oxigeno.com.pe</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>6</id>
		<title>Radio La Zona.</title>
		<slogan>Nadie toca más música</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/lazonax72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/flazona.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamLZORD</stream_url>	
		<web_url>http://lazona.com.pe</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>7</id>
		<title>Radio Felicidad.</title>
		<slogan>Me siento bien</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/felicidadx72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/ffelicidad.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamFELRD</stream_url>	
		<web_url>http://www.felicidad.com.pe/</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
	<song>
		<id>8</id>
		<title>Radio Corazon.</title>
		<slogan>Más musica, más amor</slogan>		
		<thumb_url>http://s3.amazonaws.com/rpp-static/stream/img/corazonx72.png</thumb_url>
		<bg_url>http://s3.amazonaws.com/rpp-static/stream/img/fcorazon.jpg</bg_url>
		<stream_url>rtsp://streaming.gruporpp.net:1935/rpp02live-live/streamCORRD</stream_url>	
		<web_url>http://www.radiocorazon.com.pe/</web_url>
		<eplimg_url>http://ads.us.e-planning.net/eb/3/a118/005eabb5cc019a71?o=i&amp;m=1&amp;rnd=$RANDOM</eplimg_url>
		<epllink_url>http://ads.us.e-planning.net/ei/3/a118/005eabb5cc019a71?it=i&amp;m=1&amp;rnd=$RANDOM</epllink_url>	
	</song>
</music>
