  <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'contenido') as $contenido): ?>                                
    {% if contenido['tipo'] == "text" %}
     <p> {{contenido['texto']}} </p>
    {% elseif contenido['tipo'] == "photo" %}   
    <figure class="media full">
    <p> {{contenido['subtitulo']}} </p>
    {{ partial('partials/nota/contenido/bloque/'~model.package~'imagen',contenido) }}
    
    <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?>
        <!--  <?php // if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php // endif;?>
      <span> <?php // echo @$contenido['credito']; ?> </span>-->      
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}         
      </figcaption>
    </figure>
    {% elseif contenido['tipo'] == "embed" %}
     <p> {{contenido['subtitulo']}} </p>
     <p> {{contenido['embed']}} <div>Credito: {{contenido['credito']}} | Via: {{contenido['via']}}</div></p>
     <p> {{contenido['texto']}} </p>
    {% elseif contenido['tipo'] == "youtube" %}
    <p> {{contenido['subtitulo']}} </p>
<p><section class="img-news">
    <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
    <div class="help-media">
     <!-- <?php // echo @$contenido['youtube']['alt']; ?>
          <?php // if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php // endif;?>
      <span> <?php // echo @$contenido['credito']; ?> </span>-->      
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}      
      </div>
</section></p>
<script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg", undefined, undefined, "{{model.preroll}}");</script>
<div>Credito: {{contenido['credito']}} | Via: {{contenido['via']}}</div>
{% elseif contenido['tipo'] == "video" %}
<p> {{contenido['subtitulo']}} </p>
<p>         <section class="img-news"><div id="swfplayer" class="nd_galeriaopen_"></div>
            <div class="help-media">
            <?php echo @$contenido['video']['alt']; ?>
            <!--<?php // if(!empty($contenido['via'])): ?>| Fuente : {{contenido['via']}}<?php // endif;?>
            <span> <?php // echo @$contenido['credito']; ?> </span>-->            
            {% if not(contenido['via'] is empty) %}
            | <strong>Fuente:</strong> {{ contenido['via'] }}
            {% endif %}
            {% if not(contenido['credito'] is empty) %}
            | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
            {% endif %}             
            </div>
          </section>
</p>

<script type="text/javascript">setJW7("swfplayer", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}',"{{contenido['video']['hash']}}", "{{model.preroll}}");</script>
<div>Credito: {{contenido['credito']}} | Via: {{contenido['via']}}</div>
{% endif  %}
<?php endforeach;?>
