<div class="social-share">
    <h3 class="panel-title">Compartir</h3>
    <ul class="socials">
        <li class="facebook-share">
      <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'facebook', 'http://rpp.pe{{nUrl(model.nid)}}')">
        <i class="icon-1"></i>
      </a>
      <span></span>
    </li>
        <li class="whatsapp-share">
            <a href="whatsapp://send?text={{getNode(model.nid).titulo}} {{host}}{{nUrl(model.nid)}}">
            <i class="icon-whatsapp"></i>
            </a>
      <span>234</span>
        </li>
        <li class="twitter-share">
            <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter', '{{host}}/p/{{model.nid}}')">
        <i class="icon-5"></i>
      </a>
      <span></span>
        </li>
        <li class="google-share">
            <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'googlemas', '{{host}}{{nUrl(model.nid)}}')">
        <i class="icon icon-google-plus"></i>
      </a>
      <span>0</span>
        </li>
    <li class="linkedin-share">
      <a href="javascript: void(0);" onclick="rpp.shareSocial(this, 'linkedin', '{{host}}{{nUrl(model.nid)}}')">
        <i class="icon icon-linkedin"></i>
      </a>
      <span></span>
    </li>
    <li class="comentar">
      <a href="#ancla-comments">
        <i class="icon icon-11"></i>
        <span>Comentar</span>
      </a>
    </li>
    </ul>
</div>