<div class="social-share-mobile">
    <ul>
        <li class="twitter-share"><a href="javascript: void(0);" class="twitter" onclick="shareSocial(this,url)"><i class="icon-5"></i><span>Twitter</span></a></li>
        <li class="facebook-share"><a href="javascript: void(0);" class="facebook" onclick="shareSocial(this,url)"><i class="icon-1"></i><span>Facebook</span></a></li>
        <li class="google-share"><a href="javascript: void(0);" class="googlemas" onclick="shareSocial(this,url)"><i class="icon-2"></i><span>Google+</span></a></li>
        <li class="pinterest-share"><a href="javascript: void(0);" onclick="shareSocial(this,url)"><i class="icon-26"></i><span>Pinterest</span></a></li>
        <li class="whatsapp-share"><a href="whatsapp://send?text={{getNode(model.nid).titulo}} {{host}}{{nUrl(model.nid)}}" ><i class="icon-18"></i><span>Whatsapp</span></a></li>
    </ul>
</div>