<?php $galerias = array(); ?>
<?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'galeria') as $v => $key) :?>
<?php $item['src']=  \Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['foto']['hash'], 'large');?>
<?php $item['caption']= \Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['foto']['alt'] ;?>
<?php if(!empty(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['via'])) $item['caption'] .= ' | Fuente: '.\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['via']?>
<?php if(!empty(\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['credito'])) $item['caption'] .= ' | Fotógrafo: '.\Rpp\Services\Get\Content::part($this->model->nid,'contenido')[$key]['credito']?>	
<?php $galerias[]=$item; ?>
<?php endforeach;?>
<div class="media widen " itemref="article-body organization" >
  <div  data-x='{"comscore" : "{{model.comscore}}", "ads":"Right", "page": <?=$this->model->position;?> , "urlState":"{{host}}{{nUrl(model.nid)}}", "title": "<?=urlencode(\Rpp\Services\Get\Content::node($this->model->nid)->titulo);?>","urlVisor":"{{host}}{{nUrl(model.nid)}}-full-screen"}' data-sources='<?=json_encode($galerias,JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE)?>' itemscope itemtype="http://schema.org/ImageGallery" class="x-gallery x-gallery-large">
</div>