<div class="media widen">
  <div data-x='{"lazy":true,"urlState":"{{host}}{{nUrl(model.nid)}}"}' itemscope itemtype="http://schema.org/ImageGallery" class="x-slide">
    <meta itemprop="creator" content="<?=date(DATE_ATOM,\Rpp\Services\Get\Content::node($this->model->nid)->fecha_publicacion);?>">
    <meta itemprop="datePublished" content="<?=date(DATE_ATOM,\Rpp\Services\Get\Content::node($this->model->nid)->fecha_publicacion);?>">
    <div class="x-wrapper">
      <div class="x-container">
        <?php foreach (\Rpp\Services\Get\Content::part($this->model->nid,'galeria') as $v => $key) :?>
        <div class="x-item">
          <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject" class="cover shadow-type-1">
            <img data-src="{{ cdn_image(getPart(model.nid,'contenido')[key]['foto']['hash'],'large') }}" alt="{{ getPart(model.nid,'contenido')[key]['foto']['alt'] }}">
            <figcaption itemprop="caption description">{{ getPart(model.nid,'contenido')[key]['foto']['alt'] }} 
                {% if not(getPart(model.nid,'contenido')[key]['via'] is empty) %}
                | Fuente: {{ getPart(model.nid,'contenido')[key]['via'] }}
                {% endif %}
                {% if not(getPart(model.nid,'contenido')[key]['credito'] is empty) %}
                | Fotógrafo: {{ getPart(model.nid,'contenido')[key]['credito'] }}            
                {% endif %}</figcaption>
          </figure>
        </div>
        <?php \Rpp\Services\Get\Content::unset_part($this->model->nid,'contenido',$key);  ?>
        <?php endforeach;?>
      </div>
    </div>
    <div class="x-arrows"><a href="#prev" class="x-prev"><span class="icon-chevron-left icon-prev"></span></a><a href="#next" class="x-next"><span class="icon-chevron-right icon-next"></span></a></div>
    <div class="social">
      <ul>
        <li>Compartir:</li>
        <li class="fb"><a href="https://www.facebook.com/sharer/sharer.php?u={{host}}{{nUrl(model.nid)}}&amp;t={{getNode(model.nid).titulo}}"><span class="icon-facebook"></span></a></li>
        <li class="tw"><a href="https://twitter.com/intent/tweet?original_referer={{host}}&amp;text={{getNode(model.nid).titulo}}&amp;url={{host}}{{nUrl(model.nid)}}&amp;via=rpp"><span class="icon-twitter"></span></a></li>
      </ul>
    </div>
    <div class="x-pager-text"></div>
  </div>
</div>