<div class="media widen">
  <div data-x='{"lazy":true,"urlState":"{{host}}"}' itemscope itemtype="http://schema.org/ImageGallery" class="x-slide">
    <div class="x-wrapper">
      <div class="x-container">
        <?php foreach ($this->notapreview->contenido as $v => $contenido) :?>
            <?php if ($contenido['tipo'] == "photo"): ?>
        <div class="x-item">
          <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject" class="cover shadow-type-1">
            <img data-src="{{ contenido['foto']['url'] }}" alt="{{ contenido['foto']['alt'] }}">
            <figcaption itemprop="caption description">{{ contenido['foto']['alt'] }} | Fuente: {{ contenido['credito'] }}</figcaption>
          </figure>
        </div>
        <?php endif;?>
        <?php endforeach;?>
      </div>
    </div>
    <div class="x-arrows"><a href="#prev" class="x-prev"><span class="icon-chevron-left icon-prev"></span></a><a href="#next" class="x-next"><span class="icon-chevron-right icon-next"></span></a></div>
    <div class="social">
      <ul>
        <li>Compartir:</li>
        <li class="fb"><a href="javascript:;"><span class="icon-facebook"></span></a></li>
        <li class="tw"><a href="javascript:;"><span class="icon-twitter"></span></a></li>
      </ul>
    </div>
    <div class="x-pager-text"></div>
  </div>
</div>