<?php $imagen_portada_hash = false;?>
<?php $imagen_portada_hash = \Rpp\Services\Get\Content::node($nid)->imagen_portada['hash'] ?>
<figure class="op-slideshow">
<?php foreach (\Rpp\Services\Get\Content::part($nid,'galeria') as $v => $key) :?> 
	<?php if($imagen_portada_hash == \Rpp\Services\Get\Content::part($nid,'contenido')[$key]['foto']['hash']) continue; ?>
  <figure>
    <img src="{{ cdn_image(getPart(nid,'contenido')[key]['foto']['hash'],'large') }}" />
    <?php if( ! empty( \Rpp\Services\Get\Content::part($nid,'contenido')[$key]['foto']['alt']) ) :?>
     <figcaption>{{ getPart(nid,'contenido')[key]['foto']['alt'] }}</figcaption>
    <?php endif;?>
  </figure>
  <?php \Rpp\Services\Get\Content::unset_part($nid,'contenido',$key);  ?>
<?php endforeach;?>
</figure>