{{ partial('partials/resultados_electorales/congreso/style') }}
<script type="text/javascript">
  stage_file = '{{model.s3_raiz}}';
</script>

<div id="cont_jp" class="congresoprejp congresoprejp2">
	<h2 class="titujp1a">RESULTADOS CONGRESO 2016</h2>
    <header class="menuprinjp">
    	<nav >
        	<!--<a href="javascript:;" onclick="initjps2('ONPE');" class="activemjp">ONPE</a>
            <a href="javascript:;" onclick="initjps2('QA-TEST');">DATUM</a>
            <a href="javascript:;" onclick="initjps2('ONPE');">CPI</a>
            <a href="javascript:;" onclick="initjps2('ONPE');">GFK</a>
            <a href="javascript:;" onclick="initjps2('ONPE');">IPSOS</a>-->
        </nav>
        <div class="florrcabejp"><div>Mesas escrutadas <span class="florrcabejp_a"></span>% (<span class="florrcabejp_b"></span> votos)</div></div>
    </header>
	<div class="parte1jp homeporjch">
	    <div class="titujp1">POR BANCADA</div>
        <div class="titujp4">130<span>ESCAÑOS</span>
        </div>
    	<div id="containerjp" ></div>
        <div id="leyendjp" ></div>
    </div>
    <div class="limpia"></div>
</div>
