<?php if(@$destacadas['envivo']['estado']):?>
    {{ partial('partials/portada/bloque/cronologico/flash_widget', ['debate': destacadas['envivo'] ]) }}
<?php endif; ?>
<div class="row">
    <div class="box-mod box-special">
        <?php if(@$destacadas['encuesta']):?>
          {{ partial('tag/cabecera/cb_resultados_flash', ['enportho': '1' ]) }}
        <?php else:?>
          {{ partial('tag/cabecera/cb_elecciones-peru-2016', ['enportho': '1' ]) }}
        <?php endif;?>
        <div class="col-primary">
            <div class="box-grid">
                <div class="row columns-3">
                    <?php if(!is_array($destacadas['destacadas'])) $destacadas['destacadas'] = array();?>
                    <?php $e=1; foreach ($destacadas['destacadas'] as $v => $item):?>
                    
                      <?php if(@\Rpp\Services\Get\Content::node($item['nid'])->tipo=='url'):?>
                        <?php $durl= \Rpp\Services\Get\Content::part($item['nid'],'url_externo')?>
                      <?php else: ?>
                        <?php $durl=  \Rpp\Services\Get\Content::nurl($item['nid'])?>
                      <?php endif; ?>

                        <?php $df_id = @\Rpp\Services\Get\Content::part($item['nid'],'datafactory')?>
                        <div class="cell">
                            <article class="card">
                                <figure class="holder">
                                    <a href="{{durl}}" class="cover">
                                        {{ partial('partials/generic/lazy_image' , ['content' : cdn_image(item['imagen_portada']['hash'], 'small'), 'alt': item['imagen_portada']['alt'] ]) }}
                                        {{ partial('partials/portada/grilla/block/icon/' ~ getNode(item['nid']).tipo ) }}
                                        <?php if(@$item['envivo']): ?>
                                            <span class="live-news">En vivo</span>
                                        <?php endif; ?>
                                    </a>

                                </figure>
                                <div class="cont">
                                    <h2><a href="{{durl}}">{{item['titulo']}}</a></h2>
                                </div>

                            </article>
                        </div>
                        <?php unset($destacadas['destacadas'][$v])?>
                        <?php if($e >= 3) break;?>
                        <?php $e++ ;?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="col-secondary">
            <div class="box-row">

                <?php if(@$destacadas['publicidad']):?>
                  {{ partial('partials/ads/auspiciado1') }}
                <?php else:?>
                    <?php $e=1; foreach ($destacadas['destacadas'] as $v => $item):?>
                        {{ partial('partials/portada/bloque/tag/title_small', [ 'item' : item ]) }}
                        <?php if($e >= 2) break;?>
                        <?php $e++ ;?>
                    <?php endforeach; ?>

                <?php endif; ?>
            </div>
        </div>
    </div>
</div>