<?php if(@$destacadas['envivo']['estado']):?>
<?php $debate = $destacadas['envivo'];?>
<!--begin: debate widget -->
      <link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/debate.css?v={{eversion}}">
      <div id="widget-debate">
        <div class="wd-row">
          <div class="wd-col col-a">
            <div class="col-a-top">
              <a href="#" class="envivo">
                <img src="{{ehost}}/static/img/envv.svg" alt="En Vivo" class="ico">
                <span class="titu">En Vivo</span>
              </a>
              <span class="hashtag">#VotaPerú</span>
            </div>
            <div id="video">
              <figure>
                   <div class="cover cover-media">
                    <a href="#audio" data-x='{"playlist":"[{\"file\" : \"rtsp:\/\/streaming.gruporpp.net:1935\/rpp02live-live\/streamRPPRD\"},{\"file\" : \"http:\/\/streaming.gruporpp.net:1935\/rpp02live-live\/streamRPPRD\/playlist.m3u8\"}]","type":"audio","video_source":"rtmp:\/\/rpplivefs.fplive.net\/rpp02live-live\/streamRPPRD","video_img":"{{ehost}}/elecciones-peru-2016/img/radio_en_vivo.jpg","hash":"undefined","rtag":"https:\/\/pubads.g.doubleclick.net\/gampad\/ads?sz=400x300&iu=\/1028310\/RPP_Video&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]","section":"Home","vtemas":""}' class="x-media big"><img src="{{ehost}}/elecciones-peru-2016/img/radio_en_vivo.jpg" alt="envivo">
                    <span class="icon-audio"></span></a>
                </div>
                <figcaption>Transmisión Elecciones Presidenciales 2016</figcaption>
              </figure>
            </div>
          </div>
          <div class="wd-col col-b">
            <span class="mam">MINUTO A MINUTO</span>
            <span class="hashtag">#VotaPerú</span>
            <div class="body-inner-mam">
            <?php if(!empty(@$debate['evento']['id'])):?>
              {{ partial('partials/portada/bloque/cronologico/mam' , ['id':  debate['evento']['id'] ] ) }}
            <?php endif;?>
            </div>
          </div>
        </div>
      </div>
<!--end: debate widget-->
<?php endif; ?>
