<div class="weather-table">
		<table>
			<thead>
				<tr>
					<th><strong>Semanal:</strong></th>
				<?php  foreach ($this->model->pronostico as $day): ?>
					<th>{{day['nombre']}} <span class="w{{day['codigo']}}"></span></th>
				<?php endforeach;?>
				</tr>
			</thead>

			<tbody>
				<tr class="gray">
					<td>Temperatura máxima</td>
					<?php  foreach ($this->model->pronostico as $day): ?>
					<td>{{day['maximo']}} ºC</td>
					<?php endforeach;?>

				</tr>
				<tr>
					<td>Temperatura mínima</td>
				    <?php  foreach ($this->model->pronostico as $day): ?>
					<td>{{day['minimo']}} ºC</td>
					<?php endforeach;?>
				</tr>
				<!-- <tr class="gray">
					<td>Presión atmosférica</td>
					<td>864.06 hPa</td>
					<td>863.72 hPa</td>
					<td>862.94 hPa</td>
					<td>896.66 hPa</td>
					<td>897.98 hPa</td>
					<td>899.51 hPa</td>
					<td>899.91 hPa</td>
				</tr>
				<tr>
					<td>Humedad</td>
					<td>80%</td>
					<td>78%</td>
					<td>71%</td>
					<td>0%</td>
					<td>0%</td>
					<td>0%</td>
					<td>0%</td>
				</tr>
				<tr class="gray">
					<td>Cobertura nubosa</td>
					<td>56%</td>
					<td>8%</td>
					<td>0%</td>
					<td>13%</td>
					<td>10%</td>
					<td>46%</td>
					<td>2%</td>
				</tr> -->
			</tbody>
		</table>
	</div>