<link rel="stylesheet" type="text/css" href="{{ehost}}/elecciones-peru-2016/css/elecciones-restructured.css?v={{eversion}}">

<div class="box-mod wrap-especial in-content" id="menu-votaperu">
    <div class="box-header">
        <h3 class="title">
            <a href="{{host}}/elecciones-peru-2016">
                <span class="hide">Elecciones Perú 2016</span>
                <img src="{{host}}/elecciones-peru-2016/img/logo_header.gif" alt="Elecciones Perú 2016">
            </a>
            <button
                class="especial-btn"
                type="button"
                onclick='fn(this, event, {"method":"toggleClass", "to": "#menu-votaperu"})'>
                <span class="icon-chevron-down"></span>
            </button>
        </h3>
        <figure class="pull-right">
            <ul class="nav">
                <li ><a href="{{host}}/elecciones-peru-2016">noticias</a></li>
                <li ><a href="{{host}}/elecciones-peru-2016/candidatos.html">candidatos</a></li>
                <li ><a href="{{host}}/elecciones-peru-2016/redes">en redes</a></li>
                <li class="active" ><a href="{{host}}/elecciones-peru-2016/encuesta" class="active" >encuestas</a></li>
                <li ><a href="http://rpp.pe/politica/congreso/elecciones-peru-2016-estos-son-los-candidatos-al-congreso-noticia-940142">lista congreso</a></li>
                <li><a href="{{host}}/elecciones-peru-2016/comparaya.html">Compara Ya</a></li>
                <li><a href="{{host}}/elecciones-peru-2016/gps-electoral.html">GPS Electoral</a></li>
            </ul>
        </figure>
    </div>
</div>
