<?php $imgcabecera = @$this->model->tag_info->personalidad['sitios'][0]['tag_especial']['url_1020x65']  ?>
<?php if($imgcabecera):?> 
	<div class="box-mod box-header back-image">
		<h1 style="background:transparent url('{{imgcabecera}}') left top no-repeat; height:140px;">{{model.tag_info.nombre}}</h1>
	</div>
<?php else:?>
	<div class="box-mod box-header-section tagsec-{{model.slug}}">
		<div class="box-header">
		<h1 class="title-mod">{{model.tag_info.nombre}}</h1>
		</div>
	</div>
<?php endif;?>