
<div class="social-share-horizontal">
    <ul class="group">
        <li class="facebook-share">
            <div class="fb-share-button" data-href="<?=$slugne;?>"
                 data-layout="button_count"></div>
        </li>
        <li class="twitter-share">
            <a href="https://twitter.com/share" class="twitter-share-button"
               data-url="<?=$slugne;?>" data-lang="en">Tweet</a>
        </li>
        <li class="google-share">
            <div class="g-plus" data-action="share" data-annotation="bubble"
                 data-href="<?=$slugne;?>"></div>
        </li>
        <li class="linkedin-share">
            <script type="in/share" data-url="<?=$slugne;?>" data-counter="right"></script>
        </li>
        <li class="pinterest-share">
            <a href="https://pinterest.com/pin/create/button/?url=<?=$slugne;?>"
               data-pin-do="buttonPin" data-pin-config="before"><img
                    src="//assets.pinterest.com/images/pidgets/pin_it_button.png"></a>
        </li>
    </ul>
</div>
<!-- .social-share -->
<div class="social-share-mobile">
    <ul>
        <li class="twitter-share"><a href="#"><i class="icon-5"></i><span>Twitter</span></a></li>
        <li class="facebook-share"><a href="#"><i class="icon-1"></i><span>Facebook</span></a></li>
        <li class="google-share"><a href="#"><i class="icon-2"></i><span>Google+</span></a></li>
        <li class="pinterest-share"><a href="#"><i class="icon-26"></i><span>Pinterest</span></a></li>
        <li class="whatsapp-share"><a href="#"><i class="icon-18"></i><span>Whatsapp</span></a></li>
    </ul>
</div>
<!-- .social-share -->