{% cache "nota.header.geleria." ~ model.nid ~ "." ~ model.position 604800 %}
{{ partial('partials/nota/header/indexpl' ~ model.package) }}
<div class="wrap-galeria">
	<div class="galeria-full">
    <div class="galeria">
      <div class="slide state" 
              data-params='{
                   "baseurl": "{{host}}{{pUrl(model.nid)}}"
                            }'
              data-vars='{
                   "comscore" : {
                                  "site" : "rpp",
                                  "name" : "{{model.comscore}}"
                                },
                    "posicion" : {{model.position}},
                    "params" : "<?php echo implode('&',load_ref('='))?>",
                    "epl_tag" : [ "Top","Right" ]
                            }'>

        <?php $zise = count(\Rpp\Services\Get\Article::part($this->model->nid,'galeria'))?>
        <div class="content">
          <div class="inner">
            <?php foreach (\Rpp\Services\Get\Article::part($this->model->nid,'galeria') as $v => $key) :?>
            <div class="item">
              <figure class="hmedia">

                <?php if($this->model->position == $v):?>
                <img class="photo" src="{{ cdn_image(gPart(model.nid,'contenido')[key]['foto']['hash'],'large') }}" alt="{{ gPart(model.nid,'contenido')[key]['foto']['alt'] }}">
                <?php else :?>
                <img class="photo" src="" data-src="{{ cdn_image(gPart(model.nid,'contenido')[key]['foto']['hash'],'large') }}" alt="{{ gPart(model.nid,'contenido')[key]['foto']['alt'] }}">
                <?php endif;?>
              </figure>
 <figcaption>{{ gPart(model.nid,'contenido')[key]['foto']['alt'] }} {% if not( gPart(model.nid,'contenido')[key]['via'] is empty) %} | <strong>Fuente:</strong> {{ gPart(model.nid,'contenido')[key]['via'] }} {% endif %} {% if not(gPart(model.nid,'contenido')[key]['credito'] is empty) %} | <strong>Fotógrafo:</strong> {{ gPart(model.nid,'contenido')[key]['credito'] }} {% endif %}</figcaption>
            </div>
            <?php \Rpp\Services\Get\Article::unset_part($this->model->nid,'contenido',$key);  ?>
            <?php endforeach;?>

          </div>
        </div>

        <div class="arrows">
          <a href="#prev" class="prev">
            <span>
              <i class="icon-13"></i>
            </span>
          </a>
          <a href="#next" class="next">
            <span>
              <i class="icon-14"></i>
            </span>
          </a>
        </div>
        <div class="pagers">
          <div class="text-pager">
            <p>
              Foto <span class="g-num">1</span> de <span class="g-total">{{zise}}</span>
            </p>
          </div>
     
          <ul class="pager-circle">
             <?php for ($i=1; $i <= $zise ; $i++ ):?>
                <li data-pager="{{i}}" class="page"></li>
             <?php endfor;?>
          </ul>

              <div class="social-state">
                <span>Compartir: </span>
                <a  class="fc" href="javascript: void(0);" onclick="rpp.shareSocial(this, 'facebook', 'http://rpp.pe{{pUrl(model.nid)}}')">
                  <i class="icon-1"></i>
                </a>
                <a class="tw" href="javascript: void(0);" onclick="rpp.shareSocial(this, 'twitter', '{{host}}/p/{{model.nid}}')">
                  <i class="icon-5"></i>
                </a>
              </div>

        </div>

      </div>
    </div> 
  </div>
  <div class="sidebar-galeria">
    {{ partial('partials/ads/right') }}
  </div>
</div>
{% endcache %}