
    {{ partial('partials/nota/header/indexpl' ~ model.package) }}       


<div class="gallery-single">
    <?php $i=0;foreach (\Rpp\Services\Get\Article::part($this->model->nid,'contenido') as $contenido): ?> 
     {% if contenido['tipo'] == "photo" %}
    <section class="img-news" >                                           
    <figure class="hmedia main-photo" ><img style="display: block;margin-left: auto;margin-right: auto;" src="{{contenido['foto']['url']}}" alt="{{contenido['subtitulo']}}" title="{{contenido['subtitulo']}}">
      <figcaption class="help-media">
      <?php echo @$contenido['foto']['alt']; ?>
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}
      </figcaption>
    </figure>
    </section>
     <?php \Rpp\Services\Get\Article::unset_part($this->model->nid,'contenido',$i)?>
    {% break  %}
    {% elseif contenido['tipo'] == "embed" %}
       <p>
        {{contenido['embed']}}
        </p>
       <?php \Rpp\Services\Get\Article::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "video" %}
       <section class="img-news">
        <div id="swfplayer_open" class="nd_galeriaopen_">   </div>
        <div class="help-media">
        <?php echo @$contenido['video']['descripcion']; ?>
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}
            </div>
        <script type="text/javascript">setJW7("swfplayer_open", "{{contenido['video']['url']}}", "{{contenido['video']['url_cover']}}", '{{contenido['video']['playlist']|default([])|json_encode}}',"{{contenido['video']['hash']}}","{{model.preroll}}");</script>
       </section>
       <?php \Rpp\Services\Get\Article::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% elseif contenido['tipo'] == "youtube" %}
     <section class="img-news">
     <div id="swfplayer_{{contenido['youtube']['id']}}" class="nd_galeriaopen_{{contenido['youtube']['id']}}"></div>
     <div class="help-media">
        <?php echo @$contenido['youtube']['descripcion']; ?>
        {% if not(contenido['via'] is empty) %}
        | <strong>Fuente:</strong> {{ contenido['via'] }}
        {% endif %}
        {% if not(contenido['credito'] is empty) %}
        | <strong>Fotógrafo:</strong> {{ contenido['credito'] }}
        {% endif %}
            </div>
        </section>
     <?php if(empty($contenido['youtube']['url_cover'])) : ?>
     <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "http://img.youtube.com/vi/{{contenido['youtube']['id']}}/0.jpg", undefined, undefined, "{{model.preroll}}");</script>
     <?php else: ?>
      <script type="text/javascript">setJW7("swfplayer_{{contenido['youtube']['id']}}", "https://www.youtube.com/watch?v={{contenido['youtube']['id']}}", "{{contenido['youtube']['url_cover']}}", undefined, undefined, "{{model.preroll}}");</script>
     <?php endif;?> 
     <?php \Rpp\Services\Get\Article::unset_part($this->model->nid,'contenido',$i)?>
     {% break  %}
     {% endif  %}
     <?php $i++?>
<?php endforeach;?>

</div>

<div class="wrap group">
    <div class="content group">  
       <!-- <div class="entry-content group"> -->
       <div class="group">
            {{ partial('partials/nota/detalle/plsocial') }}
            {{ partial('partials/nota/detalle/plsocialmobile') }}
            <div class="cont ajust_win">
                {{ partial('partials/nota/detalle/open/pl' ~ model.package ) }} 
                {{ partial('partials/nota/detalle/block/firma/pl'~model.package) }}
                {{ partial('partials/nota/detalle/content/pl'~model.package) }}                            
                <!-- .social-share -->                            
                {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
            </div>
            <!-- .cont -->
        </div>
        <?php if(!(@\Rpp\Services\Get\Article::part($this->model->nid,'comentariosfb')===false)) :?>
        <!-- .entry-content -->
        <div class="news-comments" id="ancla-comments">
            <h2 class="panel-title">Dinos que opinas</h2>
            <div class="fb-comments" data-href="{{host}}{{pUrl(model.nid)}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
        </div>
        <?php endif;?>
        <!-- .comments -->

       {{ partial('partials/ads/interna_full' , ['position':9]) }}
        <!-- .pub-wrap -->
        {{ partial('partials/nota/sugeridas/index' , [] , trackurl ) }}

        {{ partial('partials/ads/interna_full' , ['position':10]) }}
        <!-- .related-news -->

    </div>   
    <!-- .content -->
    <aside class="sidebar">
        {{ partial('partials/ads/right') }}
        {{ partial('partials/nota/sidebar/mas_en_tag' ,[], trackurl ) }}
        {{ partial('partials/ads/perured_nota') }} 
        <!-- pub-300 -->                   
        {{ partial('partials/nota/sidebar/recomendado' ,[] , trackurl ) }}
        {{ partial('partials/ads/right1') }}
    </aside>
    <!-- .sidebar -->
</div>