{% cache "nota.wrap.group." ~ model.nid 604800 %}
{{ partial('partials/nota/header/indexpl' ~ model.package) }}                
<!-- <div class="entry-content group"> -->
<div class="group">
    {{ partial('partials/nota/detalle/plsocial') }}
    {{ partial('partials/nota/detalle/plsocialmobile') }}
    <div class="cont ajust_win">
        {{ partial('partials/nota/detalle/open/pl' ~ model.package ) }} 
        {{ partial('partials/nota/detalle/block/firma/pl'~model.package) }}
        {{ partial('partials/nota/detalle/content/pl'~model.package) }}                            
        <!-- .social-share -->                            
        {{ partial('partials/nota/tags/index'~model.package , [] , trackurl ) }}
    </div>
    <!-- .cont -->
</div>
<?php if(!(@\Rpp\Services\Get\Article::part($this->model->nid,'comentariosfb')===false)) :?>
<!-- .entry-content -->
<div class="news-comments" id="ancla-comments">
    <h2 class="panel-title">¿Qué opinas?</h2>
    <div id="fbCommentPage" class="fb-comments" data-href="{{host}}{{pUrl(model.nid)}}" data-width="100%" data-numposts="5" data-colorscheme="light"></div>
</div>
<?php endif;?>
<!-- .comments -->
{% endcache %} 