<div class="wrap group">
            <div class="content group">
               {{ partial('partials/nota/tipo/plnota/ncache') }}   
               {{ partial('partials/ads/interna_full' , ['position':9]) }}
                <!-- .pub-wrap -->
                {{ partial('partials/nota/sugeridas/plindex' , [] , trackurl ) }}
                {{ partial('partials/ads/interna_full' , ['position':10]) }}
                <!-- .related-news -->

            </div>
    <!-- .content -->
   {{ partial('partials/nota/sidebar/plindex') }}  
    <!-- .sidebar -->
</div>