<?php
  $gene_img['type']='html';
  $gene_img['content'] ='<img src="'.\Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Article::node($nid)['imagen_portada']['hash'], 'medium') .'" alt=" '.\Rpp\Services\Get\Article::node($nid)['imagen_portada']['alt'].' ">';
$jsongene_img=json_encode($gene_img, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE);
  ?>
<article class="card">
  <figure class="holder"><a href="{{pUrl(nid)}}" data-x='<?=$jsongene_img;?>' class="cover x-fit-lazy">
      <?php $tipo = \Rpp\Services\Get\Article::node($nid)['tipo'] ?>
       {{ partial('partials/portada/grilla/block/icon/' ~ tipo ) }}
      </a>
<div class="social inverse">
  <ul>
    <li class="fb"><a href="https://www.facebook.com/sharer/sharer.php?u={{host}}{{pUrl(nid)}}&amp;t={{gNode(nid)['titulo']}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-facebook"></span></a></li>
    <li class="tw"><a href="https://twitter.com/intent/tweet?original_referer={{host}}&amp;text=<?=urlencode(\Rpp\Services\Get\Article::node($nid)['titulo_corto']);?>&amp;url={{host}}{{pUrl(nid)}}&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-twitter"></span></a></li>
  </ul>
</div>
  </figure>
  <div class="cont">
<div class="top-info"  >
  <div class="cat">
    <a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Article::node($nid)['categoria']['slug']) ;  ?>">{{gNode(nid)['categoria']['nombre']}}</a>
  </div>
  <?php $fecha_actual = time();?>
  <?php $fecha_publicacion  = \Rpp\Services\Get\Article::node($nid)['fecha_publicacion']  ?>
  <?php if($fecha_publicacion > $fecha_actual) $fecha_publicacion = $fecha_actual; ?>
  <time class="time x-ago" data-x="<?php echo date('Y-m-d\TH:i:sP' , $fecha_publicacion )?>">
    {{date('d/m/y', fecha_publicacion )}}
  </time>
</div>
    <h3><a href="{{pUrl(nid)}}">{{gNode(nid)['titulo_corto']}}</a></h3>
    <p>{{gNode(nid)['bajada']}}</p>
  </div>
</article>
