<?php
  $gene_img['type']='html';
  $gene_img['content'] ='<img src="'.\Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\Content::node($nid)->imagen_portada['hash'], 'medium') .'" alt=" '.\Rpp\Services\Get\Content::node($nid)->imagen_portada['alt'].' ">';
$jsongene_img=json_encode($gene_img, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE);
  ?>
<article class="card">
  <figure class="holder"><a href="{{nUrl(nid)}}" data-x='<?=$jsongene_img;?>' class="cover x-fit-lazy">
      </a>
    {{ partial('partials/portada/flujo/box/social', [ 'nid' : nid ]) }}
  </figure>
  <div class="cont">
    {{ partial('partials/portada/flujo/box/cat', [ 'nid' : nid ]) }}
    <h3><a href="{{nUrl(nid)}}{{TrackUrl(position)}}" >{{getNode(nid).titulo_corto}}</a></h3>
    <div class="author"><img src="<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn(@\Rpp\Services\Get\Content::part($nid,'autor')['foto'],'media')?>" alt="{{getPart(nid,'autor')['nombre']}}">
      <div class="data">Escrito por:<a href="{{host}}<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($nid)->categoria['slug']) ;  ?>">{{getPart(nid,'autor')['nombre']}}</a></div>
    </div>
    <p>{{getNode(nid).bajada}}</p>
  </div>
</article>