<?php $size_brand = !empty(@\Rpp\Services\Get\Content::part($nid,'imagen_branding'));?>
  <?php $size_especial = !empty(@\Rpp\Services\Get\Content::part($nid,'imagen_tag'));?>
<div class="top-info"  >
	<div class="cat">
	<?php if((int) $size_brand==1){ ?>
		<div class="sponsor">
		  <div class="by">Gracias a:</div><a href="{{host}}/tema-{{getPart( nid ,'imagen_branding')['slug']}}" ><img src="<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn_raiz(\Rpp\Services\Get\Content::part($nid,'imagen_branding')['url']) ?>" alt="{{getPart( nid ,'imagen_branding')['nombre']}}"></a>
		</div>
	<?php }else if((int) $size_especial==1){ ?>
		<div class="sponsor">
		  <a href="{{host}}/tema-{{getPart( nid ,'imagen_tag')['slug']}}" ><img src="<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn_raiz(\Rpp\Services\Get\Content::part($nid,'imagen_tag')['url']) ?>" alt="{{getPart( nid ,'imagen_tag')['nombre'] }}"></a>
		</div>
	<?php }else{ ?>
		<a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\Content::node($nid)->categoria['slug']) ;  ?>{{TrackUrl(position)}}">{{getNode(nid).categoria['nombre']}}</a>
	<?php } ?>

	</div>
	<?php $fecha_actual = time();?>
  <?php $fecha_publicacion  = \Rpp\Services\Get\Content::node($nid)->fecha_publicacion  ?>
  <?php if($fecha_publicacion > $fecha_actual) $fecha_publicacion = $fecha_actual; ?>
	<time class="time x-ago" data-x="<?php echo date('Y-m-d\TH:i:sP' , $fecha_publicacion )?>">
		{{date('d/m/y', fecha_publicacion )}}
	</time>
</div>