<?php $titulo =  \Rpp\Services\Get\LContent::node($nid)->titulo ?>
<?php $titulo_corto =  \Rpp\Services\Get\LContent::node($nid)->titulo_corto ?>
<?php $bajada =  \Rpp\Services\Get\LContent::node($nid)->bajada ?>


<?php if(@\Rpp\Services\Get\LContent::node($nid)->tipo=='url'):?>
    <?php $durl= \Rpp\Services\Get\LContent::part($nid,'url_externo')?>
<?php else: ?>
    <?php $durl=  \Rpp\Services\Get\LContent::nurl($nid)?>
<?php endif; ?>
<article>
    <figure class="holder"><a href="{{durl}}" class="cover"><img src="<?php echo \Rpp\Services\Get\UrlMedia::image(\Rpp\Services\Get\LContent::node($nid)->imagen_portada['hash'], 'medium');?>" alt="<?php echo @\Rpp\Services\Get\LContent::node($nid)->imagen_portada['alt']?>">
    <?php $tipo = \Rpp\Services\Get\Content::node($nid)->tipo ?>
        {{ partial('partials/portada/grilla/block/icon/' ~ tipo ) }}
    </a>

<div class="social inverse">
  <ul>
    <li class="fb"><a href="https://www.facebook.com/sharer/sharer.php?u={{durl}}&amp;t={{titulo}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-facebook"></span></a></li>
    <li class="tw"><a href="https://twitter.com/intent/tweet?original_referer={{host}}&amp;text={{titulo}}&amp;url={{host}}{{durl}}&amp;via=rpp" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-twitter"></span></a></li>
  </ul>
</div>

    </figure>

    <div class="cont">
<div class="top-info"  >
    <div class="cat">
        <a href="<?php echo str_replace( SITESLUG ,'', \Rpp\Services\Get\LContent::node($nid)->categoria['slug']) ;  ?>"><?php echo \Rpp\Services\Get\LContent::node($nid)->categoria['nombre'] ;  ?></a>
    </div>
    <?php $fecha_publicacion  = \Rpp\Services\Get\LContent::node($nid)->fecha_publicacion  ?>
    <time class="time x-ago" data-x="<?php echo date('Y-m-d\TH:i:sP' , $fecha_publicacion )?>">
        {{date('d/m/y', fecha_publicacion )}}
    </time>
   </div>
      <h2 class="headline"><a href="{{durl}}">{{titulo}}</a></h2>
      <p>{{bajada}}</p>
    </div>
</article>