<div class="social inverse">
  <ul>
    <li class="fb"><a href="https://www.facebook.com/sharer/sharer.php?u={{host}}{{nUrl(nid)}}&amp;t={{getNode(nid).titulo}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-facebook"></span></a></li>
    <li class="tw"><a href="https://twitter.com/intent/tweet?original_referer={{host}}&amp;text=<?=urlencode(\Rpp\Services\Get\Content::node($nid)->titulo_corto);?>&amp;url={{host}}{{nUrl(nid)}}&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})"><span class="icon-twitter"></span></a></li>
  </ul>
</div>