<div id="fb-root"></div>
{{ partial('partials/ads/top') }}
<!-- pub-980 -->
<header class="wrapper">
    {{ partial('partials/ads/verticales') }}
    {{ partial('partials/header/fecha') }}
    {{ partial('partials/header/search',[] , trackurl ) }}
    {{ partial('partials/header/nav',[] , trackurl ) }}
    {{ partial('partials/header/logonav' ) }}
    <!-- header-main -->
   {{ partial('partials/portada/bloque/tag/campana_cabecera' , ['slug':slug ] ) }}
    <div class="widget-cabecera">    
    </div>
   {{ partial('partials/ads/expandible') }}
    <!-- pub-980 -->
</header><!-- header -->
<!-- {{ partial('partials/ads/bg_banner') }} -->
