    {{ partial('partials/ads/top') }}
    {{ partial('partials/header/logonav') }}
    {{ partial('partials/header/navmovil',[] , trackurl ) }}
    {{ partial('partials/header/search',[] , trackurl ) }}
    {{ partial('partials/header/nav',[] , trackurl ) }}
    {{ partial('partials/header/smartphone',[] , trackurl ) }}
    {{ partial('partials/header/picantes',[] , trackurl ) }}
    {{ partial('partials/ads/frame2') }}
    {{ partial('partials/ads/back_pushdown') }}
    <?php if(@$this->model->slug_seccion[2]=='descentralizado') :?>
<div class="wrap_bannerclick">
<style type="text/css">body { background: #e3e3e3 url("http://ads.us.e-planning.net/eb/3/15cd9/02994db1f63a8e4d?o=i&rnd=$RANDOM") no-repeat center top fixed } </style>
<div class="wrap_bannerclick">
<a class="banner_left" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"></a>
<a class="banner_right" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/02994db1f63a8e4d?it=i&rnd=$RANDOM"></a>
</div>
</div>
<?php else :?>
<div class="wrap_bannerclick">
<style type="text/css">body { background: #e3e3e3 url("http://ads.us.e-planning.net/eb/3/15cd9/33973fe30fa9bfd2?o=i&rnd=$RANDOM") no-repeat center top fixed } </style>
<div class="wrap_bannerclick">
<a class="banner_left" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/33973fe30fa9bfd2?it=i&rnd=$RANDOM"></a>
<a class="banner_right" target="_blank" href="http://ads.us.e-planning.net/ei/3/15cd9/33973fe30fa9bfd2?it=i&rnd=$RANDOM"></a>
</div>
</div>
<?php endif;?>
    {{ partial('partials/ads/back_frame') }}
