<div id="fb-root"></div>
{{ partial('partials/header/nav_especial',[] , trackurl ) }}
<!-- pub-980 -->

<div class="wrapper wrapper-top">
    {{ partial('partials/ads/verticales') }}
    {{ partial('partials/ads/top') }}
    {{ partial('partials/header/search',[] , trackurl ) }}
    <!-- header-main -->
   {{ partial('partials/portada/bloque/tag/campana_cabecera' , ['slug': model.tag_slug_portada ] ) }}
    <div class="widget-cabecera">    
    </div>
   {{ partial('partials/ads/expandible') }}
    <!-- pub-980 -->
</div><!-- header -->
<!-- {{ partial('partials/ads/bg_banner') }} -->
