  <div class="header-scroll">
    <div class="w-menu-scroll">
      <div class="wrapper group">
        <a href="/" class="i-back">
          <i class="icon-13"></i>
        </a>
        <a class="logotipo" href="/">RPP Noticias</a>

        <a id="envivo-mini" href="/radioenvivo"><embed class="icn-vivo" src="{{ehost}}/images/envv.svg" type="image/svg+xml"/>En Vivo:<strong></strong></a>
      </div>
      <ul class="socialRpp">
      <!--
        <li>
          <div class="fb-like" data-href="https://www.facebook.com/rppnoticias/" data-layout="button"></div>
        </li>
        <li>
          <a href="https://twitter.com/RPPNoticias" class="twitter-follow-button" data-show-count="false" data-lang="es" data-show-screen-name="false">Seguir</a>
        </li>
        <li>
          <script src="https://apis.google.com/js/platform.js" async defer>
            {lang: 'es'}
          </script>
      <div class="g-follow" data-annotation="none" data-height="20" data-href="//plus.google.com/113482325785133390225" data-rel="author">
        
      </div>
        </li> -->
        
      </ul>
      <div class="controls-responsive">
        <i class="icon-hamburguesa"></i>
        <i class="icon-cancel none"></i>
      </div>

      <div class="w-c">

        <form class="search-mn" id="search2" action="/buscar" method="POST">
          <input name="texto" type="text" placeholder="BUSCAR">
          <button><span class="icon-9"></span></button>
        </form>

      <ul class="main-menu group">
        <li><a href="/politica">Política</a></li>
        <li><a href="/actualidad">Actualidad</a></li>
        <li><a href="/deportes">Deportes</a></li>
        <li><a href="/entretenimiento">Entretenimiento</a></li>
        <li><a href="/peru">Perú</a></li>
        <li><a href="/mundo">Mundo</a></li>
        <li><a href="/economia">Economía</a></li>
        <li><a href="/vida">Vida</a></li>
        <li><a href="/tecno">Tecno</a></li>
        <li><a href="/viral">Viral</a></li>
        <li><a class="" href="/autores">Autores</a></li>
        <li><a href="/programacion/radio">Radio </a></li>
        <li><a href="/programacion/tv">TV </a>
      </ul>

        <div class="block-complement">
          <div class="icons-responsive">
            <h5>Servicios</h5>
            <a href="/tema-rotafono">
              <i class="icon-rotafono"></i>
              <span>Rotafono</span>
            </a>
            <a href="/tema-trafico">
              <i class="icon-trafico"></i>
              <span>Tráfico</span>
            </a>
            <a href="/virales/cine">
              <i class="icon-cine"></i>
              <span>Cine</span>
            </a>
            <a href="/tema-clima">
              <i class="icon-cloud-sun"></i>
              <span>Clima</span>
            </a>
          </div>

          <div class="socials-responsive">
            <h5>RPP Noticias en Redes</h5>
            <a  href="https://www.facebook.com/rppnoticias" class="fb-responsive" target="_blank" >
              <i class="icon-1"></i>
            </a>
            <a href="https://twitter.com/rppnoticias" class="tw-responsive" target="_blank" >
              <i class="icon-5"></i>
            </a>
            <a href="https://plus.google.com/113482325785133390225" class="go-responsive" target="_blank" >
              <i class="icon-2"></i>
            </a>
            <a href="https://www.youtube.com/user/RPPNOTICIAS" class="you-responsive" target="_blank" >
              <i class="icon-3"></i>
            </a>
          </div>

        </div>
      </div>

    </div>
  </div><!-- .header-scroll -->


{% if (model.alert.tipo  is defined ) %}
    {{ partial('partials/header/alert/alerta_' ~ model.alert.tipo) }}
{% endif  %}

<div class="traffic-mobile">
  <img src="{{ehost}}/images/traffic-mobile.png" alt="Trafico Waze">
</div>
