<!--Header-->
<section class="header-logo-nav fix-logo-nav sinfix">
  <div class="wrapper">
    <figure class="logo"><a href="/"><img src="<?php echo $host; ?>/svg/logo-la10.svg" alt="Logo La10"></a></figure>
    <nav class="nav-header">
      <ul>
        <li <?php if( @$this->model->slug == 'resultados' ):?>class="active"<?php endif;?> ><a href="/resultados/fecha{{TrackUrl()}}">Resultados</a></li>
        <li <?php if( @$this->model->slug_seccion == 'futbol-peruano' ):?>class="active"<?php endif;?> ><a href="/futbol-peruano{{TrackUrl()}}">Fútbol Peruano</a></li>
        <li <?php if( @$this->model->slug_seccion == 'futbol-internacional' ):?>class="active"<?php endif;?> ><a href="/futbol-internacional{{TrackUrl()}}">Fútbol Internacional</a></li>
        <li <?php if( @$this->model->slug_seccion == 'futbol-peruano/seleccion' ):?>class="active"<?php endif;?>><a href="/futbol-peruano/seleccion{{TrackUrl()}}">Selección</a></li>
        <li <?php if( @$this->model->slug_seccion == 'full-contacto' ):?>class="active"<?php endif;?> ><a href="/full-contacto{{TrackUrl()}}">Full Contacto</a></li>
        <li <?php if( @$this->model->slug_seccion == 'mas-deportes' ):?>class="active"<?php endif;?> ><a href="/mas-deportes{{TrackUrl()}}">+ Deportes</a></li>
      </ul>
      <ul class="nav-fix">
        <li id="open-nav-movil-fix2"><i class="icon icon-navicon"></i></li>
      </ul>
    </nav>
  </div>
</section>
