        <nav class="nav-rpp">
            <ul class="main-menu group">
            <li class="more"><a href="#">Más <span class="icon-19"></span></a></li>
            <li><a href="/politica">Política</a></li>
            <li><a href="/actualidad">Actualidad</a></li>
            <li><a href="/deportes">Deportes</a></li>
            <li><a href="/entretenimiento">Entretenimiento</a></li>
            <li><a href="/peru">Perú</a></li>
            <li><a href="/mundo">Mundo</a></li>
            <li><a href="/economia">Economía</a></li>
            <li><a href="/vida">Vida</a></li>
            <li><a href="/tecno">Tecno</a></li>
            <li><a href="/viral">Viral</a></li>
            <li><a href="/autores">Autores</a></li>
            <li><a href="/programacion/radio">Radio </a></li>
            <li><a href="/programacion/tv">TV </a></li>
            </ul>
            <ul class="more-items group hidden"></ul>
        </nav>

