<nav class="nav-top">
              <ul>
                <li><a href="/" class="active">Edición General</a></li>
                <li><a href="#link">Arequipa</a></li>
                <li><a href="#link">La Libertad</a></li>
                <li><a href="#link">Lambayeque</a></li>
                <li><a href="#link">Junín</a></li>
                <li><a href="#link">Ancash</a></li>
                <li><a href="#link">Ica</a></li>
                <li><a href="#link">Puno</a></li>
                <li><a href="#link">Piura</a></li>
                <li><a href="#link">Cusco</a></li>
              </ul>
            </nav>