    <nav class="nav-full">
      <!--Nav main-->
      <section class="wrapper">
        <ul>
          <li class="first-li">Tendencias:</li>
          <li> <a href="/noticias/alianza-lima{{TrackUrl()}}">Alianza Lima</a></li>
          <li> <a href="/noticias/universitario-de-deportes{{TrackUrl()}}">Universitario</a></li>
          <li> <a href="/noticias/champions-league{{TrackUrl()}}">Champions</a></li>
          <li> <a href="/noticias/real-madrid{{TrackUrl()}}">Real Madrid</a></li>
          <li> <a href="/noticias/barcelona{{TrackUrl()}}">Barcelona</a></li>
          <li> <a href="/noticias/boca-juniors{{TrackUrl()}}">Boca Junior</a></li>
          <li> <a href="/noticias/ricardo-gareca{{TrackUrl()}}">Ricardo Gareca</a></li>
        </ul>
      </section>
    </nav>
