<div class="alerta alertafoto type-2 group">
    <a href="{{model.alert.url|default('#')|lower}}">
        <span class="icon icon-21"></span>
        <div class="alerta-wrap group">
            <div class="alerta-cont">
                <h2>{{model.alert.titulo}}</h2>
                <p>{{model.alert.cuerpo}}</p>
            </div>
            <img src="{{model.alert.imagen}}" alt="{{model.alert.titulo}}">
        </div>
    </a>
</div>