   <section class="widget widget-resutl">
      <!--iframe(src="http://estadisticas.conmebol.com/lastResults_new.html")-->
      <div id="outFixture">
      <div class="topFixture">
      <nav>
      <ul>
      <!-- <li data-value="0" data-id="#cntFixture" data-events="copainca" onclick="rppWR.tabsResult(this, 'tab')">Torneo del Inca</li> -->
      <li data-value="1" data-id="#cntFixture1" data-events="peru" onclick="rppWR.tabsResult(this, 'tab')" >Copa Movistar</li>
      <li data-value="2" data-id="#cntFixture2" data-events="espana" onclick="rppWR.tabsResult(this, 'tab')" >La Liga</li>
      <li data-value="3" data-id="#cntFixture3" data-events="premierleague" onclick="rppWR.tabsResult(this, 'tab')">Premier League</li>
      <li data-value="4" data-id="#cntFixture4" data-events="alemania" onclick="rppWR.tabsResult(this, 'tab')">Bundesliga</li>
      <li data-value="5" data-id="#cntFixture5" data-events="champions" onclick="rppWR.tabsResult(this, 'tab')">Champions</li>
      <li data-value="6" data-id="#cntFixture6" data-events="uefa" onclick="rppWR.tabsResult(this, 'tab')" class="active" >Europa League</li>
      <li data-value="7" data-id="#cntFixture7" data-events="copaamerica" onclick="rppWR.tabsResult(this, 'tab')" >Copa America</li>
      </ul>
      <select onchange="rppWR.tabsResult(this, 'select')">
      <!-- <option value="0" data-id="#cntFixture" data-events="copainca">Torneo del Inca</option> -->
      <option value="1" data-id="#cntFixture1" data-events="peru" >Copa Movistar</option>
      <option value="2" data-id="#cntFixture2" data-events="espana" >La Liga</option>
      <option value="3" data-id="#cntFixture3" data-events="premierleague">Premier League</option>
      <option value="4" data-id="#cntFixture4" data-events="alemania">Bundesliga</option>
      <option value="5" data-id="#cntFixture5" data-events="champions">Champions</option>
      <option value="6" data-id="#cntFixture6" data-events="uefa" selected="selected">Europa League</option>
      <option value="7" data-id="#cntFixture7" data-events="copaamerica" >Copa America</option>
      </select></nav>
      </div><!-- <div id="cntFixture" style="display:none"></div> -->
      <div id="cntFixture1" style="display:none"></div>
      <div id="cntFixture2" style="display:none"></div>
      <div id="cntFixture3" style="display:none"></div>
      <div id="cntFixture4" style="display:none"></div>
      <div id="cntFixture5" style="display:none"></div>
      <div id="cntFixture6" style="display:none"></div>
      <div id="cntFixture1">
            <script charset="utf-8"> rppWR.read({events: 'uefa', type: 'agendaMaM', matchId: ''}).render({id:'#cntFixture1'}); </script></div>
      <div id="logoDataFactory"><a rel="nofofllow" href="http://www.datafactory.la/" target="_blank"><img src="{{ehost}}/img/fuente_df.png" alt="Fuente: DataFactory" /></a></div>
      </div>
    </section>