<div class="sidebar-panel dia-sidebar sb_mas-leidas">
 <h2 class="panel-title"> Las noticias más leídas </h2>
<?php foreach (\Rpp\Services\Get\Visitas::ranking('home',$cantidad) as $e => $item):?> 
<article class=" hnews group">
	<figure class="hmedia">
		<a href="{{nUrl(item['nid'])}}">
			
			<img class="photo" src="{{ cdn_image(getNode(item['nid']).imagen_portada['hash'], 'medium' ) }}" alt="{{ getNode(item['nid']).imagen_portada['alt'] }}" width="300">
		</a>
		<figcaption class="fn hide">{{ getNode(item['nid']).titulo_corto }}</figcaption>
	</figure>
	<div class="entry-cont ">
		<footer class="hide">
			<p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
		</footer>
		
	</div><!-- .entry-cont -->
</article>
<?php endforeach;?>
</div>