<div class="sidebar-panel dia-sidebar">
 <h2 class="panel-title"> <a  href="{{host}}/tema-{{ tag }}">Un día como hoy</a>  <a class="right-link" href="{{host}}/tema-{{ tag }}"><time class="pubdate" datetime="{{ date('Y-m-d') }}"><?php echo utf8_encode(ucfirst(strftime('%e de %B',  strtotime(date("Y-m-d")) )) );?></time></a></h2>
<?php foreach (\Rpp\Services\Get\Flow::tag($tag,$cantidad) as $e => $item):?> 
<article class=" hnews group">
	<figure class="hmedia">
		<a href="{{nUrl(item._id)}}">
			
			<img class="photo" src="{{ cdn_image(getNode(item._id).imagen_portada['hash'], 'medium' ) }}" alt="{{ getNode(item._id).imagen_portada['alt'] }}" width="300">
		</a>
		<figcaption class="fn hide">{{ getNode(item._id).titulo_corto }}</figcaption>
	</figure>
	<div class="entry-cont ">
		
		
		<footer class="hide">
			<p class="source-org vcard"><a class="fn url org" href="{{host}}">RPP Noticias</a></p>
		</footer>
		
	</div><!-- .entry-cont -->

</article>
<?php endforeach;?>
</div>