{% cache "portada.sidebar.clima"  600 %}
<div class="sidebar-panel sb_weather-sidebar">
	<h2 class="panel-title">El clima en tu ciudad</h2>
	<div class="weather-title group">
		<h3>Lima</h3>
		 <select class="city" dir="rtl" onchange="if (this.value) window.location.href=this.value">
		    <option value="{{host}}/clima/lima">Mas regiones</option>
            <option value="{{host}}/clima/amazonas">Amazonas</option>
            <option value="{{host}}/clima/ancash">Ancash</option>
            <option value="{{host}}/clima/apurimac">Apurimac</option>
            <option value="{{host}}/clima/arequipa">Arequipa</option>
            <option value="{{host}}/clima/ayacucho">Ayacucho</option>
            <option value="{{host}}/clima/cajamarca">Cajamarca</option>
            <option value="{{host}}/clima/cuzco">Cuzco</option>
            <option value="{{host}}/clima/huancavelica">Huancavelica</option>
            <option value="{{host}}/clima/huanuco">Huanuco</option>
            <option value="{{host}}/clima/ica">Ica</option>
            <option value="{{host}}/clima/junin">Junin</option>
            <option value="{{host}}/clima/la_libertad">La Libertad</option>
            <option value="{{host}}/clima/lambayeque">Lambayeque</option>
            <option value="{{host}}/clima/lima">Lima</option>
            <option value="{{host}}/clima/loreto">Loreto</option>
            <option value="{{host}}/clima/madre_de_dios">Madre de Dios</option>
            <option value="{{host}}/clima/moquegua">Moquegua</option>
            <option value="{{host}}/clima/pasco">Pasco</option>
            <option value="{{host}}/clima/piura">Piura</option>
            <option value="{{host}}/clima/puno">Puno</option>
            <option value="{{host}}/clima/san_martin">San Martin</option>
            <option value="{{host}}/clima/tacna">Tacna</option>
            <option value="{{host}}/clima/tumbes">Tumbes</option>
            <option value="{{host}}/clima/ucayali">Ucayali</option>
		</select>
	</div>
      <?php 
      $data['Mon']=array('label' => 'Lunes');
      $data['Tue']=array('label' => 'Martes');
      $data['Wed']=array('label' => 'Miércoles' );
      $data['Thu']=array('label' => 'Jueves');
      $data['Fri']=array('label' => 'Viernes');
      $data['Sat']=array('label' => 'Sábado');
      $data['Sun']=array('label' => 'Domingo'); 
      ?>
	<ul class="weather-forecast group">
		<li>
			<h4>Ahora</h4>
			<div class="w<?php echo @\Rpp\Services\Get\Climas::portada('lima')->item['condition']['code']?>"><?php echo \Rpp\Services\Get\Climas::portada('lima')->item['condition']['temp']?>º <span></span></div>
		</li>
		<li>
			<h4>Mañana</h4>
			<div class="w<?php echo @\Rpp\Services\Get\Climas::portada('lima')->item['forecast'][1]['code']?>"><?php echo \Rpp\Services\Get\Climas::portada('lima')->item['forecast'][1]['high']?>º <span></span></div>
		</li>
		<li class="last">
			<h4><?php echo $data[@\Rpp\Services\Get\Climas::portada('lima')->item['forecast'][2]['day']]['label']?></h4>
			<div class="w<?php echo @\Rpp\Services\Get\Climas::portada('lima')->item['forecast'][2]['code']?>"><?php echo \Rpp\Services\Get\Climas::portada('lima')->item['forecast'][2]['high']?>º <span></span></div>
		</li>
	</ul>
</div>
{% endcache %}