<article class="main-article hnews group">
  <?php foreach (\Rpp\Services\Get\Gallery::home(1) as $position => $item) :?>
    <figure class="hmedia">

        <a href="{{nUrl(item._id)}}{{TrackUrl(position)}}">

            <p class="counter"><span class="icon-6"></span> <?=count(\Rpp\Services\Get\Content::part($item['_id'],'galeria'));?> </p>
            <img class="photo lazy"  src="{{ehost}}/images/placeholder_rpp.png"  data-src="{{cdn_image(getNode(item._id).imagen_portada['hash'],'large')}}"
                 alt="{{getNode(item._id).imagen_portada['alt']}}">
        </a>
        <figcaption class="fn hide">{{getNode(item._id).titulo_corto}}</figcaption>
    </figure>

    <div class="entry-cont ">

        <h2 class="entry-title"><a class="url" href="{{nUrl(item._id)}}{{TrackUrl(position)}}" rel="bookmark">{{getNode(item._id).titulo_corto}}</a></h2>


        <p>{{getNode(item._id).bajada}}</p>


        <footer class="hide">
            <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP Noticias</a>
            </p>
        </footer>

    </div>
    <!-- .entry-cont -->
  <?php endforeach; ?>  
                <aside id="more-galleries">
            <h2 class="panel-title">Más galerías <!-- <a class="right-link" href="/galerias">Ver todas</a> --></h2>
            

  <?php $countj=0; foreach (\Rpp\Services\Get\Gallery::home(3) as $position => $item) : $countj=$countj+1; ?>
    <?php if($countj>1){ ?>
            <article class="left-photo hnews group">
              <figure class="hmedia">
                  <a href="{{nUrl(item._id)}}{{TrackUrl(position)}}">
                      <p class="counter"><span class="icon-6"></span> <?=count(\Rpp\Services\Get\Content::part($item['_id'],'galeria'));?></p>
                      <img class="photo lazy"  src="{{ehost}}/images/placeholder_rpp.png"  data-src="{{cdn_image(getNode(item._id).imagen_portada['hash'],'small')}}"
                           alt="{{getNode(item._id).imagen_portada['alt']}}">
                  </a>
                  <figcaption class="fn hide">{{getNode(item._id).titulo_corto}}</figcaption>
              </figure>

              <div class="entry-cont ">
                  <h3 class="entry-title"><a class="url" href="{{nUrl(item._id)}}{{TrackUrl(position)}}" rel="bookmark">{{getNode(item._id).titulo_corto}}</a></h3>
                  <footer class="hide">
                      <p class="source-org vcard"><a class="fn url org" href="http://www.rpp.com.pe">RPP
                              Noticias</a></p>
                  </footer>
              </div>
              <!-- .entry-cont -->
          </article>
    <?php } ?>
  <?php endforeach; ?>  
          
        </aside>
                
                <!-- #more-galleries -->


            </article>