<div class="col-share x-sticky">
<?php $total_interaction = @\Rpp\Services\Get\Content::part($this->model->nid,'stats')['total_shared']?>
<?php $total_comment = @\Rpp\Services\Get\Content::part($this->model->nid,'stats')['total_comments']?>
  <div class="social-share" id="share-options">
    <div class="inside">
      <ul id="share-options">
        <li class="fb-share">
        <?php if($total_interaction && $total_interaction > 0):?>
          <?php if($total_interaction > 1000):?>
           <span class="count"><?php echo number_format($total_interaction/1000, 2, '.', '');?>k</span>
          <?php else:?>
           <span class="count">{{total_interaction}}</span>
          <?php endif;?>
        <?php endif;?>
          <a href="https://www.facebook.com/sharer/sharer.php?u={{host}}{{nUrl(model.nid)}}&amp;t={{getNode(model.nid).titulo}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})" rel="nofollow" >
          <span class="icon-facebook"></span>
          </a>
        </li>
        <li class="wa-share">
          <a href="whatsapp://send?text={{getNode(model.nid).titulo}} {{host}}{{nUrl(model.nid)}}" rel="nofollow" >
          <span class="icon-whatsapp"></span>
          </a>
        </li>
        <li class="tw-share">
          <a href="https://twitter.com/intent/tweet?original_referer={{host}}/p/{{model.nid}}&amp;text=<?=urlencode(\Rpp\Services\Get\Content::node($this->model->nid)->titulo_corto);?>&amp;url={{host}}/p/{{model.nid}}&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})" rel="nofollow" >
          <span class="icon-twitter"></span>
          </a>
        </li>
        <li class="gp-share">
          <a href="https://plus.google.com/share?url={{host}}{{nUrl(model.nid)}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})" rel="nofollow">
          <span class="icon-google-plus"></span>
          </a>
        </li>
        <li class="in-share">
          <a href="https://www.linkedin.com/shareArticle?url={{host}}{{nUrl(model.nid)}}&amp;title={{getNode(model.nid).titulo}}&amp;summary={{getNode(model.nid).bajada}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})" rel="nofollow">
          <span class="icon-linkedin"></span>
          </a>
        </li>
        <li class="comment">
        <?php if($total_comment && $total_comment > 0):?>
          <?php if($total_comment > 1000):?>
            <span class="count"><?php echo number_format($total_comment/1000, 2, '.', '');?>k</span>
          <?php else:?>
            <span class="count">{{total_comment}}</span>
          <?php endif;?>
        <?php endif;?>
        <a href="#section-comment"><span class="icon-chat"></span></a>
        </li>
      </ul>
    </div>
    <div class="on-share">
      <a href="#compartir" onclick='fn(this, event, {"method":"toggleClass", "to": "#share-options"})'>
        <span class="icon-forward-share"></span>
      </a>
    </div>
  </div>
</div>


