<div class="col-share x-sticky">
  <div class="social-share" id="share-options">
    <div class="inside">
      <ul>
        <li class="fb-share">
          <a href="https://www.facebook.com/sharer/sharer.php?u={{host}}&amp;t=RPP noticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
            <span class="icon-facebook"></span>
          </a>
        </li>
        <li class="wa-share">
          <a href="whatsapp://send?text=RPP noticias {{host}}" >
            <span class="icon-whatsapp"></span>
          </a>
        </li>
        <li class="tw-share">
          <a href="https://twitter.com/intent/tweet?original_referer={{host}}&amp;text=RPP noticias&amp;url={{host}}&amp;via=RPPNoticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
            <span class="icon-twitter"></span>
          </a>
        </li>
        <li class="gp-share">
          <a href="https://plus.google.com/share?url={{host}}" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
            <span class="icon-google-plus"></span>
          </a>
        </li>
        <li class="in-share">
          <a href="https://www.linkedin.com/shareArticle?url={{host}}&amp;title=RPP noticias&amp;summary=RPP noticias" onclick="fn(this, event, {&quot;method&quot;:&quot;wopen&quot;})">
            <span class="icon-linkedin"></span>
          </a>
        </li>
        <li class="comment">
          <a href="#section-comment"><span class="icon-chat"></span></a>
        </li>
      </ul>
    </div>
    <div class="on-share">
      <a href="#compartir" onclick='fn(this, event, {"method":"toggleClass", "to": "#share-options"})'>
        <span class="icon-forward-share"></span>
      </a>
    </div>
  </div>
</div>


