<?php if(\Rpp\Services\Get\Content::node($this->model->nid)->tipo != 'brandcontent'):?>
<div class="pub-wrap group">

		<div class="pub col-2 pub-300">
		    <script type="text/javascript">eplAD4M("Interna9");</script>
		</div><!-- pub-300 -->
		
		<div class="pub col-2 pub-300">
		    <script type="text/javascript">eplAD4M("Interna10");</script>
		</div><!-- pub-300 -->

	</div>
<?php endif;?>




