<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/index') }}
<body data-bg="{{model.epl_kvs}}" id='seccion' class="{{model.slug_seccion}} <?php echo @$this->model->slug_categoria ?>" data-app="{{model.js_app}}">
<div id="contenedor_div">
    <!--Header-->
    {{ partial('partials/header/index') }}
    <div class="wrapper body group">
        {{ partial('partials/portada/grilla/autores') }}
        <!-- .featured -->

        <div class="category no-cat wrap group">
            <div class="content group">
                {{ partial('partials/portada/flujo/autores') }}

                <div class="more-news">
                    <a class="btn" href="#">Ver más noticias</a>
                </div>

            </div>
            <!-- .content -->
           {{ partial('partials/portada/bloque/sidebar_seccion' , ['slug': 'autores' ]) }}
            <!-- .sidebar -->
        </div>

         {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

        

    </div>
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
