<?php setlocale(LC_TIME, "es_ES", "es_ES.utf8"); ?>
<!--Head-->
{{ partial('partials/head/indexportada') }}
<body data-bg="{{model.epl_kvs}}" id='seccion' class="{{model.slug_seccion}} <?php echo @$this->model->slug_categoria ?>" data-app="slide">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=185239485185";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div id="contenedor_div">
    <!--Header-->
    <?php $p_slug = str_replace('rpp/', '', $this->model->seccion_info->parent_slug) ;?>
    {{ partial('partials/header/indexseccion' , ['slug': p_slug ]) }}
    <div class="wrapper body group">
        {{ partial('partials/portada/grilla/' ~ model.package  ) }}
        <!-- .featured -->

        <div class="category wrap group">
            <div class="content group">
   
        {{ partial('partials/portada/bloque/tag/cronologico_1' , [ 'slug' : model.slug ] ) }}

<?php if(@$this->model->agrupador):?>
    <?php if($this->model->slug_seccion == 'actualidad' || $this->model->slug_seccion == 'peru' || $this->model->slug_seccion == 'entretenimiento'): ?>

    <div class="especial group ttl-new cajaarequipa-new">
        <h1>
            Lo Último
        </h1>
        <figure class="figure_ttl-new">
            <a href="http://ads.us.e-planning.net/ei/3/17632/Home/Ultimas?it=i&rnd=$RANDOM" target="_blank"><img src="http://ads.us.e-planning.net/eb/3/17632/Home/Ultimas?o=i&rnd=$RANDOM
" alt="Logo Caja Arequipa" /></a>
        </figure>
    </div>

    <?php else:?>
    <div class="especial group ttl-new">
        <h1>
            Lo Último
        </h1>
    </div>
    <?php endif;?>
<?php endif;?>

   <?php if($this->model->slug_categoria == 'arequipa'): ?>
    
    <div class="especial group ttl-new cajaarequipa-new">
        <h1>
            Lo Último
        </h1>
        <figure class="figure_ttl-new">
            <a href="http://ads.us.e-planning.net/ei/3/17632/Home/Ultimas?it=i&rnd=$RANDOM" target="_blank"><img src="http://ads.us.e-planning.net/eb/3/17632/Home/Ultimas?o=i&rnd=$RANDOM
" alt="Logo Caja Arequipa" /></a>
        </figure>
    </div>

   <?php endif;?>
   
                {{ partial('partials/portada/flujo/seccion', [ 'slug':model.slug ] , trackurl) }}

                <div class="more-news">
                    <a class="btn" href="/archivo/{{model.slug}}">Ver más noticias</a>
                </div>

            </div>
            {{ partial('partials/portada/bloque/sidebar_seccion' , ['slug': p_slug ]) }}
        </div>

         {{ partial('partials/ads/middle2') }}
        <!-- pub-980 -->

       

    </div>
    <!--Footer-->
    {{ partial('partials/footer/index' , [] , trackurl) }}
    <div id="pad-swipe-nav"></div>
    {{ partial('partials/footer/scripts') }}
    {{ partial('partials/footer/tracking') }}
</div>
</body>
