<div class="box-mod box-row brand-{{tag}} no-ellipsis">
	<?php $imgcb = !empty(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']);?>
	<?php if((int)$imgcb==1){ ?>
	<div style="background:transparent url('<?php echo \Rpp\Services\Get\UrlMedia::replace_cdn_raiz(@\Rpp\Services\Get\Tags::get_tag($tag)->personalidad['imagenes']['url_1020x51']) ?>') left top no-repeat;" class="box-header back-image">
	  <h3 class="title"><a href="{{host}}/tema-{{ tag }}">{{nombre}}</a></h3>
	</div>
	<?php }else{ ?>
	<div class="box-header">
	  <h3 class="title"><a href="{{host}}/tema-{{ tag }}">{{nombre}}</a></h3>
	</div>
	<?php } ?>

	<?php $cantle=1; foreach (\Rpp\Services\Get\Flow::tag($tag,$cantidad) as $e => $item):?> 
		<article class="card">
		    <div class="cont">
		      <h3><a href="{{nUrl(item._id)}}{{TrackUrl(1)}}">{{getNode(item._id).titulo}}</a></h3>
		    </div>
		  </article>
	<?php $cantle++; endforeach;?>
</div>
