<div class="item-resultados box">
    <section id="RST1"><div class="rppWR-cntMatch">
    <table><thead><tr><td class="rppWR-tdh1" colspan="3">
    <span>{{df_match(model.torneo,match)['nombre_fecha']}}</span>
    <time><?php echo utf8_encode(ucfirst(strftime('%A', Rpp\Services\Get\Resultados::match($this->model->torneo,$match)['time'])));?> {{date('d/m/Y',df_match(model.torneo,match)['time'])}} &nbsp;<?php echo date('H:i', strtotime("-2 hour",Rpp\Services\Get\Resultados::match($this->model->torneo,$match)['time']))?></time>
    </td></tr></thead><tbody>
    <tr>
    <td class="rppWR-td1"><div><figure><img src="http://eventos.rpp.com.pe/services/datafactory/escudos/{{df_match(model.torneo,match)['local']['id']}}.png" alt="Chile" width="42" height="42"></figure></div><div>{{df_match(model.torneo,match)['local']['nombre']}}</div></td>
    <td class="rppWR-td2"><div class="rppWR-center">{{ partial('partials/resultados/match/match_list_' ~ df_match(model.torneo,match)['estado'] ,['match': match]) }}
</div></td>
    <td class="rppWR-td3"><div><figure><img src="http://eventos.rpp.com.pe/services/datafactory/escudos/{{df_match(model.torneo,match)['visita']['id']}}.png" alt="Ecuador" width="42" height="42"></figure></div><div>{{df_match(model.torneo,match)['visita']['nombre']}}</div></td></tr>
    </tbody></table></div></section>
    <ul class="list-est">
      <li><a href="#">Previa</a><i class="icon icon-caret-right"></i></li>
      <li><a href="#">Ir al directo</a><i class="icon icon-caret-right"></i></li>
      <li class="active"><a href="#">Cronica</a><i class="icon icon-caret-right"></i></li>
    </ul>
</div>